### ISSUE TITLE
[Bug]: Unable to add devices after software update

### ISSUE THREAD

**Issue by xixihahajeff** [homebridge-eufy-security/plugin#101]
### What happened?

I am unable to connect my Eufy security devices after software update. Things were working fine before the update. It keeps getting stuck at “Homebridge running at port 51876”.

The devices fail to be added. Please advise. Thanks.

### Device Type

Contact Sensor (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
06/07/2022, 10:10:13 AMEufy Security Bridge starting
06/07/2022, 10:10:51 AMEufy Security BridgeLoaded plugin 'homebridge-eufy-security'
06/07/2022, 10:10:51 AMEufy Security BridgeLoading 1 platforms...
06/07/2022, 10:10:52 AMEufy Security BridgeBridge is running on port 51876.
06/07/2022, 10:11:02 AMEufy Security BridgeConfiguration change
06/07/2022, 10:11:02 AMeufysecuritybridge stopping
06/07/2022, 10:11:08 AMEufy Security Bridge starting
06/07/2022, 10:11:21 AMEufy Security BridgeLoaded plugin 'homebridge-eufy-security'
06/07/2022, 10:11:21 AMEufy Security BridgeLoading 1 platforms...
06/07/2022, 10:11:22 AMEufy Security BridgeBridge is running on port 51876.
```

**Comment by thieren** [comment]
Closed, since this most likely a duplicate and stale
