### ISSUE TITLE
[enhancement]: Two-way communication for Doorbell

### ISSUE THREAD

**Issue by cpvbruno** [homebridge-eufy-security/plugin#103]
### Describe the solution you'd like

**Current Situation**
When someone rings the bell, I need to open eufy app to respond, ideally using Apple Home app would be way better

**Proposed Change**
Implement Two-way audio communication, and maybe if possible also some "fake switches" to play the "doorbell pre-recorded answers" that are available in eufy app

**Comment by thieren** [comment]
Hi @cpvbruno 

This is already planned.

Unfortunately the needed functionality has just been added to `eufy-security-client` in version 2.1.0 and this version has some bugs that prevent it from being used straight away with this plugin. There's an issue about this on the repo.

Nonetheless we'll try to implement it as soon as possible.

**Comment by cpvbruno** [comment]
I enabled it but the option to disable “RTSP” disappeared, do you experience the same?

**Comment by cpvbruno** [comment]
I just tried on my doorbell and I couldn't hear anything at all, unfortunately :(

**Comment by cpvbruno** [comment]
![image](https://user-images.githubusercontent.com/5808343/179802671-7b531837-d8ec-4948-ac64-1996849fea68.png)

**Comment by andyrooo82** [comment]
I've tested talkback and it's working great. Thanks for this awesome implementation.

**Comment by cpvbruno** [comment]
> I've tested talkback and it's working great. Thanks for this awesome implementation. 

Did you have to tweak anything to make it work?

**Comment by DaveX510** [comment]
Just updated and enabled talkback in settings. Both my doorbell and indoor cam are working great!

**Comment by thieren** [comment]
> I just tried on my doorbell and I couldn't hear anything at all, unfortunately :(

@cpvbruno what is your exact homebridge setup? As mentioned above I had trouble with talkback on windows which looked kinda like your screenshot: the talkback process just quits after approximately 20-30 seconds with code 0 and signal null.

**Comment by andyrooo82** [comment]
> > I've tested talkback and it's working great. Thanks for this awesome implementation. 
> 
> Did you have to tweak anything to make it work? 

Hi, just checked the talkback option in the settings (found in the ui)

**Comment by cpvbruno** [comment]
@thieren 
[homebridge.log.txt](https://github.com/homebridge-eufy-security/plugin/files/9147455/homebridge.log.txt)

**Comment by thieren** [comment]
@cpvbruno Please don't mix up the issues. ;-)

Here the last question was about your exact homebridge setup. If you're running homebridge on windows, this might explain why talkback is not working. If it's another installation method, I'd have to try it maybe.

The log was for #114 I think. And no. The storage path to the plugin specific `log-lib.log` file will be written at startup of the plugin since the latest beta. Please get me this.

**Comment by cpvbruno** [comment]
Oh sorry @thieren , my setup is a MacBook Pro M1

**Comment by thieren** [comment]
Didn't try it with this, but your luck is, that I have the same device. Will try to reproduce later.
Did you install with this [method](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-macOS)?

**Comment by cpvbruno** [comment]
Yes, this exactly method

**Comment by cpvbruno** [comment]
I was accessing my Mac remotely so I didn't see this bunch of messages, it could definitely be the problem, I'll check now 

![image](https://user-images.githubusercontent.com/5808343/179926756-26161b1b-0f9c-4af8-b0ba-d20200da24dd.jpeg)

**Comment by cpvbruno** [comment]
I allowed this permission and now I don't see errors in the logs at least, I'll soon test with my real doorbell to see if I can hear something coming from he speaker

**Comment by thieren** [comment]
Yeah that definitely looks like a possible cause. :-D

Let me know if this was it.

**Comment by cpvbruno** [comment]
It worked like a charm ❤️

**Comment by thieren** [comment]
Is implemented with release of 2.1.0

**Comment by unstressable** [comment]
I've got problems with talkback audio. Hearing is quite fine, but if I want to speak to the cam just a lot of weird noise comes out. I use Raspi4, Video works fine at 640x480p.
