### ISSUE TITLE
[Bug]: No stream available in Apple TV (Neither in the doorbell ring notification)

### ISSUE THREAD

**Issue by cpvbruno** [homebridge-eufy-security/plugin#114]
### What happened?

The doorbell stream works fine on my iPhone, Apple Watch and Macbook, but on Apple TV no matter what I do I can't stream there.
I get the "someone ring the bell" notification but it comes without a screenshot/live feed.

I already tried to restart several times the Apple TV and home bridge, but nothing made it work.
I also have other cameras in my house (with official HomeKit support), those I can stream normally.

### Device Type

Doorbell (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X 11+ (Supported)

### Relevant log output

```shell
Nothing gets printed out in the logs when Apple TV tries to show the camera, for some reason it feels like the Apple TV is not even trying, no matter what I do.

Feel free to close this issue if you are 100% sure the problem is on my Apple TV
```

**Comment by thieren** [comment]
Hi!

Can you check if you still have issues on the latest beta?
For me at least Apple TV streaming works fine.

Thx!

**Comment by andyrooo82** [comment]
> Hi!
> 
> 
> 
> Can you check if you still have issues on the latest beta?
> 
> For me at least Apple TV streaming works fine.
> 
> 
> 
> Thx!

Ok I'll update to beta 8 and report back in a day or so to see if this issue is resolved.

**Comment by thieren** [comment]
@cpvbruno then we're back to: please enable debug and send me `log-lib.log` ;-)

**Comment by cpvbruno** [comment]
[Unknown 2.zip](https://github.com/homebridge-eufy-security/plugin/files/9183307/Unknown.2.zip)

**Comment by cpvbruno** [comment]
Sorry the delay 🍻

**Comment by cpvbruno** [comment]
Most recently when I moved my server from MacBook to raspberry pi the camera begin working again, but now it’s already not working anymore, also, the snapshot when someone rings the bell never works 
![789D9B1D-7F1F-48F2-9502-2126F60186E2](https://user-images.githubusercontent.com/5808343/180839881-3be4f39f-5844-4a7c-812a-ea3f94588723.jpeg)

**Comment by thieren** [comment]
> Sorry the delay 🍻

No problem. I have deleted your zip file, since it could contain some sensitive information. Sorry should have mentioned that earlier. Anyhow I saw that you have not enabled debug mode for the plugin. Could you do that and send me the logs with a new try?
You could send them via discord or we use something like google drive...

**Comment by cpvbruno** [comment]
I have the file with me, how do you prefer that I share?

**Comment by cpvbruno** [comment]
Sent in discord

**Comment by andyrooo82** [comment]
I've updated to latest beta and it seems to work for me now.

**Comment by andyrooo82** [comment]
> I've updated to latest beta and it seems to work for me now. 

Further update, the stream has stopped working again however I think I know why. It seems to happen when switching wifi networks. I have two wifi networks 1 with the Pi and all my IoT stuff on and the other is a VPN network which I switch my Apple TV too when required. I switched to my vpn network for for a while after switching back I get no stream from the doorbell (my native HomeKit cameras work though). I have to go into HomeKit settings and remove the doorbell, restart the Apple TV, then add it back, then restart the Apple TV again.

**Comment by cpvbruno** [comment]
Today out of nowhere it started working again in Apple TV, the only thing that happened was that I was a few days traveling so the Apple TV was off those days. (Maybe this info helps)

**Comment by cpvbruno** [comment]
And now it stopped working again.

**Comment by thieren** [comment]
As discussed on discord I don't think this is an issue with the plugin itself. It seems to be more likely a network/HomeKit issue. If you think otherwise let me know. But will close this, since I can't see what else can be done here.
