### ISSUE TITLE
[Bug]: Contact Sensor

### ISSUE THREAD

**Issue by federicodigiacomo** [homebridge-eufy-security/plugin#118]
### What happened?

Hi all, I noticed that the eufy's contact sensor status update is not working even after polling minutes

### Device Type

Contact Sensor (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Debian 10+ (Supported)

### Relevant log output

```shell
log
```

**Comment by thieren** [comment]
Hi @federicodigiacomo 

Didn't look into the entry sensor myself yet, but I can try to help.

Can you enable debug messages for the plugin and get me the `log-lib.log`file? Then I can have a look.

If you need help with any of that let me know.

**Comment by federicodigiacomo** [comment]
Hi thanks, I enabled debugging of the plugin. What is the file's path: log-lib.logfile?

**Comment by thieren** [comment]
If you upgrade to latest beta there should be an info message in the log with the storage path.
but usually it's something like `/var/lib/homebridge/eufysecurity/`or `/var/local/lib/...`

**Comment by federicodigiacomo** [comment]
from log for contact sensor' name: Porta Dx Salone, polling 3 minutes:
(the contact sensor was closed)
[7/20/2022, 8:43:27 AM] [EufySecurity-2.0.1] DEBUG: Porta Dx Salone GET DeviceBatteryLow: false
[7/20/2022, 8:43:27 AM] [EufySecurity-2.0.1] DEBUG: Porta Dx Salone GET DeviceSensorOpen: false

(the contact sensor was open)
[7/20/2022, 8:45:57 AM] [EufySecurity-2.0.1] DEBUG: Porta Dx Salone GET DeviceSensorOpen: false

**Comment by thieren** [comment]
> from log for contact sensor' name: Porta Dx Salone, polling 3 minutes:
> 
> (the contact sensor was closed)
> 
> [7/20/2022, 8:43:27 AM] [EufySecurity-2.0.1] DEBUG: Porta Dx Salone GET DeviceBatteryLow: false
> 
> [7/20/2022, 8:43:27 AM] [EufySecurity-2.0.1] DEBUG: Porta Dx Salone GET DeviceSensorOpen: false
> 
> 
> 
> (the contact sensor was open)
> 
> [7/20/2022, 8:45:57 AM] [EufySecurity-2.0.1] DEBUG: Porta Dx Salone GET DeviceSensorOpen: false

Thx for the snippet, but if you enable debug messages and reproduce the issue there should be a lot more info in the file I've mentioned. I'd need that.

**Comment by federicodigiacomo** [comment]
hi thank you very much, i downloaded the file and installed discord. How do I contact you to send you the file? Sorry

**Comment by thieren** [comment]
> hi thank you very much, i downloaded the file and installed discord. How do I contact you to send you the file? Sorry

Here's the link: https://discord.com/channels/432663330281226270/876907345962229791

You'll find me in the `eufy-security` channel.

**Comment by federicodigiacomo** [comment]
your invite not function sorry pleas help me

**Comment by federicodigiacomo** [comment]
send it in eufy-security channel, thanks!

**Comment by thieren** [comment]
After looking at the logs I suspect that you don't receive push notifications fro the cloud. If I had to guess I would say this is due to #59 

You could try a restart, but as soon as you open the configuration screen and don't restart afterwards this will likely happen again.
Another option would be to try the latest beta.

But since this doesn't seem to be an issue regarding the contact sensor of the plugin I'll close this.

**Comment by thieren** [comment]
Reopening, since there's still an issue. After debugging with @federicodigiacomo it seems that the eufy-security-client is not evaluating the updates on the sensor correctly.

**Comment by thieren** [comment]
As discovered in discord this was an issue with the settings in the eufy app. The push notifications for the sensors were not enabled. So a similar issue as was described [here](https://github.com/homebridge-eufy-security/plugin/wiki/Common-Issues#motion-detection-issues).
