### ISSUE TITLE
[Bug]: can’t login infinite gear rotating

### ISSUE THREAD

**Issue by ayyyop** [homebridge-eufy-security/plugin#129]
### What happened?

I’ve tried logging in multiple times. It’s an infinite‘s settings cog will spinning. I tried uninstalling and reinstalling and nothing seem to work for me
![IMG_0875](https://user-images.githubusercontent.com/110443553/182291571-ccf20a1e-4d1c-4e77-ad96-d379b05af558.jpeg)
.

### Device Type

other (UnSupported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v12 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
Na
```

**Comment by thieren** [comment]
Hi @ayyyop 

This is most likely due to a bug in 2.0.1 with node v12.

You could try the latest beta, or update your node version. Both should be sufficient to get you going.

**Comment by thieren** [comment]
Is fixed with release of 2.1.0
