### ISSUE TITLE
Devices not showing up[Bug]: 

### ISSUE THREAD

**Issue by ziggitipop** [homebridge-eufy-security/plugin#13]
### What happened?

![image](https://user-images.githubusercontent.com/8981231/164466184-9422313b-f5cb-4aaf-95c2-c7b296813a2c.png)

I'm using my main account without 2fa and I still can't see my devices. Tried clearing cache and installing beta with no success. 

### Device Type

Doorbell (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X 11+ (Supported)

### Relevant log output

```shell
4/21/2022, 5:15:19 PM] [Homebridge UI] [homebridge-eufy-security] [1.0.8] DEBUG: Response: { code: 0, msg: 'Succeed.' }
[1.0.8] DEBUG: Push token registered successfully
[1.0.8] DEBUG: Request: {
  method: 'post',
  endpoint: 'v1/app/review/app_push_check',
  baseUrl: 'https://security-app.eufylife.com',
  token: 'e582434c45fa5640cb15c5e87f7333e9006bc1abdb3b8664',
  data: { app_type: 'eufySecurity', transaction: '1650546919489' },
  headers: {
    app_version: 'v3.3.1_1058',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'US',
    language: 'en',
    openudid: '182a48f9c659419e',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: '9f928c186244',
    Model_type: 'PHONE',
    timezone: 'GMT+04:00',
    'Cache-Control': 'no-cache',
    'X-Auth-Token': 'e582434c45fa5640cb15c5e87f7333e9006bc1abdb3b8664'
```

**Comment by lenoxys** [comment]
Hello Please use the beta.

**Comment by ziggitipop** [comment]
> Hello Please use the beta.

I did that, now I can see the devices on my home app but they all look like security devices or alarms (pic below).

![image](https://user-images.githubusercontent.com/8981231/164712860-75f6274a-b004-4fa8-a83d-ecab2ffb53ce.png)

The doorbell looks like a camera but it's stuck on "not responding"
![image](https://user-images.githubusercontent.com/8981231/164712973-0d697379-ba29-400f-ba75-7dd336f413d8.png)

Here is what the log says when I try to view the doorbell camera:
[4/22/2022, 4:15:22 PM] [EufySecurity] Doorbell FFmpeg process creation failed: spawn ffmpeg ENOENT
[Doorbell] Snapshot request handler provided empty image buffer!
[4/22/2022, 4:15:44 PM] [EufySecurity] Doorbell Starting video stream: 640x480, 30 fps, 299 kbps 
[4/22/2022, 4:15:44 PM] [EufySecurity] Doorbell FFmpeg process creation failed: spawn ffmpeg ENOENT
[4/22/2022, 4:15:44 PM] [EufySecurity] Doorbell Stopped video stream.

any suggestions welcome

**Comment by lenoxys** [comment]
hello, this is a new issue for the camera doorbell. Can you create a new issue? It helps us to organise and help people to seek answer based on what they face. Thanks for your understanding.

For other camera : https://github.com/homebridge-eufy-security/plugin/wiki/Configuration#camera-or-motion-sensor-

**Comment by thieren** [comment]
Closed since the original issue was resolved. Please reopen if there are new things to share regarding this.
