### ISSUE TITLE
[Bug]: ffmpeg update failed when installing beta

### ISSUE THREAD

**Issue by Mike92115** [homebridge-eufy-security/plugin#130]
### What happened?

I have been using the plugin for a while now and keeping current with the betas previously with version 1.0.8 it worked for me.  I have since updated a couple of times with the betas and somewhere along the line my Doorbell T8210 stopped being able to stream.   I am not sure if this was/is related to the betas or that I am running this using Docker on a Synology NAS (I know it's not supported).   Anyway since it was not working after looking at the docs, I uninstalled and cleared everything so I could start over.   

I first installed v2.0.1 and that went so before I adding my devices to HomeKit I tried to update to the latest beta RC0 that I had previously tried but was not streaming and getting no response.  

Thank you,
Mike

### Device Type

Doorbell (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Docker (UnSupported)

### Relevant log output

```shell
I have put the full log file here: https://mike-underwood.com/images/homebridge-efuy-log.txt

 This is where I run into problems with the following: 

USER: root
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-eufy-security@2.1.0-rc.0

[##################] - reify:protobuf-typescript: http fetch GET 200 https://registry.
> ffmpeg-for-homebridge@0.0.9 install
> node install.js

Downloading ffmpeg from https://github.com/homebridge/ffmpeg-for-homebridge/releases/latest/download/ffmpeg-debian-x86_64.tar.gz
node:events:505####] / reify:protobuf-typescript: http fetch GET 200 https://registry.
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/home/homebridge/.npm/_ffmpeg_for_homebridge/.download'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/homebridge/.npm/_ffmpeg_for_homebridge/.download'
}
npm ERR! code 1
npm ERR! path /homebridge/node_modules/ffmpeg-for-homebridge
npm ERR! command failed
npm ERR! command sh /tmp/install-3c143732.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2022-08-03T17_59_53_743Z-debug-0.log

Operation failed. Please review log for details.


After that I tried creating .download and got the following:


[##################] \ reify:protobuf-typescript: timing reifyNode:node_modules/homebr
> ffmpeg-for-homebridge@0.0.9 install
> node install.js

Downloading ffmpeg from https://github.com/homebridge/ffmpeg-for-homebridge/releases/latest/download/ffmpeg-debian-x86_64.tar.gz
node:events:505####] | reify:protobuf-typescript: timing reifyNode:node_modules/homebr
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, open '/home/homebridge/.npm/_ffmpeg_for_homebridge/.download'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'open',
  path: '/home/homebridge/.npm/_ffmpeg_for_homebridge/.download'
}
npm ERR! code 1
npm ERR! path /homebridge/node_modules/ffmpeg-for-homebridge
npm ERR! command failed
npm ERR! command sh /tmp/install-062be8f2.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2022-08-03T18_35_13_090Z-debug-0.log

Operation failed. Please review log for details.
```

**Comment by Mike92115** [comment]
Yes, I checked the common issues page

**Comment by thieren** [comment]
Hey @Mike92115 

that's a bug from npm. Please update your npm and I think you'll have to update permissions with `sudo chown -R 999:996 "/home/homebridge/.npm"` as described [here](https://github.com/homebridge-eufy-security/plugin/issues/96)

**Comment by Mike92115** [comment]
@thieren Thank you, I updated npm and then re-tried installing the RC and no change.  I am already at version 2.0.1 not updating from 1.0.8 but that should not matter since the error appears to be the same.   I will look later to see if I can find anything else.

USER: root
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-eufy-security@2.1.0-rc.0

[##################] / reify:protobuf-typescript: timing reifyNode:node_modules/homebr
> ffmpeg-for-homebridge@0.0.9 install
> node install.js

Downloading ffmpeg from https://github.com/homebridge/ffmpeg-for-homebridge/releases/latest/download/ffmpeg-debian-x86_64.tar.gz
node:events:505####] | reify:protobuf-typescript: timing reifyNode:node_modules/homebr
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, open '/home/homebridge/.npm/_ffmpeg_for_homebridge/.download'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'open',
  path: '/home/homebridge/.npm/_ffmpeg_for_homebridge/.download'
}
npm ERR! code 1
npm ERR! path /homebridge/node_modules/ffmpeg-for-homebridge
npm ERR! command failed
npm ERR! command sh /tmp/install-f2ff2724.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2022-08-04T13_31_36_201Z-debug-0.log

Operation failed. Please review log for details.

**Comment by thieren** [comment]
Did you also reset the file and directory permissions accordingly?

**Comment by Mike92115** [comment]
Yes I did run the chown and that completed without any errors

**Comment by thieren** [comment]
Did you run it with `999:996`? Maybe the user/group id is different with your system. What's the output of `id`?

**Comment by Mike92115** [comment]
Thank you, I did that and corrected the UID and GID and then tried to install the RC and Beta and am still getting the same error.  So I tried changing the user/group to homebridge/homebrige just to try it and no difference.

**Comment by thieren** [comment]
I guess the best would be to try removing ffmpeg-for-homebridge again (e.g. `sudo npm uninstall -g ffmpeg-for-homebridge`) and just let it install via the plugin. Also try removing the `.download` directory altogether.

Do you use discord? Maybe you can dm me and we can try a debugging session together.

Anyway it seems to be solely related to your specific setup, not the plugin in general.

**Comment by Mike92115** [comment]
I will give that a try over the weekend and thank you

**Comment by Mike92115** [comment]
@thieren Removing the directory worked.  THANK YOU!

**Comment by thieren** [comment]
Glad it works for you now!
