### ISSUE TITLE
[Bug]: -2C Pro- IR LEDs turn on sporadically as soon as the plugin is used. 

### ISSUE THREAD

**Issue by novus84** [homebridge-eufy-security/plugin#134]
### What happened?

Hello

as soon as I activate my 2c Pro in Homekit as a camera, it sporadically turns on the IR LEDs. I can see this through another camera, which then always reports a movement. Even if I do not use the HOME app. 

As soon as I deactivate the Eufy plugin, this "error" does not occur. My battery lasts 2 to 3 weeks only with the Plugin enabled. 

My settings (active options): 

Type: Camera
Display Homekit Enable Button
Unbridge Camera
Use RTSP
Enable Audio

Homebridge 1.5.0

Do you have a hint for me what I can do? Thank You! 

### Device Type

Indoor Camera (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

v16 (Supported)

### Operating System

Ubuntu 18.04+ (Supported)

### Relevant log output

```shell
.
```
homebridge-eufy-security v2.0.1

**Comment by thieren** [comment]
Hey @novus84 

Now that's an unusual issue. 🥇 

I'm not sure that I can help, but we'll try together. Let's get this step by step:

1. Can you share your json configuration without the sensitive info please?
2. It'd be nice if you could enable debug messages and restart the plugin. After said motion trigger, please take note of the exact time (down to seconds if possible) and get me a log snippet from +/- 5 seconds of the event.
3. Can you say approximately how often this occurs? Is it with a fixed period, like every 10 minutes?

Honestly I don't really know what could cause this. Maybe the eufy-security-client is requesting some data that triggers the IR lights in some way.

**Comment by thieren** [comment]
Closed since this is stale. Please report back if the issue persists.
