### ISSUE TITLE
[Bug]: Can't use camera as motion detector

### ISSUE THREAD

**Issue by fullphat** [homebridge-eufy-security/plugin#142]
### What happened?

Was having some issues with my T8420 floodlight camera and this plugin so I removed it and just used the base station element instead.  This massively improved HomeBridge performance and it seems guard mode is now working well.  I just tried to re-add the camera as a motion sensor only but it still appears in HomeKit as a (broken) camera and causes all sorts of HomeBridge slowdowns even though it's set to be unbridged.

How can I get this configured as a motion sensor only as I'd really like access to the floodlight light switches.

### Device Type

Floodlight (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X 11+ (Supported)

### Relevant log output

```shell
N/A
```

**Comment by thieren** [comment]
Hi @fullphat 

Sounds to me like the accessory was not orderly removed from homebridge (so it's a caching issue). You can try the solutions described [here](https://github.com/homebridge-eufy-security/plugin/wiki/Common-Issues#unexpected-homekit-behaviour) and [here](https://github.com/homebridge-eufy-security/plugin/wiki/Bridged-and-Unbridged-Mode-and-Problems#whats-the-solution).
