### ISSUE TITLE
[Bug]: unable to change the ‘mode’ of Home Security System

### ISSUE THREAD

**Issue by shamzman** [homebridge-eufy-security/plugin#15]
### What happened?

I’m unable to change base station guard (arm) mode in the iOS Home app. After installing homebridge and the eufy security plugin the base station shows up in Home correctly as a security system. However, when I select it and try to change the mode (ie Home, Away, Night, Off) the app displays the status as ‘arming’ for a few minutes and then closes without changing the mode. 

I expected that when I select a different mode in the Home app it would change the mode of the Eufy Home Security system. 

### Device Type

Station (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Other (UnSupported)

**Comment by lenoxys** [comment]
Hello,

Did you try with the beta version ?

**Comment by shamzman** [comment]
Hi,
@lenoxys thanks for your suggestion. Just tried v1.1.1-beta.56 am continuing encounter the same problem.

**Comment by lenoxys** [comment]
Can you enable debug mode, replicate your issue and attached the output here ?

**Comment by shamzman** [comment]
[log-lib.log.gz](https://github.com/homebridge-eufy-security/plugin/files/8597838/log-lib.log.gz)

Here is log of what happened when the system was in 'Home' mode and I selected 'Away' in the Home app

**Comment by shamzman** [comment]
@lenoxys i updated the latest beta as of yesterday (v2.x) and the issue is now resolved. Thanks for the great work
