### ISSUE TITLE
[Bug]: Plugin slows down Homebridge

### ISSUE THREAD

**Issue by cbwilliamsnh** [homebridge-eufy-security/plugin#152]
### What happened?

A bug happened!

### Device Type

Indoor Camera (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X 11+ (Supported)

### Relevant log output

```shell
[8/29/2022, 9:38:18 AM] [homebridge-eufy-security] This plugin slows down Homebridge. The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Outdoor - Right Side 7DDF' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
```

**Comment by thieren** [comment]
Hi @cbwilliamsnh 

Can you provide additional info?

1. Does streaming work (delayed obviously)
2. Can you enable debug messages for the plugin and provide the log output when you try to stream? From start to finish.

Thx!

**Comment by cbwilliamsnh** [comment]
When I enabled debug I was able to see one live stream and then saw two exceptions (that I wasn't able to capture due to log scrolling) and then I couldn't see any live streams in the Home app (still can see every camera stream in the Dufy security app).

Now I'm seeing the following in the log when trying to view a stream in the Home app:

```[8/29/2022, 2:04:40 PM] [EufySecurity-2.0.1] ERROR: Local livestream didn't start in time. Abort livestream request.
[8/29/2022, 2:04:40 PM] [EufySecurity-2.0.1] ERROR: Outdoor - Left Side Unable to start the livestream: no started livestream found
[8/29/2022, 2:04:40 PM] [EufySecurity-2.0.1] INFO:  Outdoor - Left Side Starting video stream: 640x480, 30 fps, 299 kbps  (AAC-eld)
TypeError: ffmpegInput is not iterable
    at StreamingDelegate.startStream (/usr/local/lib/node_modules/homebridge-eufy-security/src/accessories/streamingDelegate.ts:676:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```

**Comment by cbwilliamsnh** [comment]
I'm also happy to install the beta 2.2.0 version if that makes sense.

**Comment by thieren** [comment]
I don't think the beta would help here since it seems your livestream can't start. To see why this is, I'd need your full log (log-lib.log and eufy-log.log files from the plugin). Can you send me these via discord or a cloud service?

**Comment by cbwilliamsnh** [comment]
And where do I find the logs?

Thank you,
Chuck

--

**Comment by thieren** [comment]
There is an option to download the logs in the configuration ui of the plugin: https://github.com/homebridge-eufy-security/plugin/wiki/Basic-Troubleshooting#enable-logging

**Comment by cbwilliamsnh** [comment]
I will get these to you later today.

Thank you,
Chuck

--

**Comment by cbwilliamsnh** [comment]
@thieren what's your Discord id? 

I removed the plugin and all the HK devices and now I only see the doorbell camera to be added back into HK and then reinstalled the plugin (reading the installation instructions this time! So I now have a dedicated admin account for the plug-in!)

I have not yet added back in the two Homebase2 bridges as they say I need to press the reset button which I assume will also reset all the connected camera which are install where they can't be reached without a ladder to take down and re-sync to the Homebase2, so I haven't done that yet. Is this what's preventing me from adding the other six cameras back into HK?

**Comment by cbwilliamsnh** [comment]
I'm now running all six eufy 2C cameras in bridged mode as this appears to be the only way I can get them into HK right now.

Attached are current log files (running v2.1.0-rc5).

[homebridge-eufy-security-logs.zip](https://github.com/homebridge-eufy-security/plugin/files/9462584/homebridge-eufy-security-logs.zip)

**Comment by thieren** [comment]
> I'm now running all six eufy 2C cameras in bridged mode as this appears to be the only way I can get them into HK right now.

If you set the m to unbridged you should see a setup code in the logs on startup. With this you should be able to see them in HK. Or simply said: If you can see them in the eufy app with the account you used with the plugin, you should be able to connect them in HK.

In Discord you can find me in the channel for this plugin. An invitation link can be found via the 'new issue' page. My id is `therein#9191`

I'll have a look at the logs later. 😉

**Comment by thieren** [comment]
As already discussed on discord this seems to be an issue of `eufy-security-client`.

**Comment by cbwilliamsnh** [comment]
Yes, working with bropat on the issue there.

**Comment by lenoxys** [comment]
should be fixed
