### ISSUE TITLE
[Bug]: newest beta version 2.0 beta 1 putting entire Homebridge in boot/crash/restart loop.  

### ISSUE THREAD

**Issue by DolmensDude** [homebridge-eufy-security/plugin#16]
### What happened?

the previous beta, 1.1.56 or something like that, was actually okay.

the issue that's getting raised is that while registering new accessories, or updating during startup, it throws an error saying a particular serial number is already registered... seems to always happen on my flood cam pro 2, always the 2nd of the two, or... one of the 6 motion sensors...  

unfortunately, it was taking down the entire homebridge installation, so other plugins were shutting down and restarting in this loop.

I couldn't leave the plugin installed - I uninstalled, reinstalled, refreshed the devices, did the login procedure again... but as this was taking down everything, I had to uninstall and leave uninstalled. The previous beta is not available to (re)install, so I'm a bit stuck in providing better and more info.

### Device Type

Floodlight (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Docker (UnSupported)

### Relevant log output

```shell
[5/1/2022, 3:16:18 PM] [EufySecurity] Updating accessory: Exterior West
[5/1/2022, 3:16:19 PM] DuplicateDeviceError: Device with this serial XXXXXXXXXXXXXXX exists already and couldn't be added again!
    at EufySecurity.addDevice (/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/eufysecurity.ts:285:19)
    at EufySecurity.handleDevices (/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/eufysecurity.ts:491:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[5/1/2022, 3:16:19 PM] Got SIGTERM, shutting down Homebridge...
[5/1/2022, 3:16:19 PM] [EufySecurity] Finished shutdown!
[5/1/2022, 3:16:19 PM] Got SIGTERM, shutting down child bridge process...
[5/1/2022, 3:16:19 PM] Got SIGTERM, shutting down child bridge process...
```

**Comment by T18DJ** [comment]
Hey, I got the exact same issue!
For me it occurs when changing the doorbel camera from "Motion sensor" to "Camera".
When I put it back to "Motion sensor" the error disappeared luckily.

**Comment by lenoxys** [comment]
Hello,

Got the issue to with doorbell. Beta 2.0 introduced the 2.0.0 lib update as well.

I've already fill-in a bug issue :
https://github.com/bropat/eufy-security-client/issues/145

**Comment by DolmensDude** [comment]
> Hello,
> 
> Got the issue too with doorbell. Beta 2.0 introduced the 2.0.0 lib update as well.
> 
> You can revert back to the previous beta : https://github.com/homebridge-eufy-security/plugin/wiki/Beta-Version
> 
> I've already fill-in a bug issue : [bropat/eufy-security-client#145](https://github.com/bropat/eufy-security-client/issues/145)

Hi, I tried sudo npm install homebridge-eufy-security@1.1.1-beta.56 -g to revert back, but could not get it to go. As soon as this bug is resolved, believe me, I'll be back to test!

**Comment by lenoxys** [comment]
> > Hello,
> > Got the issue too with doorbell. Beta 2.0 introduced the 2.0.0 lib update as well.
> > You can revert back to the previous beta : https://github.com/homebridge-eufy-security/plugin/wiki/Beta-Version
> > I've already fill-in a bug issue : [bropat/eufy-security-client#145](https://github.com/bropat/eufy-security-client/issues/145)
> 
> Hi, I tried sudo npm install homebridge-eufy-security@1.1.1-beta.56 -g to revert back, but could not get it to go. As soon as this bug is resolved, believe me, I'll be back to test!

try to uninstall from home bridge then install directly through CLI

**Comment by DolmensDude** [comment]
tried multiple times, 1st time reboot with 1.1.1 beta56 errors, but restarts and then goes from there.  

am most of the way back now, only that the doorbell cams and floodlight pro 2s only work now when not unbridged.  

there is also an option to choose RSTP for the doorbells, but RSTP has never provided any working functionality on those.

I can however force update the latest displayed frame - that's a nice touch from what these things would otherwise do.

Again, *very* happy about where this is heading!

**Comment by TOTO-DK** [comment]
Same problem here - also with the new Beta2:

DuplicateDeviceError: Device with this serial T8210P342...... exists already and couldn't be added again!

Tried everything; incl. new and totally clean HomeBridge install....

Previous 1.1.1 Beta56 worked very well, but now I'm only able to roll-back to 1.0.8, which doesn´t work particularly well.

Keep up the very good work ;-)

**Comment by lenoxys** [comment]
Hello,

this should be fix on 2.0.0.beta.3

**Comment by TOTO-DK** [comment]
With the new Beta3 you're almost there; devices are added now, and gets the cached snapshots from Eufy Base.
But live stream within HomeKit crashes the plug-in, which restarts though and the connections are reestablished. So one bug to go in my opinion, and you're there!
Indeed some very nice work so far 👍😆

**Comment by lenoxys** [comment]
> With the new Beta3 you're almost there; devices are added now, and gets the cached snapshots from Eufy Base.
> But live stream within HomeKit crashes the plug-in, which restarts though and the connections are reestablished. So one bug to go in my opinion, and you're there!
> Indeed some very nice work so far 👍😆

this is a duplicate issue of #20

**Comment by gdotp01** [comment]
I’ve just downgraded to v1.8 as v2.0 has some bug issues with crashing. My floodlight cam was set up as an unabridged accessory and any interaction with this caused homebridge to crash and restart. This happened regardless of if it was set up as a sensor or camera.

**Comment by lenoxys** [comment]
thanks for your feedback, unfortunately we need some debug log in order to find out why it's not working.

**Comment by thieren** [comment]
Reading through this thread I think all of the issues should be resolved with the latest release. Therefore closing this.
