### ISSUE TITLE
Add Support for T8530 Video Smart Lock [enhancement]: 

### ISSUE THREAD

**Issue by j-coates** [homebridge-eufy-security/plugin#164]
### Describe the solution you'd like

I know it's not available for general purchase, but I received the Video Smart Lock (T8530) from my Kickstarter backing and just wanted to put it on the list of things to support in the future.

This is the error, in case it's helpful.
[9/18/2022, 1:39:45 PM] [EufySecurity-2.1.0] WARN:  This accessory is not compatible with HomeBridge Eufy Security plugin: Front Door Type: 55

**Comment by thieren** [comment]
Hi @j-coates 

this has to be implemented in eufy-security-client first before we can add it here.

There is already an [request](https://github.com/bropat/eufy-security-client/issues/220) to add support for it. You can follow it in the linked issue.

**Comment by andrewfluck** [comment]
Looks like the work is just about done according to:
https://github.com/bropat/eufy-security-client/issues/220#issuecomment-1915520009

**Comment by robinzhx** [comment]
I believe the homebridge plugin only treats it as lock instead of the camera? I was not able to get the camera stream video from T8530

**Comment by kats1123** [comment]
Is there an update on this?
