### ISSUE TITLE
[Bug]: Naming for Motion and Power switches is missing

### ISSUE THREAD

**Issue by schliemann** [homebridge-eufy-security/plugin#168]
### What happened?

Most Eufycams have switches for "Power" and "Motion detection". Both are however named the name of the camera. In the below example it states "Living Room" twice.

![237B6BAC-4496-466D-9436-A98988B3286C](https://user-images.githubusercontent.com/10818044/191021005-8e3698cd-547a-403b-b94a-a03b87037f26.png)

### Device Type

Indoor Camera (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
Don't think this is needed. Will provide if necessary.
```

### config

```shell
Don't think this is needed. Will provide if necessary.
```

**Comment by thieren** [comment]
Hi @schliemann 

This is apple related and occurs with the new iOS 16. I haven't had a chance test if we can do anything about this, but at the moment the standard behaviour is changed due to the HomeKit changes introduced by apple.

**Comment by thieren** [comment]
Actually if you have an device that's still on the old version you can see the naming still working correctly. (Like on an iPad that has the new update not yet)
