### ISSUE TITLE
[Bug]: Wired Snapshot

### ISSUE THREAD

**Issue by birish21** [homebridge-eufy-security/plugin#17]
### What happened?

For some reason I am getting a cached screenshot on my Eufy wired doorbell.  Even when I go to live view and go back to the main page it reverts back to the cached image.

### Device Type

Doorbell (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

**Comment by lenoxys** [comment]
You will need to use Forcerefresh button under doorbell setting. This is only available on beta for now.

**Comment by thieren** [comment]
Closed because stale

`forecerefreshsnap` option is implemented in 2.0.0 master
