### ISSUE TITLE
[Bug]: No devices connected

### ISSUE THREAD

**Issue by carsonnichols** [homebridge-eufy-security/plugin#171]
### What happened?

I am stuck after the bridge starts to run. None of the shared devices are showing on my bridge. 

- I created a shared admin account.
- I verified 2FA is off. 
- I used that login for the bridge.
- The bridge appropriately boots but never loads any devices from eufy.

Using:
- Plugin 2.1.0
- Homebridge 1.5.0
- Node 16.17.0
- 

### Device Type

Station (Supported)

### Plugin Version

other (UnSupported)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X 11+ (Supported)

### Relevant log output

```shell
9/21/2022, 4:19:37 PMEufy Security BridgeConfiguration change
9/21/2022, 4:19:37 PMeufysecuritybridge stopping
9/21/2022, 4:19:42 PMEufy Security Bridge starting
9/21/2022, 4:19:49 PMEufy Security BridgeLoaded plugin 'homebridge-eufy-security'
9/21/2022, 4:19:49 PMEufy Security BridgeLoading 1 platforms...
9/21/2022, 4:19:49 PMEufy Security BridgeBridge is running on port 51846.
```

### config

```shell
{
    "platform": "EufySecurity",
    "username": "*******@outlook.com",
    "password": "*********",
    "enableDetailedLogging": 2
}
```

**Comment by thieren** [comment]
Hi @carsonnichols 

Can you share a complete log of the startup procedure? From the log output you posted I don't see anything logged from the plugin itself.

**Comment by carsonnichols** [comment]
9/21/2022, 4:19:37 PMEufy Security BridgeConfiguration change
9/21/2022, 4:19:37 PMEufy Security Bridge[9/21/2022, 4:19:37 PM] [EufySecurity-2.1.0] INFO:  [32mFinished shutdown![39m
9/21/2022, 4:19:49 PMEufy Security BridgeLoaded plugin 'homebridge-eufy-security'
9/21/2022, 4:19:49 PMEufy Security BridgeRegistering platform 'homebridge-eufy-security.EufySecurity'
9/21/2022, 4:19:49 PMEufy Security BridgeLoading 1 platforms...
9/21/2022, 4:19:49 PMEufy Security Bridge[9/21/2022, 4:19:49 PM] [EufySecurity-2.1.0] WARN:  [33mwarning: planned changes, see https://github.com/homebridge-eufy-security/plugin/issues/1[39m
9/21/2022, 4:19:49 PMEufy Security Bridge[9/21/2022, 4:19:49 PM] [EufySecurity-2.1.0] DEBUG: [36mplugin data store: /var/lib/hoobs/eufysecuritybridge/eufysecurity[39m
9/21/2022, 4:19:49 PMEufy Security Bridge[9/21/2022, 4:19:49 PM] [EufySecurity-2.1.0] DEBUG: [36mUsing bropats eufy-security-client library in version 2.1.2[39m
9/21/2022, 4:19:49 PMEufy Security Bridge[9/21/2022, 4:19:49 PM] [EufySecurity-2.1.0] INFO:  [32mCountry set: US[39m
9/21/2022, 4:19:49 PMEufy Security Bridge[9/21/2022, 4:19:49 PM] [EufySecurity-2.1.0] INFO:  [32mFinished initializing![39m
9/21/2022, 4:19:49 PMEufy Security BridgeBridge is running on port 51846.
9/21/2022, 4:19:51 PMEufy Security Bridge[9/21/2022, 4:19:51 PM] [EufySecurity-2.1.0] DEBUG: [36mEufyClient connected false[39m
9/21/2022, 4:19:51 PMEufy Security Bridge[9/21/2022, 4:19:51 PM] [EufySecurity-2.1.0] ERROR: [31mNot connected can't continue![39m

**Comment by thieren** [comment]
As stated in the log output the login failed through the plugin.

I would suggest you update to 2.2.0-beta and try again. The login will most likely fail again, but the reason should then be displayed. I guess there will be a captcha warning.

Let me know if this is the case with the beta log output.

**Comment by carsonnichols** [comment]
9/22/2022, 4:16:08 PMEufy Security BridgeConfiguration change
9/22/2022, 4:16:08 PMeufysecuritybridge stopping
9/22/2022, 4:16:09 PMEufy Security Bridge[9/22/2022, 4:16:09 PM] [EufySecurity-2.2.0-beta.5] INFO:  [32mFinished shutdown![39m
9/22/2022, 4:16:14 PMEufy Security Bridge starting
9/22/2022, 4:16:20 PMEufy Security BridgeLoaded plugin 'homebridge-eufy-security'
9/22/2022, 4:16:20 PMEufy Security BridgeRegistering platform 'homebridge-eufy-security.EufySecurity'
9/22/2022, 4:16:20 PMEufy Security BridgeLoading 1 platforms...
9/22/2022, 4:16:20 PMEufy Security Bridge[9/22/2022, 4:16:20 PM] [EufySecurity-2.2.0-beta.5] WARN:  [33mwarning: planned changes, see https://github.com/homebridge-eufy-security/plugin/issues/1[39m
9/22/2022, 4:16:20 PMEufy Security Bridge[9/22/2022, 4:16:20 PM] [EufySecurity-2.2.0-beta.5] DEBUG: [36mplugin data store: /var/lib/hoobs/eufysecuritybridge/eufysecurity[39m
9/22/2022, 4:16:20 PMEufy Security Bridge[9/22/2022, 4:16:20 PM] [EufySecurity-2.2.0-beta.5] DEBUG: [36mUsing bropats eufy-security-client library in version 2.2.0-rc.2[39m
9/22/2022, 4:16:20 PMEufy Security Bridge[9/22/2022, 4:16:20 PM] [EufySecurity-2.2.0-beta.5] INFO:  [32mCountry set: US[39m
9/22/2022, 4:16:20 PMEufy Security Bridge[9/22/2022, 4:16:20 PM] [EufySecurity-2.2.0-beta.5] INFO:  [32mFinished initializing![39m
9/22/2022, 4:16:20 PMEufy Security BridgeBridge is running on port 51846.
9/22/2022, 4:16:22 PMEufy Security Bridge[9/22/2022, 4:16:22 PM] [EufySecurity-2.2.0-beta.5] DEBUG: [36mEufyClient connected false[39m
9/22/2022, 4:16:22 PMEufy Security Bridge[9/22/2022, 4:16:22 PM] [EufySecurity-2.2.0-beta.5] ERROR: [31mNot connected can't continue![39m

**Comment by thieren** [comment]
Ok, there's no mention of a captcha or 2FA request. So I'd assume there is something wrong with the login.

Are your credentials correct? Please double check. And also important: is your country setting correct? You'll have to use the same you've used in the eufy app.
From your config I see that you have no country set, so it will default to 'US'.
This is also shown in the logs.

**Comment by carsonnichols** [comment]
Oh man!  I'm so sorry.  I went back through and had a typo in my email address!

**Comment by thieren** [comment]
No worries. Glad I could help.

Also many thanks for your donation. Very appreciate it! :-)
