### ISSUE TITLE
[Bug]: iPhone 14 Pro and plugin v2.2.0b5 causing phone to crash when set to Copy on wifi

### ISSUE THREAD

**Issue by DaveM8686** [homebridge-eufy-security/plugin#174]
### What happened?

I have been able to replicate this over and over and I have no idea what to do from here.

Since updating to an iPhone 14 Pro, when I try to view the doorbell while connected to the same wifi, my phone reboots (black screen, Apple logo, full reboot). This happens when I view through the standard Home app, the HomeCam app, or an event notification.  This does not happen on my wife's 13 Pro.

I have played around with the settings and found this ONLY happens when the plugin is set to Copy mode, however HKSV also only records when it's set to Copy, so I need it set on this.

When I turn wifi off, everything is fine.  The log output below is what I get when I try to view the doorbell and my phone reboots.

### Device Type

Doorbell (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Docker (UnSupported)

### Relevant log output

```shell
[9/27/2022, 4:32:01 PM] [EufySecurity-2.2.0-beta.5] INFO:  Doorbell Chime station livestream (P2P session) for Doorbell has started.
[9/27/2022, 4:32:01 PM] [EufySecurity-2.2.0-beta.5] INFO:  [Doorbell] [Video Process] Starting video stream: native
[9/27/2022, 4:32:01 PM] [EufySecurity-2.2.0-beta.5] INFO:  [Doorbell] [Audio Process] Starting audio stream: 16 kHz, 24 kbps, codec: libfdk_aac
[9/27/2022, 4:32:01 PM] [EufySecurity-2.2.0-beta.5] INFO:  [Doorbell] [Talkback Process] Starting audio stream: 16 kHz, 20 kbps, codec: libfdk_aac
[9/27/2022, 4:32:05 PM] [EufySecurity-2.2.0-beta.5] INFO:  Doorbell Stopped video stream.
[9/27/2022, 4:32:05 PM] [EufySecurity-2.2.0-beta.5] INFO:  Doorbell Chime station livestream for Doorbell has stopped.
[9/27/2022, 4:32:07 PM] [EufySecurity-2.2.0-beta.5] INFO:  [Doorbell] [Video Process] FFmpeg exited with code: null and signal: SIGKILL (Forced)
[9/27/2022, 4:32:07 PM] [EufySecurity-2.2.0-beta.5] INFO:  [Doorbell] [Audio Process] FFmpeg exited with code: null and signal: SIGKILL (Forced)
[9/27/2022, 4:32:07 PM] [EufySecurity-2.2.0-beta.5] INFO:  [Doorbell] [Talkback Process] FFmpeg exited with code: null and signal: SIGKILL (Forced)
```

### config

```shell
{
            "username": "xxx",
            "password": "xxx",
            "country": "AU",
            "ignoreStations": [
                "xxx"
            ],
            "cameras": [
                {
                    "serialNumber": "xxx",
                    "enableCamera": true,
                    "useCachedLocalLivestream": true,
                    "videoConfig": {
                        "audio": true,
                        "vcodec": "copy",
                        "useSeparateProcesses": true
                    },
                    "enableButton": false,
                    "motionButton": true,
                    "refreshSnapshotIntervalMinutes": 360,
                    "unbridge": true,
                    "rtsp": false,
                    "talkback": true,
                    "immediateRingNotificationWithoutSnapshot": false,
                    "snapshotHandlingMethod": 3,
                    "hsv": true
                }
            ],
            "platform": "EufySecurity",
            "_bridge": {
                "username": "xxx",
                "port": xxx
            },
            "ignoreDevices": [],
            "cleanCache": true,
            "enableDetailedLogging": false
        }
```

**Comment by thieren** [comment]
That's a weird one.

I can only assume that the new iPhones are not able to process the custom resolutions as well as previous models could.

Can someone else confirm this behaviour with the new models?

As for a solution: I don't think we can do so much here from the plugin side. The whole meaning of the `copy` setting is to pass the video stream through without altering it. So if the phone has problems with this stream configuration, then I don't think you can do anything apart from not using `copy`.

As for HKSV: I plan to add custom settings for HKSV, so that you can set the codec etc. for this indivdually. But if this will help in this case I don't know. Since the recording will eventually be the same stream your phone should (in theory) crash when you play these recordings.

But all that assumes that this is really caused by the stream configuration. What contradicts this is the wifi thing.

Could you by any chance set up another homebridge instance on another system (preferably another os as well) and see if the bug remains still?

**Comment by DaveM8686** [comment]
I kind of assumed the same thing about the new phones, like maybe they dropped a codec or something.

I actually plan to set up a new Homebridge instance later this week, since I got a new NAS and will be moving off Docker and onto the direct HB package.  I'll let you know if that works.

In the meantime, I seem to have found a workaround.  I set it to Copy, but then unticked the box that changes the codec to Copy (so basically just left the "use different streams for video/audio" and whatever else comes with Copy).  That is letting it record in HKSV, and also letting me view it.

**Comment by DaveM8686** [comment]
HI @thieren, I can confirm this still happens with a new instance of Homebridge running on a different NAS with the direct HB package instead of going through Docker.

**Comment by DaveM8686** [comment]
Hi @thieren, this seems to have been resolved with one of the recent iOS updates. Not sure which one, sorry, as I have only checked it again since being on 16.1.2.

**Comment by thieren** [comment]
@DaveM8686 thx for the feedback. Good to know that Apple also fixes some bugs. :-D
