### ISSUE TITLE
[Bug]: Hoobs: unable to stream with doorbell

### ISSUE THREAD

**Issue by Midifreakz** [homebridge-eufy-security/plugin#176]
### What happened?

Got the doorbell in Homekit, but can't livestream.

### Device Type

Doorbell (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v12 (Supported)

### Operating System

Mac OS X 11+ (Supported)

### Relevant log output

```shell
[Eufy Security Bridge 2881@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Doorbell' didn't respond at all!. Please check that you properly call the callback!
```

### config

```shell
"platform": "EufySecurity",
    "username": "xxxxxx",
    "password": "xxxxx,
    "pollingIntervalMinutes": 30,
    "hkHome": 1,
    "hkAway": 0,
    "hkNight": 3,
    "hkOff": 63,
    "enableDetailedLogging": 0,
    "country": "BE",
    "CameraMaxLivestreamDuration": 30,
    "enableCamera": true
}
```

**Comment by thieren** [comment]
Hi @Midifreakz 

Can you please check that you followed the tips on the [wiki page](https://github.com/homebridge-eufy-security/plugin/wiki/Streaming-Settings)?

If this does not help please enable debug messages and send me the logs.

**Comment by Midifreakz** [comment]
Hi, 

Thanks for the quick response! 

I have the plugin running on Hoobs and can not access the UI (as described in another issue here). 
However, if I'm understanding it correctly I would be able to set the setting parameters for the video compression in the config.js file?

**Comment by thieren** [comment]
Hi @Midifreakz 

in theory all the settings can be set in the config json, right. The only thing that's not possible is to enter captchas or 2fa for the eufy login. But if you already got the device to show up, that should be of no concern.

However to see why the camera is not streaming properly I'd need to have a look at the logs.
Please set `"enableDetailedLogging":  true,`
After that the plugin will write all relevant date into the plugin storage path on the hoobs device. I don't have such device myself, but from what I understand it should be possible to login on this with a terminal (via ssh?) and get those logs.
