### ISSUE TITLE
[Bug]: HomeKit System Alarm Stuck in "triggered" State

### ISSUE THREAD

**Issue by dcgraves** [homebridge-eufy-security/plugin#18]
### What happened?

When the base station alarm is triggered by a motion sensor on a camera, the HomeKit security alarm is also set to the "triggered" state, as expected.

However, once the system is reset to the "Off" mode, the base station alarm is turned off appropriately, but the HomeKit alarm state is not cleared. This causes repeated HomeKit alerts whenever the system is placed back into "Home", "Away", or "Night" mode. The only way to stop this from continuing is to reboot Homebridge entirely.

From quickly scanning `src/accessories/StationAccessory.ts`, I suspect that the `this.alarm_triggered` flag is never reset to `false` after being set to `true` whenever the system is switched back to "Off" from a triggered/armed state. That, or potentially a caching issue of some kind?

### Device Type

Station (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

**Comment by lenoxys** [comment]
hello, thanks for helping, this already a duplicate of #9
