### ISSUE TITLE
[Bug]: Eufy T8200 Doorbell no audio and microphone

### ISSUE THREAD

**Issue by unstressable** [homebridge-eufy-security/plugin#186]
### What happened?

The integration of the T8200 Eufy Video Doorbell does not bring any audio with it.

Its not possible to hear, or speak throught the apple home app.

### Device Type

Doorbell (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
not necessary
```

### config

```shell
{
      "platform": "EufySecurity",
      "username": "<Mail>",
      "password": "<Password>",
      "pollingIntervalMinutes": 30,
      "hkHome": 1,
      "hkAway": 0,
      "hkNight": 3,
      "hkOff": 63,
      "enableDetailedLogging": 0,
      "ignoreStations": [
        "<S/N>"
      ],
      "ignoreDevices": [
        "<S/N>"
      ],
      "country": "DE",
      "CameraMaxLivestreamDuration": 120
    }
```

**Comment by thieren** [comment]
Hi @unstressable 

your config json seems wrong.

You'll have to set the talkback and audio settings on the specific camera to `true`.

You can check https://github.com/homebridge-eufy-security/plugin/issues/225 for an example configuration. Or better still use the config ui of homebridge to set the cameras up.
