### ISSUE TITLE
[enhancement]: Add Eufycam 3 support now that client is updated! Bropat has released new client

### ISSUE THREAD

**Issue by mahst68** [homebridge-eufy-security/plugin#195]
### Describe the solution you'd like

please update with new security client!!!! thanks!

**Comment by mutchu** [comment]
Hello @mahst68,
A little politeness towards the people working on this project and a little patience too. They certainly don't have that to do with their day.
Cordially

**Comment by mahst68** [comment]
To be frank on a previous enhancement ask, it was commented to follow the Bropat client GitHub. This ask was to clarify that indeed the client is now update. Warmly… and I understand that no one has to do anything they don’t want

**Comment by nwrightau** [comment]
Hello, Eufy Cam 3 support would be much appreciated. Happy to assist if I can. 

Thanks

**Comment by schliemann** [comment]
I will update the beta soon. Tomorrow evening perhaps.

**Comment by mahst68** [comment]
> I will update the beta soon. Tomorrow evening perhaps.

Very grateful. Is there a donation link for the teams work?

**Comment by mutchu** [comment]
@schliemann Thanks for your work !

**Comment by mutchu** [comment]
@schliemann thanks you very much, my homebase 3 run on HomeKit with the beta, On the other hand, triggering the floodlight pro alarm does not work in HomeKit.

**Comment by mahst68** [comment]
homebase 3 is working fine however the actual camera installed on it still show as a unsupported device when the plugin loads.

11/14/2022, 2:48:04 PM] [EufySecurity-2.2.0-beta.7] WARN:  This accessory is not compatible with HomeBridge Eufy Security plugin: Front Door Type: 19

not sure if anyone else is experiencing the same thing. Any help is, as always, greatly appreciated

**Comment by schliemann** [comment]
> homebase 3 is working fine however the actual camera installed on it still show as a unsupported device when the plugin loads.
> 
> 11/14/2022, 2:48:04 PM] [EufySecurity-2.2.0-beta.7] WARN: This accessory is not compatible with HomeBridge Eufy Security plugin: Front Door Type: 19
> 
> not sure if anyone else is experiencing the same thing. Any help is, as always, greatly appreciated

Please create a new issue with more info.

**Comment by schliemann** [comment]
Both beta and non-beta is updated. Closing this.
