### ISSUE TITLE
[enhancement]: Play alarm audio on all cameras when automation triggered

### ISSUE THREAD

**Issue by bnowacky** [homebridge-eufy-security/plugin#198]
### Describe the solution you'd like

I think everyone would agree the base-station alarm is pretty sad and quiet... But what would be better is broadcasting the alarm audio on all cameras in addition to the base stations. Would love to see a way to trigger the alarm audio on the cameras when the automation for the alarm is triggered. You can have the camera's play the alarm audio on motion, but that may be too sensitive. .. For instance, I have a panic button, when I push that panic button, I want all the Eufy devices to play the alarm audio on them.

**Comment by schliemann** [comment]
Interesting idea. But I'm not sure you can turn on the alarm on a camera from the Eufy Security Client.
