### ISSUE TITLE
[Bug]: Floodlight Camera (T8420X) Camera Disabled In Homekit

### ISSUE THREAD

**Issue by walloutlet** [homebridge-eufy-security/plugin#199]
### What happened?

Basic setup of Eufy Security Plugin on Homebridge.  T8420X Floodlight Camera reports camera is off in Homekit and there is no way to enable it.  Firmware is version 2.0.6 on this Eufy device.  Other cameras on doorbell devices snapshot and stream fine.  From the Eufy app the Floodlight Camera works fine, video streaming and settings.

I've tried bridged and unbridged modes for the devices, neither with success.  Updated to EufySecurity-2.2.0-beta.5 version to see if there was a bug fix for this device.  That did not work either.  Tried various different settings with no luck.  Hoping the team here has some input for this specific Eufy Floodlight Camera device.

Homebridge version: 1.5.1
Node.js version: 18.12.1
Raspbian version: 11

### Device Type

Floodlight (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

other (UnSupported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
DEBUG: Driveway Will not SET HomeKitCameraActive: 0
```

### config

```shell
{
    "username": "guest admin account",
    "password": "the necessary password",
    "country": "US",
    "stations": [
        {
            "serialNumber": "T8420T60xxxxxxFC",
            "manualTriggerModes": []
        },
        {
            "serialNumber": "T8203P11xxxxxxF5",
            "manualTriggerModes": []
        },
        {
            "serialNumber": "T8200N00xxxxxx1E",
            "manualTriggerModes": []
        },
        {
            "serialNumber": "T8520Q20xxxxxx7E",
            "manualTriggerModes": []
        }
    ],
    "cameras": [
        {
            "serialNumber": "T8420T60xxxxxxFC",
            "rtsp": false,
            "enableCamera": "true",
            "enableButton": false,
            "motionButton": false,
            "refreshSnapshotIntervalMinutes": 15,
            "unbridge": true,
            "snapshotHandlingMethod": 2,
            "hsv": false,
            "videoConfig": {}
        },
        {
            "serialNumber": "T8203P11xxxxxxF5",
            "rtsp": false,
            "enableCamera": true,
            "enableButton": false,
            "motionButton": false,
            "unbridge": true,
            "refreshSnapshotIntervalMinutes": 15,
            "snapshotHandlingMethod": 2
        },
        {
            "serialNumber": "T8200N00xxxxxx1E",
            "rtsp": false,
            "enableCamera": true,
            "enableButton": false,
            "motionButton": false,
            "unbridge": true,
            "refreshSnapshotIntervalMinutes": 15,
            "snapshotHandlingMethod": 2
        },
        {
            "serialNumber": "T8520Q20xxxxxx7E",
            "rtsp": false,
            "talkback": false
        }
    ],
    "platform": "EufySecurity",
    "hkHome": 1,
    "hkAway": 0,
    "hkNight": 1,
    "hkOff": 63,
    "ignoreStations": [],
    "ignoreDevices": [],
    "cleanCache": true,
    "preferLocalConnection": true,
    "enableDetailedLogging": true
}
```

**Comment by walloutlet** [comment]
As far as I can tell it is not Homekit ready, yet.  What prompted the question was that the model showed as supported in the '[Supported Devices through eufy-security-client](https://bropat.github.io/eufy-security-client/#/supported_devices)' so I thought there maybe a bug or issue relating to the camera stream.

**Comment by schliemann** [comment]
Can you provide additional logs?

**Comment by stwrz** [comment]
Just hopping in to say that this has been my experience as well. 

Cloud thumbnails seem to be working, but livestream is a no go.

**Comment by thieren** [comment]
@stwrz can you provide the needed log files?

**Comment by AndrewKite** [comment]
@walloutlet Guide to retrieving the logs can be found here - https://github.com/homebridge-eufy-security/plugin/wiki/Basic-Troubleshooting#enable-logging

**Comment by walloutlet** [comment]
Haven't got to collecting the logs yet, Thanksgiving.  However, I did upgrade my Apple TV IOS (incremental 16.x version) and got these notifications from HomeKit.  So it appears the camera works but HomeKit does something when it's running to turn off the camera.

![HomeKitDrivewayMsgs](https://user-images.githubusercontent.com/117780452/204168219-07d776ad-5493-42b0-ace7-1829a00c6b35.jpg)

**Comment by thieren** [comment]
You could either join the discord channel and sent the logs via dm, or upload them to a cloud service (dropbox, google, iCloud, ...) and share the link here.

As for the initial 'error' message `DEBUG: Driveway Will not SET HomeKitCameraActive: 0`: That's not really a relevant output. The plugin has no ability to set that specific HomeKit characteristic, since it always returns its value as `On`.
So HomeKit should always 'see' the device as enabled.
I assume you get a 'No Response' in the Home App? This can have many causes and the full logs can help here...

**Comment by walloutlet** [comment]
Thanks @thieren... I've DM'd them over to you in Discord.  To answer your question, I get notifications that there is motion.  I can turn the light on and off.   Modify the Security setting from Away to Home to Off all from HomeKit.  The camera just shows up as "Off"  (See screen shot below)

![IMG_6804](https://user-images.githubusercontent.com/117780452/204360922-754224ac-5901-4eaf-967c-1c5e761dce79.jpg)

**Comment by thieren** [comment]
The issue could be resolved by enabling the enable switch (a.k.a `"enableButton": true`) and then switching this button in the home app.
