### ISSUE TITLE
[Bug]: Eufy devices not reacting in HomeKit

### ISSUE THREAD

**Issue by MartinJRS** [homebridge-eufy-security/plugin#204]
### What happened?

Eufy devices are not reacting anymore in HomeKit since a couple of days.

This line is in the protocol:
[11/11/2022, 8:15:46 AM] [EufySecurity-2.1.0] ERROR: Not connected can't continue!

I have not changed anything.

Is there anything I can do?

### Device Type

Station (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[11/11/2022, 8:15:46 AM] [EufySecurity-2.1.0] ERROR: Not connected can't continue!
```

### config

```shell
{
            "platform": "EufySecurity",
            "username": "****@****.****",
            "password": "**************",
            "country": "DE",
            "ignoreStations": [],
            "ignoreDevices": [
                "T8113N****",
                "T8113N****",
                "T8113N****",
                "T8960P****",
                "T8113N****"
            ],
            "pollingIntervalMinutes": 5,
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "enableDetailedLogging": false,
            "CameraMaxLivestreamDuration": 30,
            "cleanCache": true,
            "cameras": [
                {
                    "serialNumber": "T8112H****",
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": true,
                    "rtsp": true,
                    "unbridge": false,
                    "forcerefreshsnap": false,
                    "useCachedLocalLivestream": true,
                    "videoConfig": {
                        "audio": true
                    }
                },
                {
                    "serialNumber": "T8112H****",
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": true,
                    "rtsp": true,
                    "unbridge": false,
                    "forcerefreshsnap": true,
                    "useCachedLocalLivestream": true,
                    "videoConfig": {
                        "audio": true
                    }
                },
                {
                    "serialNumber": "T8112H****",
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": true,
                    "rtsp": true,
                    "unbridge": false,
                    "forcerefreshsnap": true,
                    "useCachedLocalLivestream": true,
                    "videoConfig": {
                        "audio": true
                    }
                }
            ]
        },
```

**Comment by MartinJRS** [comment]
Yes

**Comment by Mech4711** [comment]
same as #201

**Comment by MartinJRS** [comment]
Thanks. So, from what I understand, there is no solution yet? We have to wait?

**Comment by Mech4711** [comment]
there is a Pull request waiting for approval by a maintainer... looks like this would resolve our problem

**Comment by schliemann** [comment]
Should be solved if you are using beta.

**Comment by MartinJRS** [comment]
Thanks a lot. Yeah, it seems to work again, but there are some strange error messages as well ... is there anything I am missing to get done? Or shall we simply ignore this for the time being?

[13/11/2022, 09:58:44] [homebridge-eufy-security] This plugin threw an error from the characteristic 'Camera Operating Mode Indicator': Unhandled error thrown inside write handler for characteristic: station.setStatusLed is not a function. See https://homebridge.io/w/JtMGR for more info.
[13/11/2022, 09:58:44] [homebridge-eufy-security] This plugin threw an error from the characteristic 'Camera Operating Mode Indicator': Unhandled error thrown inside write handler for characteristic: station.setStatusLed is not a function. See https://homebridge.io/w/JtMGR for more info.
[13/11/2022, 09:58:44] [homebridge-eufy-security] This plugin threw an error from the characteristic 'Camera Operating Mode Indicator': Unhandled error thrown inside write handler for characteristic: station.setStatusLed is not a function. See https://homebridge.io/w/JtMGR for more info.

Thanks and have a great Sunday
