### ISSUE TITLE
WOW: 2.0.0 - Beta 4 works for me

### ISSUE THREAD

**Issue by TOTO-DK** [homebridge-eufy-security/plugin#21]
### What happened?

The new Beta 4 solved all problems, and my plugin is now fully functioning, and I'm able to stream now within Homekit app.

VERY well done ;-)

### Device Type

Doorbell (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Other (UnSupported)

**Comment by thieren** [comment]
Hey @TOTO-DK 

Thanks for the feedback. If you'd like you can keep on trying the betas and give feedback.

**Comment by TOTO-DK** [comment]
Hi thieren

I am gladly doing so - now on 2.0.1 beta 10, and it keeps getting better and better.

VERY well done 👍

/TOTO





Venlig hilsen
Tom Toft
________________________________
Fra: thieren ***@***.***>
Sendt: Tuesday, June 7, 2022 8:32:13 AM
Til: homebridge-eufy-security/plugin ***@***.***>
Cc: TOTO-DK ***@***.***>; Mention ***@***.***>
Emne: Re: [homebridge-eufy-security/plugin] WOW: 2.0.0 - Beta 4 works for me (Issue #21)


Hey @TOTO-DK<https://github.com/TOTO-DK>

Thanks for the feedback. If you'd like you can keep on trying the betas and give feedback.
