### ISSUE TITLE
[enhancement]: Motion sensor activity in HK when notification is disabled on Eufy App

### ISSUE THREAD

**Issue by pawel-tr** [homebridge-eufy-security/plugin#216]
### Describe the solution you'd like

Currently it appears that when motion sensor notification is disabled within the app, triggered sensor will not update status in HomeKit. Only when sensor notification is enabled HomeKit will show that motion is detected. 

I would love to use the motion sensor as a device to turn off certain elements in HomeKit but not inform me every single time motion is detected in the room from the Eufy App

**Comment by schliemann** [comment]
Since the app works on push notifications this is not possible to change.
