### ISSUE TITLE
[Bug]: No Response Eufy Doorbell in v2.0.0 Beta 5

### ISSUE THREAD

**Issue by mas0nwest** [homebridge-eufy-security/plugin#24]
### What happened?

No Response Eufy Doorbell in v2.0.0 Beta 5 in Homebridge /no camera feed/livestream
Everything else is working perfectly

### Device Type

Doorbell (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X 11+ (Supported)

### Relevant log output

Doorbell FFmpeg exited with code: 1 and signal: null (Error)

**Comment by thieren** [comment]
Hi @mas0nwest 

Could you test again with the newest beta and add a log output with debug logging enabled?

**Comment by mas0nwest** [comment]
Fixed in 2.0.0 stable release
