### ISSUE TITLE
Could be possible a new Alarm Trigger Mode?

### ISSUE THREAD

**Issue by JManuMartinez** [homebridge-eufy-security/plugin#249]
### Describe the solution you'd like

Hello,
¿Could be possible to add another Manual Alarm Trigger Mode that Eufy security shows and includes? It is named Geofencing, when you left home or arrive home with location activated in eufy app, it can switch automatically from home to away or away to home without putting it manually from app or HomeKit plug-in.
It should be nice to get this option from your plug-in, because when yo put the trigger to away or home in Homekit, you could set it again for geofencing and it remains in automatic mode for the future alarm triggers.

https://support.eufy.com/s/article/How-to-Activate-Geofencing-Mode-on-eufySecurity-App

Thanks before hand and best wishes.
Jose Manuel.

**Comment by thieren** [comment]
Hi @JManuMartinez 

please excuse me but I don't understand your request. Much like you I am not a native English speaker and somewhere in the translation the point you're trying to make is lost to me. Can you try to elaborate or maybe use google translate or something.

No offense. :-)

**Comment by JManuMartinez** [comment]
Hello Thieren,Thanks for your response, of course I try to explain better.In eufy app security config, I have a trigger that is “geofencing”, based in the gps location of my iphone, a trigger that when I’m at home, it puts trigger config directly at home because I’m in the gps location near home, when I leave home, it change the trigger to away from home, without any manual trigger change for me. This change (at home/away) is automatic.With your plug-in into HomeKit, I can only select predefined triggers for each device, and it doesn’t include “geofencing” trigger, so, I must change for at home or away from home manually, if I could select the trigger “geofencing”, between your available triggers in your plug-in for eufy I didn’t need to change its states manually.I attach images for this triggers in Eufy’s app, and the triggers availables in your plug-in.It should be nice if you could define a new one named “geofencing” too, as the eufy’s app include.In Spanish, “en Casa” means “at home”, fuera de casa means “away from home”, “noche” means “night”, and “Geovallado” means “geofencing”, based in my iphone’s gps location.Images:In eufy app:your plug-in doesn’t include the trigger “geofencing”, and it should be nice:Thanks for all and best wishes.José Manuel Martínez El 17 dic 2022, a las 21:06, thieren ***@***.***> escribió:﻿
Hi @JManuMartinez
please excuse me but I don't understand your request. Much like you I am not a native English speaker and somewhere in the translation the point you're trying to make is lost to me. Can you try to elaborate or maybe use google translate or something.
No offense. :-)

**Comment by thieren** [comment]
Unfortunately there are no images added to your post. But maybe I can help nevertheless.
In the Plugin Settings you can set the mapping of the eufy modes to the HomeKit modes. So you could for example set HK Night to Eufy Geofencing. Is this what you want?

![Bildschirm­foto 2022-12-19 um 18 44 41](https://user-images.githubusercontent.com/22128659/208487581-84dd0901-592b-4b92-ad79-472c336299a2.png)

**Comment by JManuMartinez** [comment]
Hello @thieren, is more than enough! 
I forget to review that possible configuration that you had previously included as an option.
Thanks a lot!

**Comment by thieren** [comment]
Glad I could help!
