### ISSUE TITLE
Unable to uninstall plugin

### ISSUE THREAD

**Issue by timmy8784** [homebridge-eufy-security/plugin#257]
### What happened?

having the same login issues as everyone else, however I am unable to uninstall version 2.1.3 or install any beta version. I have copied the errors I am receiving below

### Device Type

Station (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

other (UnSupported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
pi@homebridge:/var/lib/homebridge $ pm install --save homebridge-eufy-securi ty@2.2.0-beta.16
pm ERR! code ENOTEMPTY npm ERR!
syscall rename
nom
ERR! path /var/lib/homebridge/node modules /homebridge-eufy-security pm ERR! dest /var/lib/homebridge/node modules/.homebridge-eufy-security-bkoC
ZZOI
nom ERR! errno -39
pm ERR! ENOTEMPTY: directory not empty, rename '/var/lib/homebridge/node mod ules/homebridge-eufy-security
'Ivar/lib/homebride/node modules /. homebrid
ge-eufy-security-bkoCzz0I
pm ERR! A complete log of this run can be found in:
npm ERR!
/ home/pi/.npm/_1ogs/2022-12-23707_31_59_9587-debug-0.1og
```

### config

```shell
Config does not have any info about this plugin as I am not logged in
```

**Comment by timmy8784** [comment]
> 
> 
> Did you check this [Common Issues](https://github.com/homebridge-eufy-security/plugin/wiki/Common-Issues) pages ?
> 
> 
> 

Yes I went through all of those and could not find any solution that worked

**Comment by thieren** [comment]
@timmy8784 do you know how to ssh into the rPI?

if so can you please try to run `sudo npm install -g homebridge-eufy-security@beta` and report back?

**Comment by timmy8784** [comment]
> @timmy8784 do you know how to ssh into the rPI?
> 
> 
> 
> if so can you please try to run `sudo npm install -g homebridge-eufy-security@beta` and report back?

I don't know how to ssh but I can try to figure it out. Can I use the homebridge ui terminal to enter this command?

**Comment by thieren** [comment]
it depends on the exact installation method you used to set homebridge up.

you can try but there's no guarantee that it'll work.

**Comment by timmy8784** [comment]
> it depends on the exact installation method you used to set homebridge up.
> 
> 
> 
> you can try but there's no guarantee that it'll work.

It just says sudo: npm: command not found

Guess I'll have to figure out how to ssh into it

**Comment by timmy8784** [comment]
> it depends on the exact installation method you used to set homebridge up.
> 
> 
> 
> you can try but there's no guarantee that it'll work.

I might be in over my head. I hooked my pi up to a monitor and this is the only place I can get to. Tried typing in your command but looks like it did nothing 

![image](https://user-images.githubusercontent.com/59715478/209405903-8065172a-c50f-4b30-bdb4-f53a2591c801.jpeg)

**Comment by timmy8784** [comment]
@thieren 

So I used ssh from my Mac to the pi and the command line was at pi@homebridge and I tried your command. It still came back as "sudo: npm: command not found"

:(

**Comment by timmy8784** [comment]
![image](https://user-images.githubusercontent.com/59715478/209407083-804efcc1-810b-4369-86cc-7659f2f2695d.jpeg)

**Comment by thieren** [comment]
At least we now know that you can use the sudo command.

Can you share the output of this command: `ls -al /var/lib/homebridge/node_modules/` ?

**Comment by timmy8784** [comment]
> At least we now know that you can use the sudo command.
> 
> Can you share the output of this command: `ls -al /var/lib/homebridge/node_modules/` ?

@thieren 

Really really appreciate this help btw!

![image](https://user-images.githubusercontent.com/59715478/209448786-9a7fe9fd-3e1b-4cc4-a0ac-e0f1284058e9.jpeg)

**Comment by thieren** [comment]
Ok, now try `rm -rf /var/lib/homebridge/node_modules/.homebridge-eufy-security-bkoCzz0I`

If this won't work put a `sudo` in front: `sudo rm -rf /var/....`

That directory is wrong there and seems to cause the error message. After removing it you should be able to install the beta.

**Comment by timmy8784** [comment]
@thieren 

I got it to erase that, now it's giving me the same error but mentioning a different directory? Something about the Deebot package?

Do I need to erase something else?

![image](https://user-images.githubusercontent.com/59715478/209449324-6868c2e9-0111-4f6c-ae93-b8fb540d00d3.png)

**Comment by thieren** [comment]
Ok. Sorry but it seems there is something terribly wrong with your setup. I don't see what this directory would have to do with this plugin and I won't recommend to delete it.

I'd assume that there is something wrong with the permissions but can't really say from afar. And so I can't really give any advice here.

The best in my opinion would be to setup the system totally new.

**Comment by thieren** [comment]
The error message itself is referencing the `.reconnect-core-2...` directory which itself seems to be wrong according to the naming (it should not be prefixed with a . and the suffix seems to be of a temporary kind.
So you could try to erase this also, but I'd assume this will only lead to other faulty directories popping up.

Either delete all the obscure directories that come up in these error messages (seems as if npm has created these sometime and is now struggling to delete them itself) or reset the whole setup. That'd be my two advices.

**Comment by timmy8784** [comment]
@thieren 

I actually did an update to that plug in it was referencing and that must overridden what was needed cause now it let me upgrade to beta 17!

Now I just have the same login issue as everyone else lol. So I will continue to monitor the other issue. 

Once again thank you so much for your help! Really appreciate it!

**Comment by thieren** [comment]
Ok, glad to hear this is resolved. I'll close this then.

Keep tracking the progress of the other issue for the login bug.
