### ISSUE TITLE
[enhancement]: Is it possible to expose the Homebase alarm in HomeKit?

### ISSUE THREAD

**Issue by billbazza** [homebridge-eufy-security/plugin#26]
### Describe the solution you'd like

Would this be possible as it would be useful with the home and away settings and the camera motion sensors combined with other HomeKit devices such as window and door sensors.

**Comment by lenoxys** [comment]
Hello this is already the case station is exposed. I've one in my setup.

**Comment by billbazza** [comment]
The hub is exposed with the home and away switches but I can see no alarm
![2E3A8BEB-9D0B-4DF8-A367-4C2601C4BD52](https://user-images.githubusercontent.com/34342370/168485625-68effda9-9665-4bcd-ab54-9fca30a57e23.png)

**Comment by lenoxys** [comment]
When enabling [debug mode](https://github.com/homebridge-eufy-security/plugin/wiki/Basic-Troubleshooting#debug-mode) do you see some issue appear?

**Comment by billbazza** [comment]
> When enabling [debug mode](https://github.com/homebridge-eufy-security/plugin/wiki/Basic-Troubleshooting#debug-mode) do you see some issue appear?

No, the homebase appears with the home, away & night setting just fine. What I was asking for it if the inbuilt siren could be exposed as an additional option so that we could use it in HomeKit automations to create a security system.

**Comment by lenoxys** [comment]
haaa got it now. Dunno if we can trigger that but bear with us I've few time to spend on the plugin as of now.

**Comment by billbazza** [comment]
> haaa got it now. Dunno if we can trigger that but bear with us I've few time to spend on the plugin as of now.

Great stuff, this would be amazing.

**Comment by thieren** [comment]
Hi @billbazza 

Just checked this. Yeah, the eufy-security-client does expose a method to trigger the alarm. But for an implementation some details would have to be clarified:

- how exactly should the alarm get triggered. The way I see it, there are two options (I prefer option 1):

1. Integrate via On/Off Switch, so On -> the alarm is triggered: Off -> the alarm is turned off
    Little Drawback: Users could hit the button by accident and would be somewhat confused by the result
2. Add a configuration option, that the alarm is automatically triggered when specific events are triggered (e.g. motion is detected, so alarm is triggered)
    Drawbacks: Much less control over the automation

- the plugin has to know for how long the alarm should be triggered. Seems to me, that the alarm cannot run indefinitely. Unfortunately Homekit doesn't have a Characteristic with which you could set a time duration (at least to my knowledge). I think this would be best achieved by a plugin setting in the configuration. Other ideas?

@lenoxys I believe I would have some time in the coming weeks to get this feature running if you don't mind.

**Comment by billbazza** [comment]
In the eufy app, you can trigger the alarm in an automation that you can configure from homebase i.e. motion detected while away, sound alert and notify. In the home app, you would need an alarm off switch off another way to deactivate the alarm i.e. a Hidden button press or along down press on a hue switch et cetera. You could even use one of those automations to say if door is unlocked (smart door lock) the alarm will turn off. It would need some careful consideration though.

**Comment by thieren** [comment]
Hey @billbazza 

Is it possible that you write me up on discord?

It should be no problem to include a button to turn the alarm off.
Theoretically also turning on will be no problem. But I lack some information as to how this could be useful (because I see no way to integrate this into any automations).

**Comment by sroettgermann** [comment]
I'm interested in this as well. Would be great to have an option to trigger the alarm siren of the homebase via an automation. E.g. some motion gets detected during "away" mode and this leads to an alarm sound.

**Comment by thieren** [comment]
> I'm interested in this as well. Would be great to have an option to trigger the alarm siren of the homebase via an automation. E.g. some motion gets detected during "away" mode and this leads to an alarm sound.

Still working on this.

> during "away" mode

That's exactly the problem. In HomeKit automations you cannot check for different modes. So the plugin will have to handle this via an optional setting I think.
But then you'll have a switch which behaviour is not at all obvious to the user since it sometimes does something, and other times not...
It's a bit tricky to implement this with ideal UX.

**Comment by sroettgermann** [comment]
Ah okay. I got it. Thanks anyway for your quick answer. Looking forward to the results.

**Comment by thieren** [comment]
This is implemented in the latest beta. Please give some feedback if you test this. Thx!

**Comment by sroettgermann** [comment]
The beta is not working with my HB setup. :( 

`[12/07/2022, 09:42:46] TypeError: device.getStationSerial is not a function
    at /usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/eufysecurity.ts:517:56
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/eufysecurity.ts:516:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[12/07/2022, 09:42:46] Got SIGTERM, shutting down Homebridge...
[7/12/2022, 9:42:46 AM] [EufySecurity-2.1.0-beta.7] INFO:  Finished shutdown!
(node:31067) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
(Use `node --trace-warnings ...` to show where the warning was created)`

**Comment by thieren** [comment]
Hi @sroettgermann 

sorry to hear that. bropat changed a few things on the way devices are added and maybe this is related to an issue that will be resolved in his 2.1.1, but to know for sure I'd like to have a look at your logs, if that's possible.

Please [enable debug messages](https://github.com/homebridge-eufy-security/plugin/wiki/Basic-Troubleshooting#debug-mode) and send me the log at `/var/local/lib/homebridge/eufysecurity/log-lib.log`

**Comment by sroettgermann** [comment]
@thieren thank you. I'll have a look at it. 

It seems an additional IndoorCam is causing this issue. :-( 
I'll send you the log asap.

**Comment by sroettgermann** [comment]
@thieren, is it possible to send it to you in a DM somehow?

**Comment by thieren** [comment]
> @thieren, is it possible to send it to you in a DM somehow?

You could send it to me via discord. You'll find the discord link on the main page of this repo.

**Comment by thieren** [comment]
Alternatively I'll send you a mail.

**Comment by thieren** [comment]
Is implemented with release of 2.1.0
