### ISSUE TITLE
after 2.1.4 Homebridge doesn't start

### ISSUE THREAD

**Issue by Hanimaniac** [homebridge-eufy-security/plugin#261]
### What happened?

Hey Community,
after Update, my homebridge get stuck in a start loop with this message:

Dec 25 12:15:29 raspberrypi systemd[1]: homebridge.service: Main process exited, code=killed, status=11/SEGV
Dec 25 12:15:29 raspberrypi systemd[1]: homebridge.service: Failed with result 'signal'.
Dec 25 12:15:30 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.

After downgrade to 2.1.3 my Homebridge works fine.
Only the Eufy Plugin with 2.1.3 dont work. 

Thanks and merry christmas
Martin

### Device Type

Doorbell (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v12 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
Dec 25 12:15:29 raspberrypi systemd[1]: homebridge.service: Main process exited, code=killed, status=11/SEGV
Dec 25 12:15:29 raspberrypi systemd[1]: homebridge.service: Failed with result 'signal'.
Dec 25 12:15:30 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
```

### config

```shell
{
            "username": "XXXXXXXX",
            "password": "XXXXXXX",
            "country": "DE",
            "deviceName": "",
            "platform": "EufySecurity",
            "ignoreStations": [],
            "ignoreDevices": [],
            "cleanCache": true,
            "cameras": [
                {
                    "serialNumber": "XXXXXXXXX",
                    "rtsp": false,
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": false,
                    "videoConfig": {
                        "audio": true,
                        "debug": true
                    },
                    "snapshotHandlingMethod": 1
                },
                {
                    "serialNumber": "XXXXXXXXXX",
                    "enableButton": false,
                    "motionButton": false
                }
            ]
        }
```

**Comment by mariomaz87** [comment]
Also in my case after the update, HomeBridge is broken with the error: Websocket failed to connect, is the server running?
After restoring a backup, it works again but Eufy Plugin can't connect: [12/25/2022, 7:58:00 PM] [EufySecurity-2.1.3] ERROR: Not connected can't continue!

**Comment by AndrewAdventure** [comment]
Hi. Having same issue. 


![image](https://user-images.githubusercontent.com/101590972/209676611-1c6cc006-15bc-45cf-a2ad-7274bcc08870.jpeg)

**Comment by thieren** [comment]
About the 'Not connected can't continue!' error please see #250 

It might help if you set up a new guest account and share your devices with the new account.
Also it might help to deactivate 2FA temporarily.
And lastly it might be a captcha request that the plugin cannot resolve on its own. Unfortunately the `2.1.4` still won't show the captcha warning. This will only show up in the beta for now. --> If it is the captcha it might help to wait some 12 hours or so and try again (most likely the account is flagged by eufy and that's automatically resolved after a while).
