### ISSUE TITLE
[enhancement]: Person-detection switch presented to HomeKit

### ISSUE THREAD

**Issue by juliantali** [homebridge-eufy-security/plugin#276]
### Describe the solution you'd like

Hi team,

It would be great if a switch could be presented to HomeKit for activation of person detection by a Eufy camera. 

This would enable us to create automation triggers based on human detection rather than simple motion detection. Much more reliable!

The Home Assistant equivalent of this plug-in can do this https://github.com/fuatakgun/eufy_security#features

Thoughts?

**Comment by schliemann** [comment]
Should be possible.

**Comment by bradleyrawleigh** [comment]
Please. This would be fantastic addition. Would allow HKSV cameras to have a trigger or dummy device based on animal person package being detected, turning on said dimmer trigger/switch. Therefor allowing automation creation in homekit based on said trigger/dummy switch. IE: person detected during daytime triggers a scene or a device to on or off.  Or something similar. Thanks for any help with these additions.
