### ISSUE TITLE
[enhancement]: Add Compatability for S330 4k Camera

### ISSUE THREAD

**Issue by RyanBeangstrom** [homebridge-eufy-security/plugin#291]
### Describe the solution you'd like

It would be great to add support for the S330 camera!

**Comment by Electr1fying** [comment]
They are supported and work fine for me in Beta 2.20 Build 19.

**Comment by nepofigist** [comment]
> They are supported and work fine for me in Beta 2.20 Build 19.

Does HKSV works well? If yes, would you please share settings? Thank you!
