### ISSUE TITLE
[Bug]: After Update to iOS 16.4 (Beta) no HomeKit Device found

### ISSUE THREAD

**Issue by Vollspacken** [homebridge-eufy-security/plugin#294]
### What happened?

After updating my iOS devices (iPhone + Apple TV) to iOS 16.4 (Beta) to improve HomeKit performance & possibly fix some issues, an Eufy Cam in HomeKit has now completely disappeared.

The Euyf plugin runs on the PI as a standalone bridge. After the reboot, the cam was still gone. Even after completely re-setting up the plugin & adding the eufy homebrige to HomeKit, only the bridge was displayed, but no compatible iOS device that I could assign to a room.

Seems like iOS 16.4 is now turning off some Homebridge plugins so they don't work in HomeKit anymore.

Would be great if this could be fixed with one of the upcoming plugin updates.

thanx,
Alex

### Device Type

Indoor Camera (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
No error visible in the log
```

### config

```shell
.
```

**Comment by dreondre** [comment]
I'm also on iOS 16.4 beta and this hasn't been my experience. 
I'm on HB 2.0.0 beta 0 and eufy plugin 2.1.4, with unbridged mode enabled.

Have you checked other rooms in your HomeKit home? For example, sometimes things end up in "Default Room".

Are you running the upgraded HomeKit mode or no? It was removed from 16.2 but it's being re-released for 16.4

Do you have any devices not running iOS 16.4 beta that you can compare with?

**Comment by Vollspacken** [comment]
Hello,

Thank you for your comment.

Indeed, I checked all other rooms, nowhere was a Device to be found. The camera was not shown to me either.

I have now several times reseted the plugin and & set up again, always as a separate bridge with different software versions.

After what felt like 20 attempts now finally the success. The camera is back online and now runs with the plugin version 2.1.4.

iOS 16.2 had already triggered the switch to the new HomeKit architecture, but after that everything ran normally.

No idea what the problem was in the end, but I'm happy that the camera is now integrated again via Homebridge.

**Comment by Vollspacken** [comment]
Closed
