### ISSUE TITLE
[enhancement]: 

### ISSUE THREAD

**Issue by jens-ac** [homebridge-eufy-security/plugin#307]
### Describe the solution you'd like

Hi team, are there any plans to integrate the Eufy S100 Wall Light Cam? Would be great.

**Comment by FTSCOOP** [comment]
I also want to know this.

**Comment by pgogins1** [comment]
Me too!

**Comment by FTSCOOP** [comment]
> Me too!

I hope someone answers soon. I really want it in HomeKit. Lol
