### ISSUE TITLE
[Bug]: Smart Lock no longer performs lock/unlock operations

### ISSUE THREAD

**Issue by sparsematrix** [homebridge-eufy-security/plugin#309]
### What happened?

The lock (identified by plugin as LOCK_WIFI) status is always correct and updates without issue, however toggling the lock state in either direction via HB UI or HomeKit does not perform actions any longer. No errors are printed to the HB log. Previously there were no issues locking/unlocking the Smart Lock through HomeKit. Clearly the plugin has some connection to Eufy as it  updates the lock's status in HomeBridge when locked or unlocked through the Eufy app or manually.

HomeBridge: 1.6
Plugin versions: 2.14 and 2.2.0-beta.19

### Device Type

other (UnSupported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

v16 (Supported)

### Operating System

Debian 10+ (Supported)

### Relevant log output

```shell
[EufySecurity-2.2.0-beta.19] INFO:  You're using guest admin account with this plugin! This is recommanded way!
[EufySecurity-2.2.0-beta.19] INFO:  Updating accessory: Back Door
```

### config

```shell
{
            "username": "redacted",
            "password": "redacted",
            "country": "US",
            "deviceName": "",
            "platform": "EufySecurity",
            "ignoreStations": [],
            "ignoreDevices": [],
            "cleanCache": true
        }
```

**Comment by bbatod** [comment]
I can confirm I am running into the same issue with T8520N.

**Comment by nackerr** [comment]
Did you manage to fix this @sparsematrix or @bbatod ?

**Comment by CarlComputerGuy** [comment]
This is still occurring for me. None of my Eufy locks (we have 5) work through HomeKit/Homebridge any longer. I’ve uninstalled and reinstalled the plugin multiple times, updated to newer versions, older versions, beta versions, etc.

**Comment by bbatod** [comment]
> Did you manage to fix this @sparsematrix or @bbatod ?

Nope. Still not working. Stays unlocking for a while then goes back to locked status without ever unlocking the lock at all. 

Logs are not showing much or I am not seeing it.

**Comment by sparsematrix** [comment]
No, I haven't found a resolution and have switched to a Tuya smart lock (BLE + wifi bridge). I've been pretty disappointed with the Eufy lock in general (slow to wake, poor fingerprint recognition, random errors about being jammed despite entirely clear path, etc). The Tuya plugin is mildly annoying in that API access has to be renewed every 6 months but at least everything works.

**Comment by nackerr** [comment]
Try and install version 2.2.2. I've been playing around.

I also have an issue open here:  https://github.com/homebridge-eufy-security/plugin/issues/384

**Comment by CarlComputerGuy** [comment]
> Try and install version 2.2.2. I've been playing around.
> 
> I also have an issue open here: #384

Thank you so much! 2.2.2 is working for me!! So glad to have this working again after over a month of not working. Thanks!!!
