### ISSUE TITLE
[Bug]: when keypad is used to turn off alarm it triggers alarm 

### ISSUE THREAD

**Issue by lukeishere02** [homebridge-eufy-security/plugin#310]
### What happened?

when the eufy keypad is used to turn off the alarm it triggers the alarm 

{"name":"[EufySecurity-2.1.4]","hostname":"Nunu","pid":20619,"level":40,"msg":"ON StationAlarmEvent - ALARM OFF - alarmEvent: 15","time":"2023-04-09T06:24:31.878Z","v":0}
{"name":"[EufySecurity-2.1.4]","hostname":"Nunu","pid":20619,"level":40,"msg":"ON StationAlarmEvent - ALARM TRIGGERED - alarmEvent: 6","time":"2023-04-09T06:24:32.020Z","v":0}
{"name":"[EufySecurity-2.1.4]","hostname":"Nunu","pid":20619,"level":40,"msg":"ON StationAlarmEvent - ALARM OFF - alarmEvent: 0","time":"2023-04-09T06:24:32.630Z","v":0}

I also noticed on the status that there is no eufy off only eufy disarm where on the app when you turn off the alarm on the keypad it turns it to the off setting not disarm 

<img width="773" alt="Screenshot 2023-04-09 at 10 56 56" src="https://user-images.githubusercontent.com/42520184/230766353-aa381ddc-78cb-4d92-92e0-0bf8415f99f3.png">
![IMG_3118](https://user-images.githubusercontent.com/42520184/230766372-7e756b7e-0df5-42c2-8118-bfd19a3587ca.PNG)
![IMG_3118](https://user-images.githubusercontent.com/42520184/230766501-6cd45b4c-ad5a-4336-b766-b5f2fe777c83.PNG)
<img width="359" alt="Screenshot 2023-04-09 at 11 01 49" src="https://user-images.githubusercontent.com/42520184/230766535-2cb405f5-7170-4a74-9c18-424a63eef9c7.png">

![IMG_3117](https://user-images.githubusercontent.com/42520184/230766374-8e53c58b-0dd1-482d-b173-698544541df9.PNG)

### Device Type

other (UnSupported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v12 (Supported)

### Operating System

Ubuntu 18.04+ (Supported)

### Relevant log output

```shell
{"name":"[EufySecurity-2.1.4]","hostname":"Nunu","pid":20619,"level":40,"msg":"ON StationAlarmEvent - ALARM OFF - alarmEvent: 15","time":"2023-04-09T06:24:31.878Z","v":0}
{"name":"[EufySecurity-2.1.4]","hostname":"Nunu","pid":20619,"level":40,"msg":"ON StationAlarmEvent - ALARM TRIGGERED - alarmEvent: 6","time":"2023-04-09T06:24:32.020Z","v":0}
{"name":"[EufySecurity-2.1.4]","hostname":"Nunu","pid":20619,"level":40,"msg":"ON StationAlarmEvent - ALARM OFF - alarmEvent: 0","time":"2023-04-09T06:24:32.630Z","v":0}
```

### config

```shell
"country": "GB",
    "ignoreStations": [
        "T8400P20211203F9",
        "T8400P20211211C8",
        "T8400P3121380939",
        "T8400P31220309FF"
    ],
    "ignoreDevices": [
        "T8113N63211217FD",
        "T8113N6321095ED4",
        "T8400P20211203F9",
        "T8400P20211211C8",
        "T8400P3121380939",
        "T8400P31220309FF",
        "T8900P0022094305",
        "T8910P002146070D",
        "T8960P0021290181"
    ],
    "cleanCache": true,
    "cameras": [
        {
            "serialNumber": "T8900P0022094305",
            "rtsp": false,
            "talkback": false
        },
        {
            "serialNumber": "T8910P002146070D",
            "rtsp": false,
            "talkback": false
        },
        {
            "serialNumber": "T8960P0021290181",
            "rtsp": false,
            "talkback": false
        }
    ]
```

**Comment by tkbmtl** [comment]
Same here, there is no eufy off only eufy disarm where on the app when you turn off the alarm on the keypad it turns it to the off setting not disarm
