### ISSUE TITLE
[Issue]: S220 Solocam?

### ISSUE THREAD

**Issue by 77degrees** [homebridge-eufy-security/plugin#311]
Removed my original post as they have now released the device I was beta testing, is there an ETA for the support to be added for the S220 Solocam device?

**Comment by spangborn** [comment]
While not necessarily the ideal solution, you could just create a guest account and share only what you want it to access. That's the preferred method for security reasons anyway.

**Comment by 77degrees** [comment]
@spangborn 
That is what I am currently doing as the solution. But, if the device is paired with the HomeBase 3 vs just Local Storage it doesn't allow you to specify what device to share. It's either the whole HomeBase 3 + Cameras using it as storage, or not sharing the HomeBase 3 at all. 😑

**Comment by ibmaster** [comment]
<img width="740" alt="image" src="https://github.com/homebridge-eufy-security/plugin/assets/40643856/6b553bfc-bac9-4c2e-938a-a69bd6a2725c">
As far as I can tell direct connect (no HomeBase 3) support for S220 is still not available in the latest beta. It doesn't recognize the shared camera as a camera...

**Comment by 77degrees** [comment]
S220 has HB3 support for me
![20230620_202017000_iOS](https://github.com/homebridge-eufy-security/plugin/assets/80057302/78534b15-970a-4f70-9d2c-0784360a94e7)

**Comment by ibmaster** [comment]
Yeah, I don’t have a HomeBase 3, so need direct network connection standalone S220 camera support as that’s the configuration I use with my eufy setup :(Ben.Sent from my iPhoneOn Jun 20, 2023, at 1:22 PM, 77degrees ***@***.***> wrote:﻿
S220 has HB3 support for me

**Comment by okaa-pi** [comment]
Hi. 
I have the same result on my end. 
S220 solocam, no homebase.
HomeBridge detects it as an alarm + switch, instead of as a camera. 

I can change the alarm « mode » to away, home, etc, and it does change the mode on the Eufy app. 
I have no idea what the switch does tho. 

Overall, would be nice if it was recognized as a camera. (Although my homebridge is on a RPi first gen so I doubt it would be able to stream the video).

**Comment by ibmaster** [comment]
I'm totally not familiar with this plugin's codebase, but would the update be as simple as adding the new DeviceType that matches DeviceType.SOLO_CAMERA with the new uniqueId reported from the S220 camera?

**Comment by ibmaster** [comment]
Or more accurately, changing the device.ts file from:

```
    static isSoloCameraBySn(sn: string): boolean {
        return sn.startsWith("T8130") ||
            sn.startsWith("T8131") ||
            sn.startsWith("T8122") ||
            sn.startsWith("T8123") ||
            sn.startsWith("T8124");
    }
```
to

```
    static isSoloCameraBySn(sn: string): boolean {
        return sn.startsWith("T8130") ||
            sn.startsWith("T8131") ||
            sn.startsWith("T8122") ||
            sn.startsWith("T8123") ||
            sn.startsWith("T8124") ||
            **sn.startsWith("T8134");**
    }
```

**Comment by okaa-pi** [comment]
> Or more accurately, changing the device.ts file from:
> ...

Which version of the code are you looking at? I can't find this piece of code anywhere in the codebase.

**Comment by ibmaster** [comment]
I was using the latest label 2.1.7. Seems like this routine is not leveraged anywhere for associating the Camera device type to eufy devices. Guess we need to figure out what the `com.oceanwing.battery.cam.binder.model.QueryDeviceData` call returns as a device type number for the S220 camera configured in standalone (no Homebase) mode and add that to the enum structure of DeviceTypes in types.ts

**Comment by toshibochan** [comment]
love to see the s220 camera to

**Comment by mistert871** [comment]
Love to see support for S220

**Comment by ibmaster** [comment]
I installed new Homebridge plugin release v2.2.2 which supposedly has native S220 support, however the device is still not recognized as a camera :(

**Comment by ibmaster** [comment]
Yep, not only did the S220 not show up as a camera, but with plugin v2.2.2 the S220’s battery would constantly drain down until I updated the plugin configuration to ignore the ‘unknown’ eufy device completely.
This wasn’t an issue on prior release plugins. So it sounds like latest plugin is trying to constantly connect to the S220 now to get status info even though it’s not fully working/supported as a standalone camera device yet… just beware of it draining your battery.

**Comment by julien94800** [comment]
Hello @ibmaster , indeed I get same issue! It took me 2 days to understand it comes from the plugin and I did same as you, block it fully from plugin and now it's fine again

**Comment by aberthil** [comment]
Confirm this is still not working with the S220

**Comment by ibmaster** [comment]
Still not working with release 2.2.5 :

[08/24/2023 03:37:01]   [EufySecurity-2.2.5]    WARN    [platform.ts:502]       This accessory is not compatible with HomeBridge Eufy Security plugin: Porch Type: 63

**Comment by ibmaster** [comment]
@lenoxys if you need a test setup with an S220 camera online or any debug logs for adding support for this camera, I'd be happy to provide.

**Comment by lenoxys** [comment]
hello did you check the compatibility list : https://bropat.github.io/eufy-security-client/#/supported_devices

As you can see S220 is not listed here yet. I can see on @bropat lib that a PR has been provided. It matter of weeks now until we can use it here : 
https://github.com/bropat/eufy-security-client/pull/353

**Comment by akno2205** [comment]
S220 is now supported. Please check the plugin by Borat. New version 2.9.0

**Comment by akno2205** [comment]
Sorry bropat

**Comment by ccanalia82** [comment]
How do you find version 2.9?Sent from my iPhoneOn Nov 4, 2023, at 10:55, akno2205 ***@***.***> wrote:﻿
S220 is now supported. Please check the plugin by Borat. New version 2.9.0

**Comment by akno2205** [comment]
Please look here 

https://github.com/bropat/eufy-security-client/releases/tag/2.9.1

**Comment by akno2205** [comment]
Please look here

https://github.com/bropat/eufy-security-client/releases/tag/2.9.1

**Comment by toshibochan** [comment]
https://github.com/bropat/eufy-security-client
just update
homebridge-eufy-security need to be updated to work with s220?

https://github.com/homebridge-eufy-security/plugin/issues/370#290-2023-11-04
(bropat/martijnpoppen) NEW: add support for S220 (T8134; https://github.com/homebridge-eufy-security/plugin/issues/353)

**Comment by lenoxys** [comment]
it's been back ported in 2.3.6 hksv

**Comment by ccanalia82** [comment]
I can’t seem to figure out how to install 2.9.1. I get 2.3.6 in the HomeBridge UI. I tried to install with @2.9.1 but that errors out. What am I doing wrong?On Nov 5, 2023, at 10:05, akno2205 ***@***.***> wrote:﻿
Please look here
https://github.com/bropat/eufy-security-client/releases/tag/2.9.1

**Comment by mynameisjosh83** [comment]
Has there been any update on this? As of now I can still not get any S220 solo cam's to show up in HomeKit.

**Comment by esprusso** [comment]
I can't seem to get the S220 to appear as a camera in the Home app. I'm on the native Synology Homebridge app, using 2.3.9 of the Eufy-Security plugin. All I get is an on-off switch, despite having the device set up as a camera in settings.

Log:

```
[12/16/2023, 09:32:03]  [EufySecurity]  INFO    Updating existing accessory: Garage
[12/16/2023, 09:32:06]  [EufySecurity]  INFO    Garage Setting up automatic snapshot refresh every 30 minutes. This may decrease battery life dramatically. The refresh process for Garage should begin in 1 minutes.
[12/16/2023, 09:32:06]  [EufySecurity]  INFO    Garage is set to balanced snapshot handling.
[12/16/2023, 09:32:42]  [EufySecurity]  INFO    Looking for old cached accessories that seem to be outdated...
[12/16/2023, 09:32:42]  [EufySecurity]  INFO    No outdated cached accessories found.
```
All that displays is this. I've reinstalled multiple times to no avail.

![IMG_0664](https://github.com/homebridge-eufy-security/plugin/assets/132158468/e02fef36-c21c-4dca-ada1-9740b0bd9a26)

**Comment by toshibochan** [comment]
Same here I can’t get to show as camera to

**Comment by jfegea3869** [comment]
when you g-have configure a pluggin, please add a camera with homebrige code. 
i have a camera but problem with a snapshot  terrase is a name on my S220 solocam :)

[12/24/2023, 11:52:22 AM] Please add [Terrasse 3ED2] manually in Home app. Setup Code: ...... homebridge code :)
[12/24/2023, 11:52:51 AM] [homebridge-eufy-security] This plugin slows down Homebridge. The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Terrasse 3ED2' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[12/24/2023, 11:52:55]  [EufySecurity]  INFO    Looking for old cached accessories that seem to be outdated...
[12/24/2023, 11:52:55]  [EufySecurity]  INFO    No outdated cached accessories found.
[12/24/2023, 11:53:02]  [EufySecurity]  ERROR   Error fetching snapshot: No snapshot in memory
[12/24/2023, 11:53:13]  [EufySecurity]  ERROR   Error fetching snapshot: No snapshot in memory
[12/24/2023, 11:53:24]  [EufySecurity]  ERROR   Error fetching snapshot: No snapshot in memory

**Comment by fahaad9** [comment]
Is there any update to this? I am planning to get S220 so want to make sure i can make it compatible with homekit.

**Comment by mistert871** [comment]
I'm wondering the same thing

**Comment by lenoxys** [comment]
try 2.3.26+ hksv special version / see wiki for the how to

**Comment by lenoxys** [comment]
I'm closing it since it's been a while. If need please open a new ticket.
