### ISSUE TITLE
[enhancement]: sound detection as motion

### ISSUE THREAD

**Issue by herbi3** [homebridge-eufy-security/plugin#316]
### Describe the solution you'd like

Option to enable sound as motion detection, allowing for HomeKit alerts for sounds (enables camera as somewhat of a baby monitor for “crying o sound for the indoor camera.

debug logs show sound detected! But naturally doesn’t trigger HomeKit notification

**Comment by herbi3** [comment]
any luck or tips we can do?

**Comment by lenoxys** [comment]
coming soon #361
