### ISSUE TITLE
S330 Cameras not showing up in Homekit

### ISSUE THREAD

**Issue by jcouzy** [homebridge-eufy-security/plugin#318]
### What happened?

S330 Cameras are not showing up in Homekit and are not configurable, only ignorable.

### Device Type

other (UnSupported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Debian 10+ (Supported)

### Relevant log output

```shell
I have no logging
```

### config

```shell
"username": "xxxx@xxxx.xxx",
            "password": "xxxxxxxxxx",
            "country": "NL",
            "deviceName": "",
            "platform": "EufySecurity",
            "cameras": [
                {
                    "serialNumber": "T8160P2122451F27",
                    "rtsp": false,
                    "talkback": false
                },
                {
                    "serialNumber": "T8210P6422411FF8",
                    "rtsp": false,
                    "enableCamera": true,
                    "useCachedLocalLivestream": true,
                    "videoConfig": {
                        "audio": true,
                        "audioSampleRate": 0
                    },
                    "talkback": true,
                    "immediateRingNotificationWithoutSnapshot": false,
                    "delayCameraSnapshot": true,
                    "snapshotHandlingMethod": 2,
                    "refreshSnapshotIntervalMinutes": 30
                },
                {
                    "serialNumber": "T8160P21224521B5",
                    "rtsp": false,
                    "talkback": false
                },
                {
                    "serialNumber": "T8410P42224801EB",
                    "useCachedLocalLivestream": true,
                    "rtsp": false,
                    "videoConfig": {
                        "audio": true,
                        "audioSampleRate": 0
                    },
                    "talkback": true,
                    "snapshotHandlingMethod": 2,
                    "delayCameraSnapshot": true,
                    "refreshSnapshotIntervalMinutes": 30
                }
            ],
            "_bridge": {
                "username": "0E:09:BD:51:1B:29",
                "port": 58032
            },
            "ignoreStations": [],
            "ignoreDevices": [],
            "cleanCache": true
        }
    ]
}
```

**Comment by LambdaEnt** [comment]
Same issue:

MacOS 13.3.1 
Homebridge 1.6.1
Node.js 18.16.0
Plugin 2.1.7

**Comment by bkleef** [comment]
Same issue:

Ubuntu: 20.04.5
Homebridge: 1.6.0
Node.js: 18.13.0
Plugin: 2.1.7

**Comment by jamaalmck** [comment]
For anyone still having issues with s330 compatibility - install the previous vs of Eufy Security Homebridge app. It's stable on the 2.2(beta) but not on the current one, for some reason. I'd run that, in the interim, until they fix whatever bug caused the upset in the new version.

**Comment by bkleef** [comment]
@jamaalmck which beta version of 2.2 did you try?

I tried beta.19:

```sh
npm install homebridge-eufy-security@2.2.0-beta.19
```

But no cameras for me with the following settings:

```json
{
    "platform": "EufySecurity",
    "username": "x",
    "password": "x",
    "country": "NL",
    "cameras": [
        {
            "serialNumber": "x",
            "rtsp": false,
            "talkback": false
        }
    ],
    "_bridge": {
        "name": "Homebridge Eufy cameras",
        "username": "x",
        "port": 51945,
        "pin": "x",
        "advertiser": "ciao"
    }
}
```

**Comment by jamaalmck** [comment]
> @jamaalmck which beta version of 2.2 did you try?
> 
> I tried beta.19:
> 
> ```shell
> npm install homebridge-eufy-security@2.2.0-beta.19
> ```
> 
> But no cameras for me with the following settings:
> 
> ```json
> {
>     "platform": "EufySecurity",
>     "username": "x",
>     "password": "x",
>     "country": "NL",
>     "cameras": [
>         {
>             "serialNumber": "x",
>             "rtsp": false,
>             "talkback": false
>         }
>     ],
>     "_bridge": {
>         "name": "Homebridge Eufy cameras",
>         "username": "x",
>         "port": 51945,
>         "pin": "x",
>         "advertiser": "ciao"
>     }
> }
> ```


I'm on Beta 19, as well. I currently have everything on a child bridge, and all Cameras are unbridged and added separately through HomeKit. Unbridging them should be at the bottom of each camera's settings, right above Snapshot Behavior. 
Child Bridges are located on the plugin page, just hit the wrench icon, bridge settings, turn on child bridges and reset. Hopefully that works for you.

**Comment by bkleef** [comment]
@jamaalmck thanks a lot for your reply and help. I did everything you and the docs describe without luck. I'm on Beta 19 with this config:

```json
        {
            "platform": "EufySecurity",
            "username": "x",
            "password": "x",
            "country": "NL",
            "cameras": [
                {
                    "serialNumber": "x",
                    "unbridge": true,
                    "rtsp": false,
                    "talkback": false,
                    "enableCamera": "true"
                }
            ],
            "_bridge": {
                "name": "Homebridge Eufy cameras",
                "username": "x",
                "port": 51945,
                "pin": "x",
                "advertiser": "ciao"
            }
        }
```

Can you please share your config?

**Comment by jamaalmck** [comment]
> @jamaalmck thanks a lot for your reply and help. I did everything you and the docs describe without luck. I'm on Beta 19 with this config:
> 
> ```json
>         {
>             "platform": "EufySecurity",
>             "username": "x",
>             "password": "x",
>             "country": "NL",
>             "cameras": [
>                 {
>                     "serialNumber": "x",
>                     "unbridge": true,
>                     "rtsp": false,
>                     "talkback": false,
>                     "enableCamera": "true"
>                 }
>             ],
>             "_bridge": {
>                 "name": "Homebridge Eufy cameras",
>                 "username": "x",
>                 "port": 51945,
>                 "pin": "x",
>                 "advertiser": "ciao"
>             }
>         }
> ```
> 
> Can you please share your config?

That's Odd. Is it showing up as Not Responding? Any errors in your log? 

Config: 

{
    "bridge": {
        "name": "Homebridge ABA3",
        "username": "x",
        "port": 51445,
        "pin": "x",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "username": "x",
            "password": "x",
            "country": "US",
            "deviceName": "",
            "platform": "EufySecurity",
            "ignoreStations": [
                "T8410P20204203E1",
                "T8410P202042327E"
            ],
            "cameras": [
                {
                    "serialNumber": "x",
                    "hsv": true,
                    "hsvRecordingDuration": 90,
                    "hsvConfig": {},
                    "snapshotHandlingMethod": 3,
                    "enableCamera": "true",
                    "enableButton": false,
                    "motionButton": false,
                    "unbridge": true,
                    "videoConfig": {
                        "audio": false
                    },
                    "talkback": false,
                    "talkbackChannels": 1
                },
                {
                    "serialNumber": "x",
                    "hsv": true,
                    "hsvRecordingDuration": 90,
                    "hsvConfig": {},
                    "snapshotHandlingMethod": 3,
                    "enableCamera": "true",
                    "unbridge": true,
                    "enableButton": false,
                    "motionButton": false
                },
                {
                    "serialNumber": "x",
                    "hsv": true,
                    "hsvRecordingDuration": 90,
                    "hsvConfig": {},
                    "snapshotHandlingMethod": 3,
                    "enableCamera": "true",
                    "videoConfig": {
                        "audio": true
                    },
                    "talkback": true,
                    "talkbackChannels": 1
                }
            ],
            "ignoreDevices": [
                "X",
                "X"
            ],
            "ignoreMultipleDevicesWarning": true,
            "cleanCache": true,
            "_bridge": {
                "username": "x",
                "port": 33879
            }
        }
    ]
}

**Comment by funtush** [comment]
I am getting similar error camara not responding. 
[7/7/2023, 11:31:19 AM] [EufySecurity-2.1.7] INFO:  Country set: US
[7/7/2023, 11:31:19 AM] [EufySecurity-2.1.7] INFO:  Finished initializing!
[7/7/2023, 11:31:20 AM] [EufySecurity-2.1.7] ERROR: Not connected can't continue!
