### ISSUE TITLE
[enhancement]: T8213 (Doorbell Dual) Support

### ISSUE THREAD

**Issue by noltondyer** [homebridge-eufy-security/plugin#32]
### Describe the solution you'd like

I’ve been following along, and with the posting of 2.0 being updated to the latest @bropat - I’m curious why my Video Doorbell Dual is still showing as unsupported, seeing as the latest @bropat update adds support, and it’s listed in the compatible devices page.

**Comment by lenoxys** [comment]
Hello,

Good point missing some code. Just added please test beta.9

**Comment by thieren** [comment]
Can anyone confirm that T8213 is working?
