### ISSUE TITLE
[Bug]: eufy cams no longer visible on HomeKit. 

### ISSUE THREAD

**Issue by dd3uk** [homebridge-eufy-security/plugin#330]
### What happened?

Homebridge now shows error logs as follows. 

[6/12/2023, 2:19:32 PM] [EufySecurit y-2.1.7] INFO: You're using guest a dmin account with this plugin! This is recommanded way!
[6/12/2023, 2:19:32 PM] [EufySecurit y-2.1.7] INFO:
Updating accessory:
Ulverley
[6/12/2023, 2:19:32 PM] [EufySecurit y-2.1.7] WARN:
This accessory is no
t compatible with HomeBridge Eufy Se curity plugin: Gate Ulverley Type: 2
3
[6/12/2023, 2:19:32 PM] [EufySecurit y-2.1.7] WARN: This accessory is no t compatible with HomeBridge Eufy Se curity plugin: Driveway Ulverley Typ e: 23

Previously these cams used to show up on HomeKit. 

Homebridge is fully up to date. V1.6.1
Node js 18.16.0 

let me know if anything else needed. 
Homebase is s380 running v 3.2.0.3 
Cameras are s300 running v3.2.1.6 sub system v0.2.0.5

### Device Type

Floodlight (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

other (UnSupported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[6/12/2023, 2:19:32 PM] [EufySecurit y-2.1.7] INFO: You're using guest a dmin account with this plugin! This is recommanded way!
[6/12/2023, 2:19:32 PM] [EufySecurit y-2.1.7] INFO:
Updating accessory:
Ulverley
[6/12/2023, 2:19:32 PM] [EufySecurit y-2.1.7] WARN:
This accessory is no
t compatible with HomeBridge Eufy Se curity plugin: Gate Ulverley Type: 2
3
[6/12/2023, 2:19:32 PM] [EufySecurit y-2.1.7] WARN: This accessory is no t compatible with HomeBridge Eufy Se curity plugin: Driveway Ulverley Typ e: 23
```

### config

```shell
{
            "username": "xxxx@icloud.com",
            "password": "xxxxx",
            "country": "GB",
            "deviceName": "",
            "platform": "EufySecurity",
            "_bridge": {
                "username": "0E:42:28:E0:41:A8",
                "port": 43640
            },
            "ignoreStations": [],
            "ignoreDevices": [],
            "cleanCache": true,
            "stations": [
                {
                    "serialNumber": "T8030P23222901A9",
                    "manualTriggerModes": [
                        0,
                        1,
                        2,
                        3
                    ]
                }
            ],
            "cameras": [
                {
                    "serialNumber": "T8161P1022340682",
                    "rtsp": false,
                    "talkback": false
                },
                {
                    "serialNumber": "T8161P1022340C36",
                    "rtsp": false,
                    "talkback": false
                }
            ]
        },
```

**Comment by thecolinscott** [comment]
PROBLEM RESOLVED - SYMPTOMS CAUSED BY DNS ERROR ELSEWHERE ON NETWORK.  NO ERROR, NO BUG!

**Comment by dd3uk** [comment]
No it’s not resolved the app says devices not supported 
Please see attached 
![IMG_3247](https://github.com/homebridge-eufy-security/plugin/assets/31772238/b485e6c9-dfa8-439f-84b8-dd01aa717942)

**Comment by thecolinscott** [comment]
It's all very odd.  The doorbells went back to being visible in HomeKit (my complaint in the OP was that they had vanished), but no, they don't work as they used to, and not all functionality seems to be available..

It looks as if this might be due to the recent software updates to Apple Home, which have broken other stuff too.  For example, all my Athom switches (which as I understand it use Tasmota) simultaneously went into "Device Not Responding" mode after I installed the updates  This Eufy failure seems to have occurred at about the time the updates appeared, and the date of my OP corresponds with the first reportsin the Athom forums of Athom switches going non-responsive .

I guess the moral of the story is that if you want to use HomeKit one should use HomeKit certified kit.  :-(

**Comment by dd3uk** [comment]
Hi Colin, 

This is not looking like a HomeKit issue. It's Homebridge plugin not accepting the cameras anymore before it gets to homekit. 

Please stop posting this is working now etc. on my report or diagnosing HomeKit updates etc it’s potentially confusing to whomever is creating or working on updates/bugs. Thanks

**Comment by dd3uk** [comment]
And yes in the plugin the camera is on and it works in the eufy app on my phone

**Comment by richieboyle** [comment]
Same issue. Any progress?

**Comment by richieboyle** [comment]
I disabled the child bridge and the camera came back with what appears to be full functionality. I will re-add the child bridge another day to see if that repaired it.

**Comment by pgogins1** [comment]
Any updates on this?

**Comment by dd3uk** [comment]
Unfortunately nothing useful. Getting this working has been hampered by the fact that my eufy system did an update and now Homebase 3 is not recording or able to give me motion alerts even in the eufy app !

I intend trying above and removing the child bridge.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lenoxys** [comment]
try to update to the latest version 2.2.5
