### ISSUE TITLE
[enhancement]: S100 EUFY LIGHT SUPPORT

### ISSUE THREAD

**Issue by FTSCOOP** [homebridge-eufy-security/plugin#337]
### Describe the solution you'd like

Been waiting for S100 Eufy plugin to come into homekit.  It doesn't show the camera in homekit.  It just shows it as light and motion sensor.  No camera support.

**Comment by pgogins1** [comment]
https://github.com/bropat/eufy-security-client/issues/318

**Comment by lenoxys** [comment]
done #351

**Comment by julien94800** [comment]
Hello @lenoxys ,
If I'm correct the light support is not implemented. Indeed the device now work as camera but no way to manage light on/off

**Comment by pgogins1** [comment]
I'm Okay with that! Thanks for your work
