### ISSUE TITLE
[enhancement]: Add support for CAM S220 SoloCam

### ISSUE THREAD

**Issue by julien94800** [homebridge-eufy-security/plugin#338]
### Describe the solution you'd like

Hello
This device type is not compatible at the moment. It seems to be device code 63 from log error message during startup.
Please let me know if any info from devices are needed.
Thanks in advance

**Comment by Vollspacken** [comment]
I also bought the S220 solo a few days ago to be able to use it with Homebridge/HomeKit.

Would be really great if a cam support in the Eufy plugin could be made available in the short term to revise the mistake that Eufy has made (no official HomeKit support) again. 

I plan then, if the Homebridge support for this cam is available, to buy more. With the built-in solar panel, the S220 is really great & relatively small. 

Thanks in advance & keep up the good work!

BR,
Alex

**Comment by ibmaster** [comment]
@julien94800 Have you tried to add enumerated device type 63 in src/configui/app/util/eufy-security-client.utils.ts and updating static isCamera function to include the new device type? I think that should be sufficient as the plugin can already see the Solo220 present in latest build, it just doesn't properly recognize it as a camera.

**Comment by LambdaEnt** [comment]
While the author of this plug in please respond an update it for the current line up of cameras?

**Comment by julien94800** [comment]
Hello @ibmaster 
No I did not tried yet. My first idea was to update the file and put code 63 for the 2Cpro camera in the code in order having to update only one line cause I assume both devices should have close functionalities. But then I was locked due to permission on files on my docker installation.

**Comment by julien94800** [comment]
I checked again this morning and I did not found this file.... I'm not skilled enough. If I'm correct these information are only saved in a dependency script?

**Comment by toshibochan** [comment]
I have the Solo220 to and I wish I could see the camera on my home app

**Comment by mistert871** [comment]
I also have the Solo 220 and looking forward to supporting this device.

**Comment by lenoxys** [comment]
done #351

**Comment by julien94800** [comment]
Hello @lenoxys , this device is not yet compatible with last library version

**Comment by ibmaster** [comment]
@julien94800 perhaps is the issue that there is no official homebridge plugin npm release label that incorporates the latest underlying plugin version v2.1.11?

**Comment by toshibochan** [comment]
eufy-security-client just added s220. hope soon will be working.

https://github.com/bropat/eufy-security-client/pull/353/files/0667e02f2c663de3d42b604669fe83370825bd70..d004fb4f33d3cde1cdd1426ac52a30ce9d5ef8e8

**Comment by toshibochan** [comment]
https://github.com/bropat/eufy-security-client
just update
homebridge-eufy-security need to be updated to work with s220?

https://github.com/homebridge-eufy-security/plugin/issues/370#290-2023-11-04
(bropat/martijnpoppen) NEW: add support for S220 (T8134; https://github.com/homebridge-eufy-security/plugin/issues/353)

**Comment by mistert871** [comment]
> it's been back ported in 2.3.6 hksv

I just tried / test it with version 2.3.6 hksv on a clean install but it is not working. It still shows S220 as an alarm.

**Comment by Vollspacken** [comment]
I also just tried / test it with version 2.3.6 hksv but it is not working. No selection for Operating Mode "Camera" shown. (See Screenshot)

In my homebridge Log-File i found this: 

[11/06/2023, 13:10:22]  [EufySecurity]  ERROR   Garten-Pool handleSecuritySystemCurrentStateGets: Wrong return value
[11/06/2023, 13:10:22]  [EufySecurity]  ERROR   Garten-Pool handleSecuritySystemTargetStateGet: Wrong return value


![S220_Homebridge](https://github.com/homebridge-eufy-security/plugin/assets/117859123/bfa0b327-4d64-4d80-bdc5-0da9ac8ad6ea)

**Comment by mynameisjosh83** [comment]
Is there any update to get this working?

**Comment by webprogi46** [comment]
I also would like to add my S220 to homebridge. Please update the plugin. Many, many thanks.

**Comment by mistert871** [comment]
Still no update. Is this actively researched. Would be great
