### ISSUE TITLE
[Help]: How to use the email verification code?

### ISSUE THREAD

**Issue by Willygoat1** [homebridge-eufy-security/plugin#36]
### What happened?

I get the email for the 2fa but there is no where to use in in the plugin config.

### Device Type

Indoor Camera (Supported)

### Plugin Version

v0.2.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X 11+ (Supported)

**Comment by thieren** [comment]
As this is answered in the wiki I'll close this issue:

https://github.com/homebridge-eufy-security/plugin/wiki/Configuration
