### ISSUE TITLE
[enhancement]: please fix the issue from today

### ISSUE THREAD

**Issue by Milchbeck** [homebridge-eufy-security/plugin#368]
### Describe the solution you'd like

Today don’t work the plug-in can you please fix it I think eufy make a update

**Comment by msegzda** [comment]
This roadmap page is dead link. I guess @Milchbeck is referring to issue described here: https://github.com/homebridge-eufy-security/plugin/issues/334

**Comment by lenoxys** [comment]
this is not an enhancement ticket
