### ISSUE TITLE
add S220 solar camera

### ISSUE THREAD

**Issue by toshibochan** [homebridge-eufy-security/plugin#370]
### Describe the solution you'd like

can add S220 solar camera to view camera image and record on HomeKit please.

**Comment by toshibochan** [comment]
https://github.com/bropat/eufy-security-client/pull/353/files/0667e02f2c663de3d42b604669fe83370825bd70..d004fb4f33d3cde1cdd1426ac52a30ce9d5ef8e8

**Comment by ibmaster** [comment]
There’s already a request open for this Ben.Sent from my iPhoneOn Aug 18, 2023, at 4:36 PM, Toshi Taka ***@***.***> wrote:﻿
Describe the solution you'd like
can add S220 solar camera to view camera image and record on HomeKit please.

**Comment by toshibochan** [comment]
https://github.com/bropat/eufy-security-client
just update
homebridge-eufy-security need to be updated to work with s220?

[2.9.0 (2023-11-04)](https://github.com/homebridge-eufy-security/plugin/issues/370#290-2023-11-04)
(bropat/martijnpoppen) NEW: add support for S220 (T8134; #353)

**Comment by lenoxys** [comment]
it's been back ported in 2.3.6 hksv

**Comment by Vollspacken** [comment]
Hi,

Thank you for the fast update! 

Unfortunately, after updating to 2.3.6, I cannot switch hksv to device "Camera" in the device overview in Homebridge as actually required 
I have already completely uninstalled & reinstalled the plugin - but no selection option. 

Does anyone happen to have the same problem?


![S220_Homebridge](https://github.com/homebridge-eufy-security/plugin/assets/117859123/e5567576-f137-4ec4-a447-4d69261d4a3c)

**Comment by d4nm0** [comment]
is it possible to publish an npm package for version 2.3.6?

**Comment by d4nm0** [comment]
I have a problem: I can see my camera, but I can't see the video stream. 
![image](https://github.com/homebridge-eufy-security/plugin/assets/20597792/20778be9-0051-4148-83eb-f9d1b102462e)
![image](https://github.com/homebridge-eufy-security/plugin/assets/20597792/a5f806f3-3a33-4578-aa29-f557f0a4267f)

**Comment by d4nm0** [comment]
is it possible to see the live stream or just images?

**Comment by d4nm0** [comment]
hello my conf: 
{
    "platform": "EufySecurity",
    "username": "xxx",
    "password": "xxxx.xx",
    "enableDetailedLogging": 1,
    "enableCamera": true,
    "pollingIntervalMinutes": 1,
    "hkHome": 1,
    "hkAway": 0,
    "hkNight": 3,
    "hkOff": 63,
    "country": "FR"
}
dont have image here : 
![image](https://github.com/homebridge-eufy-security/plugin/assets/20597792/7bb7bddc-084f-4ddb-a063-e3c0ce2a2b84)

07/11/2023 12:08:39HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:39[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[LocalLivestreamManager.ts:95[0m[0m]	Arrière-cour Stopping station livestream.
07/11/2023 12:08:39HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:39[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[LocalLivestreamManager.ts:44[0m[0m]	Arrière-cour Initialize before livestream.
07/11/2023 12:08:39HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:39[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[LocalLivestreamManager.ts:46[0m[0m]	Arrière-cour Cleaning before livestream.
07/11/2023 12:08:39HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:39[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[utils.ts:133[0m[0m]	An error occurred while unlinking the file: Error: ENOENT: no such file or directory, unlink '/tmp/T8134P202329426E.1.sock'
07/11/2023 12:08:39HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:39[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[utils.ts:137[0m[0m]	Resources cleaned up.
07/11/2023 12:08:39HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:39[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[utils.ts:133[0m[0m]	An error occurred while unlinking the file: Error: ENOENT: no such file or directory, unlink '/tmp/T8134P202329426E.2.sock'
07/11/2023 12:08:39HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:39[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[utils.ts:137[0m[0m]	Resources cleaned up.
07/11/2023 12:08:39HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:39[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[34m[1mINFO[22m[39m[0m[0m	[LocalLivestreamManager.ts:103[0m[0m]	Arrière-cour station livestream for Arrière-cour has stopped.
07/11/2023 12:08:39HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:39[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[LocalLivestreamManager.ts:44[0m[0m]	Arrière-cour Initialize before livestream.
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'AccessoryInformation / Manufacturer': Eufy
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'AccessoryInformation / Model': SOLO_CAMERA_SOLAR
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'AccessoryInformation / Name': Arrière-cour
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'AccessoryInformation / SerialNumber': T8134P202329426E
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'AccessoryInformation / FirmwareRevision': 3.2.6.1
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'AccessoryInformation / HardwareRevision': 0.0.0.2
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[StationAccessory.ts:323[0m[0m]	Arrière-cour GET StationCurrentMode: 1
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'SecuritySystem / SecuritySystemCurrentState': 0
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[StationAccessory.ts:323[0m[0m]	Arrière-cour GET StationCurrentMode: 1
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'SecuritySystem / SecuritySystemTargetState': 0
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'AccessoryInformation / Manufacturer': Eufy
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'AccessoryInformation / Model': SOLO_CAMERA_SOLAR
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'AccessoryInformation / Name': Porte d'entrée
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'AccessoryInformation / SerialNumber': T8134P20232987A5
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'AccessoryInformation / FirmwareRevision': 3.2.6.1
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'AccessoryInformation / HardwareRevision': 0.0.0.2
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[StationAccessory.ts:323[0m[0m]	Porte d'entrée GET StationCurrentMode: 1
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'SecuritySystem / SecuritySystemCurrentState': 0
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[StationAccessory.ts:323[0m[0m]	Porte d'entrée GET StationCurrentMode: 1
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'SecuritySystem / SecuritySystemTargetState': 0
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'AccessoryInformation / Manufacturer': Eufy
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'AccessoryInformation / Model': SOLO_CAMERA_SOLAR
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'AccessoryInformation / Name': Arrière-cour
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'AccessoryInformation / SerialNumber': T8134P202329426E
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'AccessoryInformation / FirmwareRevision': 3.2.6.1
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'AccessoryInformation / HardwareRevision': 0.0.0.2
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'MotionSensor / MotionDetected': false
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'Battery / BatteryLevel': 75
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[CameraAccessory.ts:564[0m[0m]	Arrière-cour GET 'On' enabled: true
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'Switch / On': true
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[CameraAccessory.ts:564[0m[0m]	Arrière-cour GET 'On' motionDetection: true
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Arrière-cour GET 'Switch / On': true
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'AccessoryInformation / Manufacturer': Eufy
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'AccessoryInformation / Model': SOLO_CAMERA_SOLAR
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'AccessoryInformation / Name': Porte d'entrée
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'AccessoryInformation / SerialNumber': T8134P20232987A5
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'AccessoryInformation / FirmwareRevision': 3.2.6.1
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'AccessoryInformation / HardwareRevision': 0.0.0.2
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'MotionSensor / MotionDetected': false
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'Battery / BatteryLevel': 25
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[CameraAccessory.ts:564[0m[0m]	Porte d'entrée GET 'On' enabled: true
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'Switch / On': true
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[CameraAccessory.ts:564[0m[0m]	Porte d'entrée GET 'On' motionDetection: true
07/11/2023 12:08:43HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:08[0m[0m:43[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:161[0m[0m]	Porte d'entrée GET 'Switch / On': true
07/11/2023 12:09:14HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:09[0m[0m:14[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[34m[1mINFO[22m[39m[0m[0m	[platform.ts:612[0m[0m]	Looking for old cached accessories that seem to be outdated...
07/11/2023 12:09:14HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:09[0m[0m:14[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[34m[1mINFO[22m[39m[0m[0m	[platform.ts:628[0m[0m]	No outdated cached accessories found.
07/11/2023 12:13:33HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:13[0m[0m:33[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:105[0m[0m]	Arrière-cour Raw Property Changes: 1101 74
07/11/2023 12:13:33HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:13[0m[0m:33[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:110[0m[0m]	Arrière-cour Property Changes: battery 74
07/11/2023 12:13:33HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:13[0m[0m:33[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:105[0m[0m]	Arrière-cour Raw Property Changes: 1142 -79
07/11/2023 12:13:33HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:13[0m[0m:33[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:110[0m[0m]	Arrière-cour Property Changes: wifiRssi -79
07/11/2023 12:13:33HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:13[0m[0m:33[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:105[0m[0m]	Arrière-cour Raw Property Changes: 1138 8
07/11/2023 12:13:33HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:13[0m[0m:33[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:110[0m[0m]	Arrière-cour Property Changes: batteryTemperature 8
07/11/2023 12:14:33HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:14[0m[0m:33[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:105[0m[0m]	Arrière-cour Raw Property Changes: 1138 10
07/11/2023 12:14:33HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:14[0m[0m:33[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:110[0m[0m]	Arrière-cour Property Changes: batteryTemperature 10
07/11/2023 12:14:33HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:14[0m[0m:33[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:105[0m[0m]	Porte d'entrée Raw Property Changes: 1142 -77
07/11/2023 12:14:33HOOBS[11[0m[0m/07[0m[0m/2023[0m[0m 11[0m[0m:14[0m[0m:33[0m[0m]	[32m[EufySecurity-2.3.6][39m[0m[0m	[32m[1mDEBUG[22m[39m[0m[0m	[BaseAccessory.ts:110[0m[0m]	Porte d'entrée Property Changes: wifiRssi -77

**Comment by toshibochan** [comment]
2.3.7 hksv slolar s220 live view and recording not working.

**Comment by d4nm0** [comment]
> 2.3.7 hksv slolar s220 live view and recording not working.

I don't have anything that works. I don't even have a picture.
![image](https://github.com/homebridge-eufy-security/plugin/assets/20597792/ef3c1b62-ca76-4678-b605-caf4bf27f87b)
