### ISSUE TITLE
[Bug]: Node Version

### ISSUE THREAD

**Issue by shortcopper** [homebridge-eufy-security/plugin#371]
### What happened?

After updating to the new version from beta (due to numbering issue) I reverted back to Beta to get HSV back and now the plugin states that Node version 18.16 is required. Which did not show up in logs prior to the upgrade and downgrade.

### Device Type

Station (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Other (UnSupported)

### Relevant log output

```shell
The plugin "homebridge-eufy-security" requires Node.js version of >=18.16.0 which does not satisfy the current Node.js version of v18.15.0. You may need to upgrade your installation of Node.js
```

### config

```shell
N/A
```

**Comment by lenoxys** [comment]
Please try upgrading to 2.2.3 then downgrade to beta.

**Comment by shortcopper** [comment]
After updating to v2.2.3 the warning about node when away, but once I then downgraded to beta it came back, and the settings in beta do not include any HSV settings.

`[8/23/2023, 11:24:37 AM] The plugin "homebridge-eufy-security" requires Node.js version of >=18.16.0 which does not satisfy the current Node.js version of v18.15.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
[8/23/2023, 11:24:37 AM] Loaded plugin: homebridge-eufy-security@2.2.1
[8/23/2023, 11:24:37 AM] Registering platform 'homebridge-eufy-security.EufySecurity'
[8/23/2023, 11:24:37 AM] ---`

**Comment by lenoxys** [comment]
try it now it should be fine. 2.3.0-beta0 nothing has change.

**Comment by shortcopper** [comment]
Awesome, worked perfect! thanks again.

**Comment by lenoxys** [comment]
thanks, I'm closing this thread.
