### ISSUE TITLE
[Bug]: Activate experimental homekit secure video

### ISSUE THREAD

**Issue by diablotin84** [homebridge-eufy-security/plugin#375]
### What happened?

How to activate the experimental homekit secure video function with release 2.2.2 or 2.2.1-beta ?
The menu for enable experimental options or hkv not appears in my interface.

Thanks for return.

### Device Type

Doorbell (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Debian 10+ (Supported)

### Relevant log output

```shell
/
```

### config

```shell
/
```

**Comment by lenoxys** [comment]
try on 2.3.0 beta. see here how to use beta : 

https://github.com/homebridge-eufy-security/plugin/wiki/RC---Beta-Version

**Comment by zthun** [comment]
Same issue here.

I just updated my plugin from the 2.2.x beta to 2.2.5 and HSV is no longer in the plugin.  I tried updating to the 2.3.0 beta version, and there are no HSV options anymore?  Was this removed intentionally?

**Comment by lenoxys** [comment]
try the [2.3.1-beta.2](https://www.npmjs.com/package/homebridge-eufy-security/v/2.3.1-beta.2)

**Comment by lenoxys** [comment]
hello, I've finished the rewriting of a lot of code make me more easy to read after few months off. I will work on HKSV but I've to get the work of @thieren and it will my first try. Bear with me.

**Comment by diablotin84** [comment]
> try on 2.3.0 beta. see here how to use beta :
> 
> https://github.com/homebridge-eufy-security/plugin/wiki/RC---Beta-Version

Work perfectly with this version. Thanks :)
