### ISSUE TITLE
Looks like I'm also running into this same exact error. Unfortunately for me, I've tried all of the listed steps above (delete everything - plugin, settings, cache, etc.) and am still getting the "[EufySecurity-2.2.5]    ERROR   [platform.ts:228]       Not connected can't continue!".

### ISSUE THREAD

**Issue by lenoxys** [homebridge-eufy-security/plugin#385]
Looks like I'm also running into this same exact error. Unfortunately for me, I've tried all of the listed steps above (delete everything - plugin, settings, cache, etc.) and am still getting the "[EufySecurity-2.2.5]    ERROR   [platform.ts:228]       Not connected can't continue!".

Logs: https://drive.google.com/drive/folders/1G5Cxc7BTOAaCeoDopsUR5yoI9kwldkIr?usp=sharing

_Originally posted by @frozenfractals in https://github.com/homebridge-eufy-security/plugin/issues/379#issuecomment-1696935344_

**Comment by lenoxys** [comment]
do you use a dedicated account for the plugin ? 
https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin

can you log using this account into Eufy App while plugin is disabled ? Do you see any prompt ? When done logout from this account and try to reset (red button) then log back.

**Comment by alanyenhk** [comment]
Same issue on me🥲

**Comment by alanyenhk** [comment]
Just tried to create another dedicated account and joined the home. It works again.

Not sure if it helps…

**Comment by frozenfractals** [comment]
Thanks for the tips, guys! Unfortunately, it's still not working for me. I've tried:

1.) Using main account
2.) Using dedicated account via sharing entire home (followed guide as per lenoxys above)
3.) Using dedicated account via sharing individual devices with admin rights (ditto)
4.) Tried uninstalling the plugin, remove all configuration data, reset Homebridge cache, etc.

With all of that, I'm still getting the dreaded error: `[EufySecurity-2.2.5] ERROR [platform.ts:228] Not connected can't continue!`

**Comment by lenoxys** [comment]
Can you try the test version ?

**Comment by Fab57-tech** [comment]
[https://github.com/homebridge-eufy-security/plugin/issues/379](url)

**Comment by lenoxys** [comment]
try 2.2.6?

**Comment by pmcdowall** [comment]
I'm also having this issue, tried version 2.2.5 and 2.2.7. Turned on the debug logs and it looks like a captcha is being received each time Homebridge restarts that is preventing the plugin from logging in. Logs below.

[09/02/2023 08:03:13]   [EufySecurity-2.2.7]    DEBUG   [api.ts:83]     Loaded API {
  apieBase: 'https://security-app.eufylife.com',
  country: 'AU',
  username: 'xxx@gmail.com',
  persistentData: {
    user_id: '',
    email: '',
    nick_name: '',
    device_public_keys: {},
    clientPrivateKey: 'xxxxxxxxx',
    serverPublicKey: 'xxxxxxxxxxxx'
  }
}
[09/02/2023 08:03:13]   [EufySecurity-2.2.7]    DEBUG   [eufysecurity.ts:174]   Load previous login_hash {
  login_hash: 'xxxxxxxx'
}
[09/02/2023 08:03:13]   [EufySecurity-2.2.7]    DEBUG   [api.ts:293]    Login and get an access token {
  token: null,
  tokenExpiration: null,
  options: {
    force: false
  }
}
[09/02/2023 08:03:13]   [EufySecurity-2.2.7]    DEBUG   [api.ts:618]    Api request {
  method: 'post',
  endpoint: 'v2/passport/login_sec',
  responseType: undefined,
  token: null,
  data: {
    ab: 'AU',
    client_secret_info: {
      public_key: 'xxxxxxxxxx'
    },
    enc: 0,
    email: 'xxxxx@gmail.com',
    password: '[***]',
    time_zone: 36000000,
    transaction: '1693641793121'
  }
}
[09/02/2023 08:03:14]   [EufySecurity-2.2.7]    DEBUG   [api.ts:631]    Api request - Response {
  token: null,
  request: {
    method: 'post',
    endpoint: 'v2/passport/login_sec',
    data: {
      ab: 'AU',
      client_secret_info: {
        public_key: 'xxxxxxxxxxx'
      },
      enc: 0,
      email: 'xxxxxx@gmail.com',
      password: '[***]',
      time_zone: 36000000,
      transaction: '1693641793121'
    }
  },
  response: {
    code: 100032,
    msg: 'Failed to request.',
    data: {
      captcha_id: 'ec794b48-4a56-4ec8-8ff2-8371e8a6b161',
      item: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFUAAAArCAIAAACGv1O8AAAJeElEQVR4nOyabUxb1RvA7729vS0bZSusa9qydthmHaXMtWSZS+fL3JyJlCrTBEh1xqQm6owRQ3S6fXDxi2kWErdsxg8TTaRrpguKiWvWbmsmC9ICBYowQGnLW2uhxdKWvt2Xf7L7T62Ue2GKEsN+n7pznuec5znPc55z7hkwQRDABgZabwPWmQf+b2we+L+xeeD/xuaB/xsbeL0NWAMwDLPZbIlE4rHHHisuLr4/ZWJNwXF88R70YvF43GazdXR0rMmkP//8886dO2UymdPpRFGUyrBMJpPfvpb5TxDEb7/9ZjQa29ra5ubmqMQSiURra+ubb77Z2NgYDof/5qQ4jqdSKa/XOzU15fV6GQzGsmIzMzMnT540Go3xeHyp0WtFMpk8f/48CIJsNvvdd98NhUL5MiiK3rhxQyaTQRBUVVWVTqeXHWrZWFHR1dVVVFTE4/HOnj2b34vjeCAQOH78OAAAO3bsCAQCub1r6T+O43fv3pVIJCAIQhBkNBoTicQSmUAgcOjQIQAAuFyu3W7HcTx/kOHh4Vu3bo2Pj2MYtpp57Xa7Wq3esmXLBx98kN87Nzd38eJFGIYLCwvr6+uX7M013v8EQbjdbrlcDkFQYWHh1atXcyOMoujp06c3bdoEQdDZs2djsVi++uDg4LFjxzgczsmTJ/OXb1m6u7uPHj3KYDDee++9/DEtFsvBgwcZDEZ1dXV3d/eS3tXu/0QiMTg42NnZOTw8HIvFaCSVSuXFixfLysoWFxdPnz59+/btdDpNdtlsNrPZnEwmq6urn3/++U2bNlHNBUHQ77//DsOrOp6kUil5CsTj8fn5+dyucDj8ww8/uFwumUxWX1+/Z8+epcqrWeDr16+/+uqrNTU1jz766IEDB+rq6kwmUygUys/eLBcuXBCLxRAEPf744x0dHalUanJyUqfTsVgskUhksVhSqRSVrtPp/OSTT1wu1+qrgFarRRBEq9VOTEzktre3tyuVShAEm5qaPB5PviKd/ziOR6NRo9EoEomYTCaLxZJKpaWlpTAMFxcXNzQ0eL1eqi2aTqdPnTolFAohCKqtre3s7Pzoo494PB6DwTh16lQwGKSZ976KH2lnY2MjCIJisXhhYSHbjqJobW1tQUEBj8fr7+/PDXk28HT+z87ONjc3wzCMIIharT5z5sylezz77LMAAGzbtu3bb7+lUZ+fn29sbNy+fTuTyXzuueekUimDwXjiiSe6urqoTulcRkZGbDYbTZpkicVin332GVnefT4f2ZhOp61Wa0FBAZPJfO2116iyns7/tra2srIyFotVXV1tt9vj8ThBENFo9IsvvgAAoLy83Gaz0Vvm8/kMBgOXyyVnlUgkLS0tuSGiIpPJNDQ0qFSqtra2ZctkLhiGXb58mclkKhSKa9eukY2jo6MNDQ0QBFVWVv70009U/lPWv56enuvXr3s8Ho1G8/rrr2s0GrJchcPh3t5eAAAUCkV5eTl9ZRKLxVqtViwWk/9UqVRqtZrD4dBrkdcVv9/vcrmuXbs2OTlJLwxBEIZhfD4/kUj4/X4AAFKplN1ut1qtPB5Pq9VWVVVR6lJ1eDyegYEBAACefvrpRx55JFuKI5GIx+Mh6/zWrVvpLZufnx8dHc3WZJ/PNzY2lkql6LUAAGCxWBqNBgAAh8Pxyy+/rChfVFRUUlISDAYzmQyGYb29ve3t7aFQ6MCBAzU1NTD8p2fu3N+U/mcyGXLh9+/fv2XLltx2co0rKipYLBaNTYlEwmq1mkymmZkZuVz+0EMPud3uL7/8sru7e0V/uFzuM888AwCA+x7JZJJefteuXTiOx+PxRCKxsLBw9epVh8OxdevW2traysrKrNv/3/M5UPrP5XJJPyUSSe6lGkGQ6elpAAB2794NQZTqKIq6XK6Wlha3261QKE6cOPHyyy8LBILbt2+3trauGFIEQRQKxf79+zEMc7lcw8PD9PISiQTDMAiC7t7jypUrs7Ozhw8ffvLJJwsLC2kUKR1gsVgEQfB4vKmpKRAEyUaCIBAE8fv9TCZTLBZn25dAEITX6/38889v3rwpEAj0ev2LL76o1+tfeOEF8ky+fPlyJBKhd6moqEin08EwPDQ01NfXRy+cTqfJYnTnzh2TyTQ5OQnD8DfffFNaWkqvSOk/DMNCoRBFUYvFguM42UgmPwRBEolkdnaWSjccDpvN5itXrhQUFOh0urq6Oi6XW1ZWptfrjx496vf7zWbz119/nR12ecsgqKamhsPheDye/AK+BBRF9+7dS347fPXVV5s3b85kMouLi1QRysL48MMPl+1Ip9MTExNOp3N6ejocDsdisampqYGBAZPJ5Ha7S0tL9+3bR148l5BMJtvb2z/++ONYLHbo0KG3335boVAAAACCIJfL5XA4Q0NDIyMjwWBQIBDs2rWLxjg+n3/jxg2fz4cgyMMPPywQCKgkYRgeGRm5detW6h579+799NNPlUrlyv+7R3Oofvfdd5WVlWQi7Nu3T6VS8fl8BEEAABAKhZcuXVpW6+bNmxUVFTAMV1VV5V+QQqHQhQsXSkpK2Gz2kSNHHA4H/dne3NwsEol27tx57tw5esnW1laZTEZunDNnzkQiEXp5Esr4gyAol8sPHz5cXFxMEEQqlUIQRCgUHjx4MBqN+v1+jUazZ88ecjmyjI2Nvf/++06nc8eOHW+88cZLL720JAPZbLZIJMIw7M6dO4FAIBKJHDt2jCY8LBaro6NjfHycwWDU1dXRSIIg6HA4gsGgTqd75ZVXaMrT/eXC3Nycy+WyWCydnZ3RaJQgCLPZ/NRTT33//ffkjTAXi8WCIAiPx2tqaqJ620BR9Ndff21qauLz+W+99daKITIYDJs3b5ZKpW63m0YslUqdP3/++PHj/f39VFPn8yefaVYhl8XFRZfLtbCwkP/9FwwGT5w48c4779BfclEU9fv9PT09S15jlqWlpUWpVHK53Obm5hWF75e1f/9Yc/r7++vr65lM5pEjR9Z88P/A+//u3bvVajUAAD/++KPP58vtuu8dngeUOxbJ3xxxTZienu7r64vH4ziOIwhSXl5eUVGB47jVas3KkKb+BYPBHODcsbK/1/2PYux2u9lsVqlUer1eLpeXlJRs27YNgiCDwZCVIQjir5n6JxVyG6xS7V/j3LlzbDZ7+/btBoPhH53o/+u3JIuWXZH8TFv3NPn7/JE/uR8562rSv8ofD8wbyu0s/4Hz7x/lgf8bm/8FAAD//1XENS1PhbtSAAAAAElFTkSuQmCC'
    }
  }
}
[09/02/2023 08:03:14]   [EufySecurity-2.2.7]    DEBUG   [api.ts:355]    Login - Captcha verification received {
  captchaId: 'ec794b48-4a56-4ec8-8ff2-8371e8a6b161',
  item: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFUAAAArCAIAAACGv1O8AAAJeElEQVR4nOyabUxb1RvA7729vS0bZSusa9qydthmHaXMtWSZS+fL3JyJlCrTBEh1xqQm6owRQ3S6fXDxi2kWErdsxg8TTaRrpguKiWvWbmsmC9ICBYowQGnLW2uhxdKWvt2Xf7L7T62Ue2GKEsN+n7pznuec5znPc55z7hkwQRDABgZabwPWmQf+b2we+L+xeeD/xuaB/xsbeL0NWAMwDLPZbIlE4rHHHisuLr4/ZWJNwXF88R70YvF43GazdXR0rMmkP//8886dO2UymdPpRFGUyrBMJpPfvpb5TxDEb7/9ZjQa29ra5ubmqMQSiURra+ubb77Z2NgYDof/5qQ4jqdSKa/XOzU15fV6GQzGsmIzMzMnT540Go3xeHyp0WtFMpk8f/48CIJsNvvdd98NhUL5MiiK3rhxQyaTQRBUVVWVTqeXHWrZWFHR1dVVVFTE4/HOnj2b34vjeCAQOH78OAAAO3bsCAQCub1r6T+O43fv3pVIJCAIQhBkNBoTicQSmUAgcOjQIQAAuFyu3W7HcTx/kOHh4Vu3bo2Pj2MYtpp57Xa7Wq3esmXLBx98kN87Nzd38eJFGIYLCwvr6+uX7M013v8EQbjdbrlcDkFQYWHh1atXcyOMoujp06c3bdoEQdDZs2djsVi++uDg4LFjxzgczsmTJ/OXb1m6u7uPHj3KYDDee++9/DEtFsvBgwcZDEZ1dXV3d/eS3tXu/0QiMTg42NnZOTw8HIvFaCSVSuXFixfLysoWFxdPnz59+/btdDpNdtlsNrPZnEwmq6urn3/++U2bNlHNBUHQ77//DsOrOp6kUil5CsTj8fn5+dyucDj8ww8/uFwumUxWX1+/Z8+epcqrWeDr16+/+uqrNTU1jz766IEDB+rq6kwmUygUys/eLBcuXBCLxRAEPf744x0dHalUanJyUqfTsVgskUhksVhSqRSVrtPp/OSTT1wu1+qrgFarRRBEq9VOTEzktre3tyuVShAEm5qaPB5PviKd/ziOR6NRo9EoEomYTCaLxZJKpaWlpTAMFxcXNzQ0eL1eqi2aTqdPnTolFAohCKqtre3s7Pzoo494PB6DwTh16lQwGKSZ976KH2lnY2MjCIJisXhhYSHbjqJobW1tQUEBj8fr7+/PDXk28HT+z87ONjc3wzCMIIharT5z5sylezz77LMAAGzbtu3bb7+lUZ+fn29sbNy+fTuTyXzuueekUimDwXjiiSe6urqoTulcRkZGbDYbTZpkicVin332GVnefT4f2ZhOp61Wa0FBAZPJfO2116iyns7/tra2srIyFotVXV1tt9vj8ThBENFo9IsvvgAAoLy83Gaz0Vvm8/kMBgOXyyVnlUgkLS0tuSGiIpPJNDQ0qFSqtra2ZctkLhiGXb58mclkKhSKa9eukY2jo6MNDQ0QBFVWVv70009U/lPWv56enuvXr3s8Ho1G8/rrr2s0GrJchcPh3t5eAAAUCkV5eTl9ZRKLxVqtViwWk/9UqVRqtZrD4dBrkdcVv9/vcrmuXbs2OTlJLwxBEIZhfD4/kUj4/X4AAFKplN1ut1qtPB5Pq9VWVVVR6lJ1eDyegYEBAACefvrpRx55JFuKI5GIx+Mh6/zWrVvpLZufnx8dHc3WZJ/PNzY2lkql6LUAAGCxWBqNBgAAh8Pxyy+/rChfVFRUUlISDAYzmQyGYb29ve3t7aFQ6MCBAzU1NTD8p2fu3N+U/mcyGXLh9+/fv2XLltx2co0rKipYLBaNTYlEwmq1mkymmZkZuVz+0EMPud3uL7/8sru7e0V/uFzuM888AwCA+x7JZJJefteuXTiOx+PxRCKxsLBw9epVh8OxdevW2traysrKrNv/3/M5UPrP5XJJPyUSSe6lGkGQ6elpAAB2794NQZTqKIq6XK6Wlha3261QKE6cOPHyyy8LBILbt2+3trauGFIEQRQKxf79+zEMc7lcw8PD9PISiQTDMAiC7t7jypUrs7Ozhw8ffvLJJwsLC2kUKR1gsVgEQfB4vKmpKRAEyUaCIBAE8fv9TCZTLBZn25dAEITX6/38889v3rwpEAj0ev2LL76o1+tfeOEF8ky+fPlyJBKhd6moqEin08EwPDQ01NfXRy+cTqfJYnTnzh2TyTQ5OQnD8DfffFNaWkqvSOk/DMNCoRBFUYvFguM42UgmPwRBEolkdnaWSjccDpvN5itXrhQUFOh0urq6Oi6XW1ZWptfrjx496vf7zWbz119/nR12ecsgqKamhsPheDye/AK+BBRF9+7dS347fPXVV5s3b85kMouLi1QRysL48MMPl+1Ip9MTExNOp3N6ejocDsdisampqYGBAZPJ5Ha7S0tL9+3bR148l5BMJtvb2z/++ONYLHbo0KG3335boVAAAACCIJfL5XA4Q0NDIyMjwWBQIBDs2rWLxjg+n3/jxg2fz4cgyMMPPywQCKgkYRgeGRm5detW6h579+799NNPlUrlyv+7R3Oofvfdd5WVlWQi7Nu3T6VS8fl8BEEAABAKhZcuXVpW6+bNmxUVFTAMV1VV5V+QQqHQhQsXSkpK2Gz2kSNHHA4H/dne3NwsEol27tx57tw5esnW1laZTEZunDNnzkQiEXp5Esr4gyAol8sPHz5cXFxMEEQqlUIQRCgUHjx4MBqN+v1+jUazZ88ecjmyjI2Nvf/++06nc8eOHW+88cZLL720JAPZbLZIJMIw7M6dO4FAIBKJHDt2jCY8LBaro6NjfHycwWDU1dXRSIIg6HA4gsGgTqd75ZVXaMrT/eXC3Nycy+WyWCydnZ3RaJQgCLPZ/NRTT33//ffkjTAXi8WCIAiPx2tqaqJ620BR9Ndff21qauLz+W+99daKITIYDJs3b5ZKpW63m0YslUqdP3/++PHj/f39VFPn8yefaVYhl8XFRZfLtbCwkP/9FwwGT5w48c4779BfclEU9fv9PT09S15jlqWlpUWpVHK53Obm5hWF75e1f/9Yc/r7++vr65lM5pEjR9Z88P/A+//u3bvVajUAAD/++KPP58vtuu8dngeUOxbJ3xxxTZienu7r64vH4ziOIwhSXl5eUVGB47jVas3KkKb+BYPBHODcsbK/1/2PYux2u9lsVqlUer1eLpeXlJRs27YNgiCDwZCVIQjir5n6JxVyG6xS7V/j3LlzbDZ7+/btBoPhH53o/+u3JIuWXZH8TFv3NPn7/JE/uR8562rSv8ofD8wbyu0s/4Hz7x/lgf8bm/8FAAD//1XENS1PhbtSAAAAAElFTkSuQmCC'
}
[09/02/2023 08:03:14]   [EufySecurity-2.2.7]    DEBUG   [platform.ts:233]       EufyClient connected false
[09/02/2023 08:03:14]   [EufySecurity-2.2.7]    ERROR   [platform.ts:239]       Not connected can't continue!

**Comment by lenoxys** [comment]
Yeah in that case unfortunately you will need to create a new account looks like the old one will be permanently asked for captcha :(

**Comment by frozenfractals** [comment]
@lenoxys Apologies for lack of response on my end. I was away, but was able to update to the latest version yesterday and all is well using the dedicated admin account.

**Comment by lenoxys** [comment]
Ha cool fix is working properly so I've 2 positive feedback I'm glad it's works !
