### ISSUE TITLE
Contact Sensor Status

### ISSUE THREAD

**Issue by federicodigiacomo** [homebridge-eufy-security/plugin#394]
### What happened?

Hello everyone, when I open contact sensor “Porta DX Salone” it all ok but after a second it is wrongly closed. Can you help me? In this condition, on HomeKit I see the sensor that both opens and automatically closes. Before the homebase firmware update everything worked.

![IMG_2900](https://github.com/homebridge-eufy-security/plugin/assets/47451973/6bc1a79a-e5de-4906-b998-a834bb588de3)

### Device Type

Contact Sensor (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
X
```

### config

```shell
X
```

**Comment by lenoxys** [comment]
Try 2.2.6

**Comment by federicodigiacomo** [comment]
> Try 2.2.7

not worked with 2.2.7

**Comment by lenoxys** [comment]
can you provide me with log ? I do have contact sensor on my setup and it works. I will need to check what's wrong with yours.

**Comment by federicodigiacomo** [comment]
> can you provide me with log ? I do have contact sensor on my setup and it works. I will need to check what's wrong with yours.
> 
> 
> 
> https://github.com/homebridge-eufy-security/plugin/wiki/Basic-Troubleshooting

How to?

**Comment by federicodigiacomo** [comment]
> > can you provide me with log ? I do have contact sensor on my setup and it works. I will need to check what's wrong with yours.
> > 
> > 
> > 
> > https://github.com/homebridge-eufy-security/plugin/wiki/Basic-Troubleshooting
> 
> How to?

What is the firmware version of your homebase? My firmware is 3.3.0.1h. I have another homebase with firmware 3.2.9.5h and everything works

**Comment by lenoxys** [comment]
hum I'm using 3.2.9.5h as well. You just need to follow the instructions and provide log file by downloading it using the button in plugin settings.

**Comment by aigkwin** [comment]
> hum I'm using 3.2.9.5h as well. You just need to follow the instructions and provide log file by downloading it using the button in plugin settings.

I have the same problem since the Homebase was updated to 3.3.0.1h. All contact sensors status change to open and then close instantly. I have attached Homebridge logs for your attention. 
[Unknown.zip](https://github.com/homebridge-eufy-security/plugin/files/12507950/Unknown.zip)

**Comment by federicodigiacomo** [comment]
> I might need an access. Can you ping me on discord ?
> 
> 
> 
> https://discord.com/channels/432663330281226270/876907345962229791
> 
> 
> 
> By the way, do you see this behaviour as well on Eufy App 

Everything works fine in the Eufy app

**Comment by lenoxys** [comment]
Is 3.3.0.1h on Homebase 3 or Homebase 2 ?

**Comment by lenoxys** [comment]
as per log I can see it's HB2

**Comment by federicodigiacomo** [comment]
> Is 3.3.0.1h on Homebase 3 or Homebase 2 ?

Homebase 2

**Comment by lenoxys** [comment]
this is an identified bug and fixed is waiting for approval : 
https://github.com/bropat/eufy-security-client/pull/371

**Comment by federicodigiacomo** [comment]
With 2.2.12 work fine, thank you

**Comment by lenoxys** [comment]
Really ? Because I'm waiting the fix from the lib so nothing has been done yet

**Comment by federicodigiacomo** [comment]
It's All ok

**Comment by lenoxys** [comment]
On I'm closing the case so
