### ISSUE TITLE
[Bug]: 2.2.6+ Lose Indoor Pan & Tilt Motions

### ISSUE THREAD

**Issue by gmogoody** [homebridge-eufy-security/plugin#400]
### What happened?

I was on 2.2.5. All my cameras I have showing as motions with accessory buttons or switches for spotlight or disable/enable. Once I upgraded over 2.2.5 all my indoor pan and tilt cameras were removed from HomeKit. 

### Device Type

Indoor Camera (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
Reverted to 2.2.5 just to gain all functionality back
```

### config

```shell
Reverted to 2.2.5 just to gain all functionality back
```

**Comment by lenoxys** [comment]
This is due by having them unbridge by default you have to add each of them independently into the home app

**Comment by gmogoody** [comment]
> This is due by having them unbridge by default you have to add each of them independently into the home app

@lenoxys , so you are saying just by updating you have modified the code where it has been working fine for over 2 + years that I now need to add each device independently in HK where prior anything added to the plugin bridge would automatically show up?

**Comment by gmogoody** [comment]
Ahh I see you did make this default. 

“ Make unbridge a global setting instead of per camera basis, and make …
…it enabled by default.”

I appreciate the work you put in. Is it possible to put a warning up on such a huge change next time? I lost about 20 automations as the update just removed the devices. I rolled back and set everything up again. 

is there a way to upgrade without having to add back to HK again?

**Comment by lenoxys** [comment]
It will be one time change. I will make sure that such a bug change will be on major release but got too many issue link by the fact people follow default settings and unbridge is one of them. Sorry for the disruption !

**Comment by gmogoody** [comment]
Thanks for confirming this change was done intentionally as I didn’t see it called out when updating. I’m in SW development and completely understand your position. Also the fact you do this in your spare time.
