### ISSUE TITLE
[Bug]: settings UI not loading

### ISSUE THREAD

**Issue by dan1916** [homebridge-eufy-security/plugin#412]
### What happened?

Hello,

I am on the latest homebridge on Ubuntu and was using the Eufy plugin for a while now. I just noticed that the settings UI for this plugin no longer loads. I tried installing an older version, also tried on a completely separate system with a new Homebridge but it still does not load.  I have Eufy plugin v2.2.14.

Can someone please help?

### Device Type

Station (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Ubuntu 18.04+ (Supported)

### Relevant log output

```shell
None. The settings UI simple shows empty box.
```

### config

```shell
None
```

**Comment by lenoxys** [comment]
hello, can you try using incognito browser mode ? Which browser are you using ?

**Comment by dan1916** [comment]
okay Incognito worked. Strange. Not sure what got messed up with the cookies. I tried in two separate machines that I have homebridge on.

**Comment by lenoxys** [comment]
yeah, some times cache aren't refresh correctly especially when I'm updating the UI which was the case these last weeks. Thanks for your feedback, you should be fine by clearing the browser cache. I'm closing the issue.
