### ISSUE TITLE
[Bug]: Floodlight switch switches also camera on/off

### ISSUE THREAD

**Issue by cixio** [homebridge-eufy-security/plugin#420]
### What happened?

After https://github.com/homebridge-eufy-security/plugin/pull/417/commits/72759f2c6377325f352d57be383d2351c0cb24a3 the Floodlight light switch also switches the camera (stream/off according to the light).

Solution: https://github.com/homebridge-eufy-security/plugin/commit/6901ed962482da50adcbe821c5e1b7b764fc057e#diff-f6e21796333e51106571b2ca60b5a5bdf135748d9be9d5f8e787d211cf12e93fL389 - i dont know why but in this very old version the light switch does not updates the characteristic. 

### Device Type

Floodlight (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
-
```

### config

```shell
-
```

**Comment by lenoxys** [comment]
hello @cixio and @julien94800, yeah, sorry for the miss, I think I found the issue but I need to be at home in order to check.

**Comment by lenoxys** [comment]
hello, try 2.2.19

**Comment by cixio** [comment]
Thanks! Works great.
