### ISSUE TITLE
[Bug]: Video streaming resolution never higher than 640x480

### ISSUE THREAD

**Issue by thieren** [homebridge-eufy-security/plugin#46]
### What happened?

As stated from Ichigo in Discord he is not able to stream video with a resolution higher than 640x480.
This was possible in an earlier version (according to him up until 1.1.1-beta36).

I'll try to figure out where the problem lies.

Excerpt from Discord:

> Ichigo:
> New Update looks great. Just one thing, ever since beta 136 from previous version, the video is unable to stream anything over 640p. Before it would do 720p on iphone and 1080p on ipads

### Device Type

other (UnSupported)

### Plugin Version

other (UnSupported)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

other (UnSupported)

### Operating System

Other (UnSupported)

### Relevant log output

```shell
none for now
```

**Comment by lenoxys** [comment]
need debug log output for that

**Comment by thieren** [comment]
If you're using the latest beta 2.0.1-beta7 this issue should be fixed, if you're enabling the new snapshot handling.
I'm still not quite sure why, but will keep looking into it.

**Comment by AntlerDM** [comment]
Just upgraded to 2.0.1 (release) and video is still 640 x 480.

I also completely uninstalled the plugin and configuration, but it is still only 640 x 480.

**Comment by thieren** [comment]
Hi @AntlerDM 

Please use beta 2.1.0 with the new snapshot handling enabled.

We had to add the 2.0.1 release as patch and switched the beta to 2.1.0.

**Comment by thieren** [comment]
This issue is fixed in 2.1.0-beta.14

**Comment by thieren** [comment]
Is fixed with release of 2.1.0
