### ISSUE TITLE
[Bug]: S220 Solocam does not stream to home-app

### ISSUE THREAD

**Issue by reqed** [homebridge-eufy-security/plugin#475]
### What happened?

I cannot view any livestream in the Home app. 
After a view minutes "No response" appears and nothing happens.

Sometimes a snapshot from a view days ago appears, but in front of this is a banner with „Camera is not responding“.
![IMG_8905](https://github.com/homebridge-eufy-security/plugin/assets/64812134/5d0abaa9-b64a-4303-80f0-f9f9fb96dcbf)

### Device Type

Station (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[11/24/2023, 12:03:59]  [EufySecurity]  INFO    Carport station livestream (P2P session) for Carport has started.
[11/24/2023, 12:03:59]  [EufySecurity]  INFO    Carport station livestream for Carport has stopped.
```

### config

```shell
{
    "platform": "EufySecurity",
    "ignoreStations": [],
    "ignoreDevices": [],
    "cleanCache": true,
    "username": "****",
    "password": "****",
    "country": "DE",
    "deviceName": "",
    "_bridge": {
        "username": "0E:C0:AB:19:4B:3A",
        "port": 38360
    }
}
```

**Comment by mistert871** [comment]
I have the exact same issue.

**Comment by reqed** [comment]
Now works with the newest v2.3.9 - hksv Version
