### ISSUE TITLE
[Bug]: version 2.0 makes Doorbell and Motion buttons useless

### ISSUE THREAD

**Issue by DaveM8686** [homebridge-eufy-security/plugin#48]
### What happened?

Since upgrading to 2.0, the buttons that normally enable/disable motion and the camera in Home now do nothing. They’re still there but flipping them doesn’t do a thing in the Eufy app, so they are useless now. 

### Device Type

Doorbell (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Docker (UnSupported)

### Relevant log output

```shell
Not sure what is relevant here. The switch does nothing.
```

**Comment by DaveM8686** [comment]
> 
> 
> Did you check this [Common Issues](https://github.com/homebridge-eufy-security/plugin/wiki/Common-Issues) pages ?
> 
> 
> 

Yes, it doesn't answer my question at all.

**Comment by lenoxys** [comment]
Hello, I've just tested on my setup, button works fine. I've doorbell too.

**Comment by DaveM8686** [comment]
> Hello, I've just tested on my setup, button works fine. I've doorbell too.

Are you on 2.0? Battery doorbell mini? Do your settings look like this?
![image](https://user-images.githubusercontent.com/75352454/170894048-74b9bad3-26a8-4457-8d01-73948c079e06.jpeg)

**Comment by thieren** [comment]
Hey @DaveM8686 

Thx for your feedback!

This should be fixed in 2.0.1-beta12

Please reopen if the issue still persists.
