### ISSUE TITLE
T8170 S340 looking to get support homebridge-eufy-security v2.2.21

### ISSUE THREAD

**Issue by beetle1967** [homebridge-eufy-security/plugin#482]
### Describe the solution you'd like

Looking to get the T8170 S340 new camera set up in Homebridge. I have the s40 camera up and running on the S380 home base and I am running  homebridge-eufy-security v2.2.21. Tried it today and it does not recognize as a camera<img width="1545" alt="Screen Shot 2023-12-02 at 9 31 45 AM" src="https://github.com/homebridge-eufy-security/plugin/assets/113145336/2cc9475b-ceb4-46e9-879e-73a704995372">

**Comment by town3r** [comment]
Looks like it was recently added to the main eufy-security-client so hopefully it will come to the plugin soon.

https://github.com/bropat/eufy-security-client/pull/410

**Comment by tomer1985** [comment]
any update about it? I also have s40 and I can't get it to work :(

**Comment by town3r** [comment]
A new beta should be coming this week that should add support. :)

**Comment by tomer1985** [comment]
Did it happened?On 4 Mar 2024, at 23:51, Ben Towne ***@***.***> wrote:﻿
A new beta should be coming this week that should add support. :)

**Comment by town3r** [comment]
No new beta yet.

Guessing the dev has been busy w/ their real job & life stuff.

Hoping they have some free time this weekend to throw a beta version using v3.0.0 together for the community. 🤞🏼

**Comment by town3r** [comment]
Good news tho is it does look like they were making some changes to the hksv version 4 days ago. 🥳

![image](https://github.com/homebridge-eufy-security/plugin/assets/12396203/22607907-8511-4c26-8541-8d17e9820474)

**Comment by beetle1967** [comment]
It works got my new S340 working with my older S230 (S40) and both are on the Home base 3. I am using 2.3.13 Version. Thanks for the new updates...

**Comment by Justincrdibl** [comment]
> It works got my new S340 working with my older S230 (S40) and both are on the Home base 3. I am using 2.3.13 Version. Thanks for the new updates...

I dont have the homebase, is this a requirement?

I had them showing as cameras but they wouldnt work, but now they are switches and I cant change it. Ive used 2.3.13 and 2.3.14 same issue

**Comment by beetle1967** [comment]
No it should not be a issue I had the S230 (s40) running for a long time without the Homebase 3 on Homebridge. Both the s340 and S40 work without the Homebase 3. Do you have the S340 camera. 
<img width="1545" alt="Screen Shot 2024-03-22 at 5 24 39 PM" src="https://github.com/homebridge-eufy-security/plugin/assets/113145336/7faeaf8a-d6a4-4a7d-b7bd-9f6cb080655b">

**Comment by Justincrdibl** [comment]
Yes I just got a couple s340 cameras. I havent used homebridge in a long time so maybe I made a mistake. Also my setup doesnt have the images like yours. 
Nothing happens in homekit unless I use the child bridge but then I still only get switches. Im using 2.3.14 now, Ive also noticed that even tho I have node v 20.11.0 its showing 20.11.1 in the homebridge ui. I deleted 2.11.1 altogethrr and have 20.11.0 confrimed I use. 

![Screenshot 2024-03-22 at 3 42 36 PM](https://github.com/homebridge-eufy-security/plugin/assets/89617888/2d909aea-3dfc-4a8b-95e4-4803058e38a1)

**Comment by beetle1967** [comment]
Did you try do Reload and signing into Eufy again. This will load all your camera's but also make sure you have another ID from the original set on the camera's. So in other words you have to share a Id with another person and sign in with that. Here is a good video. [ ](https://www.youtube.com/watch?v=n7YjKEVnFvE)

**Comment by Justincrdibl** [comment]
I just reinstalled homebridge and Eufy plugin and the UI is different, shows the pics now. Ive done that a few times but only changed this time. 
I am using a secondary account I created in Eufy yes.

So now I have no child bridge but the cameras show up in homekit as 2 icons per camera, neither are cameras, looks like switches still 

Do I need do make a chil bridge for it to work?

**Comment by beetle1967** [comment]
Yes I am running it as a child bridge  here is a video that help me a lot different camera but help me a lot. [https://www.youtube.com/watch?v=n7YjKEVnFvE](url)

**Comment by Justincrdibl** [comment]
Thank you! iIll take a look

**Comment by beetle1967** [comment]
<img width="785" alt="Screen Shot 2024-03-22 at 6 32 50 PM" src="https://github.com/homebridge-eufy-security/plugin/assets/113145336/de29c398-6263-41d9-86f4-22c83d09ad1a">

**Comment by beetle1967** [comment]
v2.3.13 also back up to this version .14 did not work for me.

**Comment by Justincrdibl** [comment]
Thank you! looks like I have them working!
Only issues I see now is no snap shots in home app and im not sure if we are able to control the camera movement but I dont see a way to do so.

**Comment by Justincrdibl** [comment]
its also very very slow to load. Ive read that most people have seen it load quite quickly. Im gonna have to keep messing with it I guess, its not functional as it unfortunately

**Comment by beetle1967** [comment]
![Uploading Screen Shot 2024-03-22 at 7.15.07 PM.png…]()

**Comment by beetle1967** [comment]
iCloud will give you a old picture

**Comment by beetle1967** [comment]
Here is my set up and yes it can be slow 
<img width="770" alt="Screen Shot 2024-03-22 at 7 15 07 PM" src="https://github.com/homebridge-eufy-security/plugin/assets/113145336/fadebc86-362f-4f4c-83cc-d0476b5dede7">

**Comment by beetle1967** [comment]
I am running a Raspberry Pi 3 Model B for Homebridge maybe is 
my speed problem also...
