### ISSUE TITLE
[enhancement]: Support for Eufy Video Doorbell Dual

### ISSUE THREAD

**Issue by lenoxys** [homebridge-eufy-security/plugin#5]
### Describe the solution you'd like

Hello, first of all a big thank you for your great work. The plugin is really great and works without any problems. But I have one big request. I bought the Dual Doorbell from Dufy. Unfortunately, this is not yet supported by the plugin. It is marked as "undefined" under Type and is not included. A support would be really great.
Thanks, Enrico

https://github.com/samemory/homebridge-eufy-security/issues/383

**Comment by lenoxys** [comment]
watchers : @bambam1979, @jbh8063, @bezibaerchen

**Comment by thieren** [comment]
I think this is resolved. Closing.
