### ISSUE TITLE
[enhancement]: Adding EufyCam E330 (Professional)

### ISSUE THREAD

**Issue by GFlik** [homebridge-eufy-security/plugin#510]
### Describe the solution you'd like

Hello, thank you for your work on this plugin. I never thought I would be able to add any Eufy products to anything but your plugin made it possible! I am however, having an issue adding my E330 Professional cameras. I'm assuming this is because these are new products and wanted to see if it was possible to get those added? 

The camera does show up in the plugin config but the only option I have is to ignore. I'm also getting the following in my Hombridge logs:

[EufySecurity]  WARN    This accessory is not compatible with HomeBridge Eufy Security plugin: Front Door Type: 24

I'm using Homebase 3. If there is any other information I can provide, please let me know and thank you again for your work!

**Comment by kirkules66** [comment]
Road Map link goes to 404 Not Found. Can you post proper link? Or let us know if the E series cameras and doorbell on the road map? Timing?  Thaks for all your great work.

**Comment by debug36** [comment]
Eufy E330 can be used with plugin homebridge-eufy-security v2.3.30 by lenoxys. So far this is the only version that I can get to function. One the cameras are connected you need to go into the advanced video config for each E330 cam and set the config to performance. After doing this I have been able to stream all of my E330 cameras on Homekit. 
Let me know if this works for you @GFlik

**Comment by GFlik** [comment]
Yes, sorry I should have closed this issue, these have been working for me for a couple months now. Thanks!
