### ISSUE TITLE
[Bug]: Snapshot Unavailable Device Not Supported

### ISSUE THREAD

**Issue by HenryGelderbloem** [homebridge-eufy-security/plugin#513]
### What happened?

I downgraded from the HomeKit Secure Video version do to issues with HomePod chimes not working. I removed all accessories from the Homebridge cache and removed the doorbell from the Home app before readding it again and now I get "Snapshot Unavailable Device Not Supported". The video stream works perfectly and the eufy app gets snapshots just fine.

I am running NodeJS version 20.11.0 which the form suggests may be unsupported?

### Device Type

Doorbell (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

other (UnSupported)

### Operating System

Debian 10+ (Supported)

### Relevant log output

```shell
[02/15/2024 09:26:44]   [EufySecurity-2.2.21]   DEBUG   [streamingDelegate.ts:169]      handleSnapshotRequest
[02/15/2024 09:26:44]   [EufySecurity-2.2.21]   DEBUG   [streamingDelegate.ts:172]      Snapshot requested: 1280 x 720 Doorbell undefined
[02/15/2024 09:26:45]   [EufySecurity-2.2.21]   DEBUG   [streamingDelegate.ts:176]      snapshot byte lenght: 26696
```

### config

```shell
{
    "enableDetailedLogging": true,
    "CameraMaxLivestreamDuration": 90,
    "pollingIntervalMinutes": 10,
    "hkHome": 1,
    "hkAway": 0,
    "hkNight": 3,
    "hkOff": 63,
    "ignoreStations": [],
    "ignoreDevices": [
        "T8113N1320434686",
        "T8113N1320434FDE",
        "T8113N13204354E4",
        "T8113N13204351AC"
    ],
    "country": "GB",
    "cameras": [
        {
            "serialNumber": "T8900P002039251A",
            "rtsp": false,
            "talkback": false
        },
        {
            "serialNumber": "T8900P0020393C18",
            "rtsp": false,
            "talkback": false
        },
        {
            "serialNumber": "T8113N1320434686",
            "rtsp": false
        },
        {
            "serialNumber": "T8113N1320434FDE",
            "rtsp": false
        },
        {
            "serialNumber": "T8113N13204354E4",
            "rtsp": false
        },
        {
            "serialNumber": "T8113N13204351AC",
            "rtsp": false
        },
        {
            "serialNumber": "T8210P0020443DA7",
            "rtsp": false,
            "enableCamera": true,
            "videoConfig": {
                "audio": true,
                "vcodec": "copy",
                "useSeparateProcesses": true,
                "audioSampleRate": 0
            },
            "talkback": true,
            "snapshotHandlingMethod": 3,
            "immediateRingNotificationWithoutSnapshot": true,
            "delayCameraSnapshot": true,
            "refreshSnapshotIntervalMinutes": 0,
            "hsv": false,
            "hsvRecordingDuration": 90,
            "hsvConfig": {},
            "useCachedLocalLivestream": true,
            "enableButton": false,
            "motionButton": false,
            "indoorChimeButton": true
        }
    ],
    "cleanCache": true,
    "unbridge": true,
    "ignoreMultipleDevicesWarning": false,
    "syncStationModes": false,
    "username": "",
    "password": "",
    "deviceName": "Homebridge",
    "platform": "EufySecurity",
    "_bridge": {
        "username": "0E:77:C8:C3:1C:1B",
        "port": 44281
    }
}
```

**Comment by HenryGelderbloem** [comment]
I checked the Common Issues. This isn't listed.

**Comment by Jcccrr** [comment]
Hey @HenryGelderbloem, I'm seeing the same problem with my wireless doorbell 2k. Have you managed to fix it?

**Comment by HenryGelderbloem** [comment]
Unfortunately not. Still got the same issue.

**Comment by Jcccrr** [comment]
@HenryGelderbloem These configs are working fine for me now:
`{
            "serialNumber": "",
            "rtsp": false,
            "enableCamera": true,
            "videoConfig": {
                "audio": true,
                "debug": true,
                "vcodec": "copy",
                "useSeparateProcesses": true
            },
            "talkback": true,
            "snapshotHandlingMethod": 3,
            "immediateRingNotificationWithoutSnapshot": false,
            "delayCameraSnapshot": false,
            "refreshSnapshotIntervalMinutes": 5,
            "useCachedLocalLivestream": false,
            "enableButton": false,
            "motionButton": false,
            "indoorChimeButton": false
        }`

**Comment by HenryGelderbloem** [comment]
That seems to work for me too! Thanks for sharing.

**Comment by vernong1992** [comment]
Necroposting here to confirm these settings worked for me on my Solocam S220 pairs, and restart Homebridge. 

Add what @Jcccrr's codeblock under  "cameras": [
                {
                }
]. 

> @HenryGelderbloem These configs are working fine for me now:
> 
> ```
>             "serialNumber": "",
>             "rtsp": false,
>             "enableCamera": true,
>             "videoConfig": {
>                 "audio": true,
>                 "debug": true,
>                 "vcodec": "copy",
>                 "useSeparateProcesses": true
>             },
>             "talkback": true,
>             "snapshotHandlingMethod": 3,
>             "immediateRingNotificationWithoutSnapshot": false,
>             "delayCameraSnapshot": false,
>             "refreshSnapshotIntervalMinutes": 5,
>             "useCachedLocalLivestream": false,
>             "enableButton": false,
>             "motionButton": false,
>             "indoorChimeButton": false
>         }```
> ```
