### ISSUE TITLE
[Bug]: Clearer statement about the Node LTS version is needed

### ISSUE THREAD

**Issue by DWLaurie** [homebridge-eufy-security/plugin#530]
### What happened?

I tried to put in a Wkik Change Request, it would not accept it.
Submitting it here for review.

Currently, under **Prerequisites** it states: (https://github.com/homebridge-eufy-security/plugin/wiki)

"_It is recommended to use the current LTS version of Node, currently v18._"

This is not a true statement, in that https://nodejs.org/en/download states that the current LTS is v20.11.1

We already know that v20.11.1 causes issues.
I was able to back-version to v20.11.0 to keep my installation working.

Point being - I feel we need to more clearly state the Requirement of the LTS version.
If it needs to state something like "the latest LTS version in the v18 branch" or something similar that would be acceptible.
But currently stating "_...use the current version of Node..._" [which is] "_...currently v18._ _" is confusing and contradictory.

### Device Type

Doorbell (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
Clearer statement about the Node LTS version is needed
```

### config

```shell
Clearer statement about the Node LTS version is needed
```

**Comment by lenoxys** [comment]
Is it better ?

> It is recommended to use the latest LTS version within the v20 branch of Node.js for optimal compatibility. Currently, this version is v20.11.0. Please note that using versions outside of this branch, including v20.11.1, may result in compatibility issues. We advise against using Node.js versions beyond v18.x.x until compatibility with the plugin has been confirmed. If you encounter any issues, consider reverting to the recommended LTS version within the v20 branch.

**Comment by DWLaurie** [comment]
THAT is way more than I anticipated, but that is awesome!
And also a faster than anticipated response! Thank you for both!!

**Comment by lenoxys** [comment]
this is done. thanks for your contribution!
