### ISSUE TITLE
[Bug]: missing state for "off" 

### ISSUE THREAD

**Issue by gianlucad3** [homebridge-eufy-security/plugin#538]
### What happened?

I have the global mapping "homekit off" set to "eufy disarmed". When disarming the alarm with the keypad the button "off" sets the station in the "off" state though, not disarmed. Since the off state is not recognized by homekit, in HK the alarm remains in the previous (alarmed) state. 

### Device Type

Station (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.7.x (Supported)

### NodeJS Version

v20 (Supported)

### Operating System

Ubuntu 22.04+ (Supported)

### Relevant log output

```shell
[04/07/2024, 11:51:44]  [EufySecurity]  ERROR   Eufy HomeBase handleSecuritySystemCurrentStateGets: Wrong return value
[04/07/2024, 11:51:44]  [EufySecurity]  ERROR   Eufy HomeBase handleSecuritySystemTargetStateGet: Wrong return value
```

### config

```shell
{
            "enableDetailedLogging": false,
            "CameraMaxLivestreamDuration": 30,
            "pollingIntervalMinutes": 10,
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "ignoreStations": [],
            "ignoreDevices": [
                "T8010P1320454127",
                "T8140P6121050951",
                "T8140P61210521C4"
            ],
            "country": "US",
            "cameras": [
                {
                    "serialNumber": "T8960P1023531041",
                    "rtsp": false,
                    "talkback": false
                },
                {
                    "serialNumber": "T8140P6121050951",
                    "rtsp": false
                },
                {
                    "serialNumber": "T8140P61210521C4",
                    "rtsp": false
                }
            ],
            "cleanCache": true,
            "unbridge": true,
            "platform": "EufySecurity",
            "username": 
            "password": 
            "stations": [
                {
                    "serialNumber": "T8010P13234107E7",
                    "manualTriggerModes": [
                        1
                    ]
                },
                {
                    "serialNumber": "T8010P1320454127",
                    "manualTriggerModes": [
                        1
                    ]
                }
            ],
            "_bridge": {
                "username": "0E:84:C8:B7:41:B8",
                "port": 45469
            }
        },
```

**Comment by gianlucad3** [comment]
I did but I didn't see anything related. Is this a known issue?

**Comment by lenoxys** [comment]
hello did you tried on 3.0.0?

**Comment by gianlucad3** [comment]
I didn't. is it the recommended version now? thank you!

**Comment by deus117** [comment]
Issue persists on 3.0.0 and 3.0.1, I upgraded from 2.2.20 where Eufy mode 'off' would show as disarmed in HomeKit (if that's any help..). I've reset the plugin and re-added accessories too.

**Comment by deus117** [comment]
The Off mode is created when you add the keypad but doesn't appear in the plugin under global settings > Change how each mode in the HomeKit security system is mapped to the modes in the Eufy App.

Home/Away keypad buttons to HK work fine. 
Have just seen there is an open enhancement #478

**Comment by lenoxys** [comment]
Can you provide log with debug enable  of the changing arming state so I can get the different IDs used?
