### ISSUE TITLE
HomeBase isn't visible in HomeKit anymore...

### ISSUE THREAD

**Issue by krausly1985** [homebridge-eufy-security/plugin#560]
Hello, unfortunately the security levels (present, away, night,...) can no longer be set in the home app recently. After I removed the HomeBase in Homekit, I completely reinstalled the plugin. Unfortunately, in the current version the HomeBase is no longer visible in Homekit. I have already downgraded to Node.js version 20.11.0. Does somebody has any idea? Thank you

**Comment by lenoxys** [comment]
Hello, 
which device are you using ?
Can you enable DEBUG and provide full logs ? 
https://github.com/homebridge-eufy-security/plugin/wiki/Basic-Troubleshooting

**Comment by krausly1985** [comment]
I'm using the HomeBase 2 and 4 eufyCam 2C Pro. I deactivated the cameras in the plugin because they are provided by the Eufy app. This all works well too. But the HomeBase is not displayed in HomeKit. 
[homebridge-eufy-security.log.txt](https://github.com/homebridge-eufy-security/plugin/files/15200021/homebridge-eufy-security.log.txt)

**Comment by lenoxys** [comment]
Looking at the error I think it's self explanatory : 

```
          #########################
          ######### ERROR #########
          #########################
          You're not using a guest admin account with this plugin! You must use a guest admin account!
          Please look here for more details: 
          https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
          #########################
```
