### ISSUE TITLE
[Question]: Node > 20.11.0

### ISSUE THREAD

**Issue by guitardoc** [homebridge-eufy-security/plugin#566]
### What happened?

Is it safe to update node to a version higher than 20.11.0 with the latest plugin update (version 3.3.0) to maintain full functionality?

### Device Type

Doorbell (Supported)

### Plugin Version

v3.0.x (Best Effort)

### HomeBridge Version

v1.7.x (Supported)

### NodeJS Version

v20 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
See above
```

### config

```shell
See above
```

**Comment by jzjz2000** [comment]
Same question? Can we upgrade to a newer version or please specify exactly what version we can safely use now .. My setup is a raspi 3,4 and 5 .. thanks for any info .. keep up the good work

**Comment by lenoxys** [comment]
20.11.0 is the latest version where livestream works. Above plugin can work but without livestream.
