### ISSUE TITLE
[Bug]: No devices shown in Homekit & arming/desarming not working

### ISSUE THREAD

**Issue by Y8rz8** [homebridge-eufy-security/plugin#567]
### What happened?

Hi there,
The plugin worked without any issues since months (years) - I use it with Homebase 2 and a motion detector.
Last week, Homebase was not able to change from Home mode to Away mode in HomeKit (always showing "arming").
I have decided to uninstall the plugin and delete devices from HomeKit.

I have installed the plugin again and configured it. Everything seems ok (meaning devices are shown in the setup screen). But no device in Accessories under Homebridge and no device in HomeKit. And no log at all.

Any idea ?

Thanks,
Patrice.

### Device Type

Station (Supported)

### Plugin Version

v3.0.x (Best Effort)

### HomeBridge Version

v1.7.x (Supported)

### NodeJS Version

v20 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
No log !
```

### config

```shell
{
    "username": "xxxx",
    "password": "xxxx",
    "country": "FR",
    "deviceName": "",
    "platform": "EufySecurity",
    "stations": [
        {
            "hkHome": 1,
            "hkAway": 0,
            "serialNumber": "T8010P2321472414",
            "hkOff": 63,
            "manualTriggerModes": [
                0,
                1
            ]
        }
    ]
}
```

**Comment by lenoxys** [comment]
Hello you can do a full reset in global settings

**Comment by Y8rz8** [comment]
Hello,
Just done it but still the same issue.

**Comment by Y8rz8** [comment]
Hi again, devices are now available in Homebridge and Homekit but arming/desarming still doesn't work. Is it due to node.js ?

**Comment by lenoxys** [comment]
CAN you enable debug mode and provide logs (see download button in plugin settings) while reproducing the error ?

**Comment by lenoxys** [comment]
Did you reboot ? And tried to reproduced the issue ?

**Comment by Y8rz8** [comment]
Yes I reboot to try but still zero bytes

**Comment by lenoxys** [comment]
Use the one embedded in plugin settings when you see the device list the yellow one on top.

**Comment by Y8rz8** [comment]
Ok - I have those files, please tell me what file you need ? I quickly search in the files but did not find something with a timestamp corresponding to the arming/dearming action I've done juste before generating the log files

<img width="574" alt="Screenshot 2024-05-08 at 20 25 05" src="https://github.com/homebridge-eufy-security/plugin/assets/68514930/3b2d3a9f-b01d-4730-ba89-9e682650cbb8">

**Comment by tekways** [comment]
I have the same problem, I need to stay in version 3.0.1, I can’t disarm ! (HomeBase)

**Comment by tekways** [comment]
I can switch to different modes, but I can't turn it off

**Comment by Y8rz8** [comment]
Hi there,
I have updated to the last node this morning (20.13.0) and everything is now working (I even get log files).
I close this issue since it's seems related more to node than to the plugin.
Thanks anyway for your support !
