### ISSUE TITLE
[enhancement]: eufy Security Indoor Cam C220

### ISSUE THREAD

**Issue by ryadkarar** [homebridge-eufy-security/plugin#576]
### Describe the solution you'd like

A new pan and tilt camera, the eufy Security Indoor Cam C220, has been released. It will replace the Indoor Cam E220
. Is it planned for this camera to be supported soon?

Here's the URL page, it's available worldwide: https://www.eufy.com/products/t8w11121?variant=43431741391034

Thank you!

**Comment by Arteleon** [comment]
Seems like bropat added the support to the 3.2.0 milestone. Is there any news? Do we get it when they get it?
