### ISSUE TITLE
[Bug]: Error in checkNodeJSVersionCompatibility() when calculate incompatible NodeJS version?

### ISSUE THREAD

**Issue by ivan-garcia-parras** [homebridge-eufy-security/plugin#597]
### What happened?

Hi,

I'm trying to use Homebridge v1.8.4 with NodeJS version v21.6.1 and plugin version v3.4.2.

According to the documentation of the RSA_PKCS1_PADDING incompatibility, this version of NodeJS should be exempt from the problem.

And older versions of the plugin work correctly, both stream and HKSV.

I think the problem lies in how the version incompatibility is calculated: https://github.com/homebridge-eufy-security/plugin/blob/master/src/plugin/platform.ts#L777

According to the semver string '^18.19.1 || ^20.11.1 || ^21.6.2', version "21.6.1", being higher than "18.19.1", is detected as an incompatible version.

I think the check string should be changed to something like the following line of code:

const incompatible = satisfies(nodeVersion, '>=18.19.1 <19.x || >=20.11.1 <21.x || >=21.6.2 <22');

Do I make myself clear?

Thanks!

### Device Type

Indoor Camera (Supported)

### Plugin Version

v3.0.x (Best Effort)

### HomeBridge Version

v1.7.x (Supported)

### NodeJS Version

v20 (Supported)

### Operating System

Ubuntu 22.04+ (Supported)

### Relevant log output

```shell
Error: Your current Node.js version....
```

### config

```shell
Not relevant for this bug.
```

**Comment by lenoxys** [comment]
Hello, cristal clear. I will implement FYI it won't blocked anymore but it will display a huge warning message.
