### ISSUE TITLE
[Bug]: Description texts invisble since v4.0.x

### ISSUE THREAD

**Issue by lhari84** [homebridge-eufy-security/plugin#605]
### What happened?

Hi, 
I noticed that almost all texts are invisible in plugin-settings since upgraded to v4.0.x. Also some other glitches like invisible device names in UI of plugin-settings. 
Seems to happen with Homebridge default UI Theme (dark mode) only. As soon as I switch to anohter Homebridge Theme (color), for example "Grey", problem is gone. 
Also note that the texts are always there, but probably same color as background in case of Homebridge default Theme, which makes them invisible. 

### Device Type

Indoor Camera (Supported)

### Plugin Version

other (UnSupported)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

other (UnSupported)

### Operating System

Ubuntu 22.04+ (Supported)

### Relevant log output

```shell
No specific error log in this case.
```

### config

```shell
Not relevant for this topic.
```

**Comment by gilluminate** [comment]
This appears to be a "dark mode" issue
