### ISSUE TITLE
[Bug]: Can't log back in after updating to 4.0.1

### ISSUE THREAD

**Issue by GreatBazunka-eng** [homebridge-eufy-security/plugin#608]
### What happened?

After I updated the plugin I can't log back in via the plugin and repopulate my Efuy devices

### Device Type

Station (Supported)

### Plugin Version

v3.0.x (Best Effort)

### HomeBridge Version

v1.7.x (Supported)

### NodeJS Version

v20 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
N/A
```

### config

```shell
N/A
```

**Comment by webdandy** [comment]
Same here, downgraded to 3.4.2 to get it working again.

**Comment by lenoxys** [comment]
hey, without very few information I'm not able to circle down. Any screenshot? Or Error logs displayed ?

**Comment by samteezy** [comment]
I'm seeing this issue as well. Nothing's in the plugin logs. In HB's terminal, I just see:
```
[8/8/2024, 4:43:05 PM] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /login
[8/8/2024, 4:43:05 PM] [Homebridge UI] [homebridge-eufy-security] [4.1.0]       INFO    [server.js:167] deleting persistent.json and accessories due to new login
[8/8/2024, 4:43:05 PM] [Homebridge UI] [homebridge-eufy-security] [4.1.0]       DEBUG   [server.js:177] init eufyClient
[8/8/2024, 4:43:05 PM] [Homebridge UI] [homebridge-eufy-security] [4.1.0]       DEBUG   [server.js:196] login with credentials
[8/8/2024, 4:43:05 PM] [Homebridge UI] [homebridge-eufy-security] [4.1.0]       DEBUG   [server.js:200] connected?: false
```

**Comment by GreatBazunka-eng** [comment]
So I got it working again. I am not sure about the technicalities, but it seemed like when I uninstalled the plugin and config from home bridge and then reinstalled it let me log back in. I had to setup all my automations again.

**Comment by webdandy** [comment]
I can remember that I saw the same logs like @samteezy in the HB logs

**Comment by mynameisbobwehadababyitsaboy** [comment]
I'm experiencing issues as well. Like @webdandy mentioned, rolling back to 3.4.2 let me log in... Unfortunately my cameras aren't working on that update, but my other devices are fine.

**Comment by ashfurrow** [comment]
I can confirm that after seeing this login issue on `4.0.1`, upgrading to `4.1.1` allowed login to Eufy again. Thanks for the plugin!

**Comment by webdandy** [comment]
Same here, working again with 4.1.1
Thanks for your great work ;-)

**Comment by mynameisbobwehadababyitsaboy** [comment]
Fresh install of 4.1.1 allows me to get back online. However if and when my Homebridge reboots, it fails to connect with Eufy again. Once I can reconnect I have to re-set up every Eufy device in Homekit, which is pretty crappy.

**Comment by webdandy** [comment]
As @mynameisbobwehadababyitsaboy mentioned I can confirm that with 4.1.1 all cams get disconnected after homebridge restart!

**Comment by mynameisbobwehadababyitsaboy** [comment]
> As @mynameisbobwehadababyitsaboy mentioned I can confirm that with 4.1.1 all cams get disconnected after homebridge restart!

So I have been doing a bit of troubleshooting, and I've come across something interesting. It seems like Eufy is partially blocking traffic from my home network when using the log-in feature (once logged in, it's fine).

Using the Eufy App for iOS (on my same network as Homebridge), if I log out, and try to log back in it's giving some generic network error. As soon as I disconnect from WiFi or connect to a VPN the error goes away and it lets me sign back in.

I ended up routing my Homebridge traffic through a VPN, and magically it let me log back into Eufy. It's been working since, even after reboots.

I'm curious to know, for other people experiencing login issues with Eufy in Homekit, try logging out and back in using the Eufy mobile app on your same network that Homebridge is on. Are you getting an error? or is it letting you log in?

**Comment by hrotsvith** [comment]
Same here! New/different IP address and I can login again but cams are disappearing soon after login.

**Comment by Perilax-De** [comment]
I have the same issues with 4.1.1. First I can’t log in, but after several trials it works. And after a second restart all cams get disconnected.

**Comment by GreatBazunka-eng** [comment]
I am having the exact same issues with 4.1.1

**Comment by mynameisbobwehadababyitsaboy** [comment]
2 days later and I’m still successfully logged in after running my homebridge through a VPN. So it does seem Eufy blocked off my IP address for logging in. 

Is it possible that the Eufy plugin for Homebridge was making too many suspicious api calls or something and now Eufy is cracking down?

**Comment by mynameisbobwehadababyitsaboy** [comment]
Fun while it lasted. Back to the issue happening, swapping VPN servers resolved it again. I think Eufy must hate the way this plugin talks to its servers, or something weird happening.
