### ISSUE TITLE
[enhancement]: Expose privacy mode as switch button

### ISSUE THREAD

**Issue by jp-lno** [homebridge-eufy-security/plugin#619]
### Describe the solution you'd like

Hi there,

I'm using the S350 camera with privacy mode and would like to automate privacy mode via Siri shortcut. 
Could you expose a new switch to trigger privacy mode via HK ? 
I will try to update the code but I am sure you will be faster than me. But if you are short of time, I will submit a PR.

I have checked in the eufy-security-client and the privacy mode is available. There are two CommandType : 

CommandType.CMD_INDOOR_ENABLE_PRIVACY_MODE_S350
CommandType.CMD_INDOOR_ENABLE_PRIVACY_MODE

Regards

**Comment by lenoxys** [comment]
Hello,

It's already exposed through enable device button.

as per bropat lib when device is disabled and it has privacy mode, it will be triggered :

See code : https://github.com/bropat/eufy-security-client/blob/develop/src/http/station.ts#L4569-L4607

**Comment by jp-lno** [comment]
🤦‍♂️ I had not noticed that the power button had been replaced by the privacy button on my S350. 
Thanks for your help. I can confirm that it works as expected 😅
