### ISSUE TITLE
[enhancement]: Alternate way to handle P2P snapshots

### ISSUE THREAD

**Issue by fullphat** [homebridge-eufy-security/plugin#64]
### What happened?

My T8420 Floodlight camera doesn't support RTSP so can be slow to retrieve the latest snapshot. 

Rather than generating a snapshot on-demand when HomeKit requests one, how about a background routine that grabs the latest snapshot every 60^ seconds or so?  That way the plugin can simply return the cached image when HomeKit requests it.

^The frequency could be configurable based on what suits the individual user's needs.

### Device Type

Floodlight (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X 11+ (Supported)

### Relevant log output

```shell
N/A
```

**Comment by thieren** [comment]
Hi @fullphat 

this is already planned and will be implemented with #33

**Comment by fullphat** [comment]
Awesome!

**Comment by thieren** [comment]
Added with 2.0.1-beta.5

Feedback would be appreciated (Please use #33)

Closed.
