### ISSUE TITLE
[enhancement]: SoloCam S40

### ISSUE THREAD

**Issue by Sebi1975** [homebridge-eufy-security/plugin#89]
### Describe the solution you'd like

Hello, 
will the SoloCam S40 be supported soon? Or isn´t it possible because of hardware issues?

With best regards.

Sebastiano

**Comment by thieren** [comment]
Hi @Sebi1975 

Unfortunately I don't have a listing which device corresponds to which serial number and to which internal type-id from eufy.

When you start the plugin (e.g. restart homebridge) there should be a line saying something like `This accessory is not compatible with HomeBridge Eufy Security plugin:...`
Can you copy this here?

**Comment by schliemann** [comment]
According to this issue on the client library it should already be supported. 

https://github.com/bropat/eufy-security-client/issues/54

However there might still be a battery drain issue

https://github.com/bropat/eufy-security-client/issues/54

**Comment by thieren** [comment]
stale
