### ISSUE TITLE
[Bug]: can’t remove triggered status

### ISSUE THREAD

**Issue by mariomaz87** [homebridge-eufy-security/plugin#9]
### What happened?

Hi, when my Eufy Base gets triggered, I can change status and for a while it’s ok, but after some minutes it gets back to triggered. I have to reboot HomeBridge in order to fix the problem. Can I do some troubleshooting? Thanks!

### Device Type

Station (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

**Comment by mariomaz87** [comment]
> Did you check this [Common Issues](https://github.com/homebridge-eufy-security/plugin/wiki/Common-Issues) pages ?

Yes, didn’t help :(

**Comment by lenoxys** [comment]
Able to reproduce please bear with me I have not spare time to works on

**Comment by thieren** [comment]
Stale and from the history of this issue I believe this is resolved. Please reopen if still relevant.
