### ISSUE TITLE
[Bug]: Upgrade from 1.0.8 to 2.0.x fails via  Homebridge UI

### ISSUE THREAD

**Issue by eulisef** [homebridge-eufy-security/plugin#96]
### What happened?

I have been trying to upgrade this plugin via Homebridge UI but it gives me an error message on every attempt.
Please see the attached log output. It seems to have something to do with permissions on the ffmpeg-for-homebridge package but I am not sure.
Any help?
Thanks,

### Device Type

Doorbell (Supported)

### Plugin Version

other (UnSupported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
USER: homebridge
DIR: /var/lib/homebridge
CMD: pnpm install --save homebridge-eufy-security@latest

Packages: +24 -5
++++++++++++++++++++++++-----
Progress: resolved 513, reused 511, downloaded 2, added 23, done
node_modules/.pnpm/ffmpeg-for-homebridge@0.1.0/node_modules/ffmpeg-for-homebridge: Runnnode_modules/.pnpm/ffmpeg-for-homebridge@0.1.0/node_modules/ffmpeg-for-homebridge: Running install script, failed in 1s
.../node_modules/ffmpeg-for-homebridge install$ node install.js
│ Downloading ffmpeg from https://github.com/homebridge/ffmpeg-for-homebridge/release
│ node:events:505
│       throw er; // Unhandled 'error' event
│       ^
│ Error: EACCES: permission denied, open '/home/homebridge/.npm/_ffmpeg_for_homebridg
│ Emitted 'error' event on WriteStream instance at:
│     at emitErrorNT (node:internal/streams/destroy:157:8)
│     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
│     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
│   errno: -13,
│   code: 'EACCES',
│   syscall: 'open',
│   path: '/home/homebridge/.npm/_ffmpeg_for_homebridge/.download'
│ }
└─ Failed in 1s
 ELIFECYCLE  Command failed with exit code 1.

Operation failed. Please review log for details.
```

**Comment by thieren** [comment]
Hi @eulisef 

this issue might be a duplicate of #47 

Try the steps described in this issue, but likely it will be resolved by updating manually via cli: `sudo npm install -g homebridge-eufy-security@latest`

For some reasons the installer seems to have a problem with certain environment variables on some systems. Therefore the used option `-E` through the homebridge UI causes this error.

Let me know if this resolves your issue. I will add a section to [common issues](https://github.com/homebridge-eufy-security/plugin/wiki/Common-Issues#update-issues), if this helps you too.

**Comment by eulisef** [comment]
Hi Thieren,

I tried following issue #47 , i tried the common issues section and going via cli for both ffmpeg-for-homebridge and your suggestion... both went through without any error message but i am still on 1.0.8...

pi@raspberrypi:~ $ sudo npm i ffmpeg-for-homebridge -g
changed 16 packages, and audited 17 packages in 9s
4 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
pi@raspberrypi:~ $ sudo npm install -g homebridge-eufy-security@latest
changed 145 packages, and audited 146 packages in 48s
23 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities

**Comment by eulisef** [comment]
And when i tried via Homebridge UI now I got this error:

USER: homebridge
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-eufy-security@2.0.1

npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /home/homebridge/.npm/_cacache/tmp/caff1a1e
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 999:996 "/home/homebridge/.npm"

npm ERR! Log files were not written due to an error writing to the directory: /home/homebridge/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal

Operation failed. Please review log for details.

**Comment by eulisef** [comment]
ok... it worked.
i followed the recommendation from the latest error and ran this from cli:

sudo chown -R 999:996 "/home/homebridge/.npm"

afterwards i tried again and now it updated properly

**Comment by thieren** [comment]
Ok. Good to know that this is caused by a bug in npm.
Didn't knew this error message until now.
